# Generated by Django 5.2.12 on 2026-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID de Llamada"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Número de Teléfono"),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL de la Grabación",
                    ),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True, null=True, verbose_name="Transcripción de IA"
                    ),
                ),
                (
                    "department_detected",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Departamento Detectado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción de Llamada",
                "verbose_name_plural": "Interacciones de Llamadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
