# Generated by Django 5.2.12 on 2026-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        default="",
                        max_length=100,
                        unique=True,
                        verbose_name="SID de Llamada",
                    ),
                ),
                (
                    "stream_sid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SID de Stream",
                    ),
                ),
                (
                    "account_sid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SID de Cuenta",
                    ),
                ),
                (
                    "from_number",
                    models.CharField(max_length=20, verbose_name="Número de Origen"),
                ),
                (
                    "to_number",
                    models.CharField(max_length=20, verbose_name="Número de Destino"),
                ),
                (
                    "direction",
                    models.CharField(
                        default="inbound", max_length=20, verbose_name="Dirección"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("ringing", "Llamando"),
                            ("in-progress", "En curso (Streaming)"),
                            ("completed", "Completada"),
                            ("failed", "Fallida"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Estado de Interacción",
                    ),
                ),
                (
                    "full_transcript",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Historial de Conversación (Log)",
                    ),
                ),
                (
                    "department_detected",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Departamento Detectado",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="Duración"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=10,
                        null=True,
                        verbose_name="Coste Estimado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción de Voz Twilio",
                "verbose_name_plural": "Interacciones de Voz Twilio",
                "ordering": ["-created_at"],
            },
        ),
    ]
