# Generated by Django 5.2.12 on 2026-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveTestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, verbose_name="ID de Sesión"),
                ),
                (
                    "api_version",
                    models.CharField(
                        default="v1beta", max_length=20, verbose_name="Versión de API"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="models/gemini-3.1-flash-live-preview",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "request_initiated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Inicio de Petición"
                    ),
                ),
                (
                    "setup_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Handshake Completado"
                    ),
                ),
                (
                    "first_response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Primera Respuesta de IA"
                    ),
                ),
                (
                    "connection_closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cierre de Conexión"
                    ),
                ),
                (
                    "handshake_latency_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Latencia Handshake (ms)"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="¿Éxito?"),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log de Errores"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Diagnóstico Live",
                "verbose_name_plural": "Logs de Diagnóstico Live",
                "ordering": ["-request_initiated_at"],
            },
        ),
    ]
