# Generated by Django 5.2.12 on 2026-07-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ivr_config", "0042_companyuser_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "Identificador legible para elegirla en el panel, "
                            "ej. 'Envio de documentacion a organismo'."
                        ),
                        max_length=150,
                        verbose_name="Nombre interno de la plantilla",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Asunto"),
                ),
                (
                    "body",
                    models.TextField(
                        help_text=(
                            "Texto generico para copiar y pegar en el cliente "
                            "de correo del usuario, junto con el PDF generado "
                            "aparte."
                        ),
                        verbose_name="Cuerpo del mensaje",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Activa"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima modificacion",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de email",
                "verbose_name_plural": "Plantillas de email",
            },
        ),
        migrations.CreateModel(
            name="DocumentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        verbose_name="ID del documento",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        verbose_name="Fecha de caducidad del documento",
                    ),
                ),
                (
                    "alert_offset_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text=(
                            "Cuantos dias antes de la fecha de caducidad se "
                            "dispara la alerta."
                        ),
                        verbose_name="Dias de antelacion para avisar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviada"),
                            ("RESOLVED", "Resuelta"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envio",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de resolucion",
                    ),
                ),
                (
                    "resolution_notes",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Notas de resolucion",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_alerts",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        related_name="document_alerts",
                        to="ivr_config.companyuser",
                        verbose_name="Contacto(s) a los que avisar",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_alerts_resolved",
                        to="ivr_config.companyuser",
                        verbose_name="Resuelta por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de documento",
                "verbose_name_plural": "Alertas de documento",
            },
        ),
        migrations.AddIndex(
            model_name="documentalert",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="document_ma_content_9e3f7a_idx",
            ),
        ),
    ]
