# Generated by Django 5.2.12 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentalert",
            name="document_label",
            field=models.CharField(
                default="",
                help_text="Ej. 'Certificado OCA 2025-2026'.",
                max_length=255,
                verbose_name="Nombre legible del documento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentalert",
            name="subject_label",
            field=models.CharField(
                default="",
                help_text=(
                    "Ej. 'A-45 -- LIEBHERR LTM 1055' (maquina) hoy; nombre "
                    "de trabajador cuando H25 lo consuma."
                ),
                max_length=255,
                verbose_name="Nombre legible del sujeto",
            ),
            preserve_default=False,
        ),
    ]
