# Generated by Django 5.2.12 on 2026-07-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ivr_config", "0042_companyuser_base"),
        ("document_management", "0002_documentalert_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSubstitutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "superseding_object_id",
                    models.PositiveBigIntegerField(
                        verbose_name="ID del documento vigente",
                    ),
                ),
                (
                    "superseding_label",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre legible del documento vigente",
                    ),
                ),
                (
                    "superseded_object_id",
                    models.PositiveBigIntegerField(
                        verbose_name="ID del documento archivado",
                    ),
                ),
                (
                    "superseded_label",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre legible del documento archivado",
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        help_text="Ej. 'A-45 -- LIEBHERR LTM 1055' (maquina).",
                        max_length=255,
                        verbose_name="Nombre legible del sujeto",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        max_length=100, verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "reasoning",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Texto de vigencia_service.evaluate_substitution() "
                            "explicando por que prevalece uno u otro."
                        ),
                        max_length=255,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de la sustitucion",
                    ),
                ),
                (
                    "superseding_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Tipo del documento vigente",
                    ),
                ),
                (
                    "superseded_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="Tipo del documento archivado",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_substitution_logs",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de sustitución de documento",
                "verbose_name_plural": "Historial de sustituciones de documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentsubstitutionlog",
            index=models.Index(
                fields=["company", "-created_at"],
                name="document_ma_company_5f8a1c_idx",
            ),
        ),
    ]
