# /home/MiguelAeTxio/PROJECTS/EnterpriseBot/chat/models.py
"""
Data models for the chat module of EnterpriseBot.

H17 — Paso 1: ChatRoom, ChatMessage and BreakdownConversationTurn removed.
BreakdownTicket.room (FK → ChatRoom) replaced by BreakdownTicket.company
(FK → Company) for direct company scoping without the chat room indirection.

BreakdownTicket lifecycle (Hito 14 redesign):
  OPEN → IN_PROGRESS (operario asignado) → CLOSED
  OPEN/IN_PROGRESS → PAUSED (operario reasignado a otro ticket)
  ticket_date_code: YYYYMMDD-NN (diario por empresa, ej. 20260618-01)
  origin: MANUAL (panel) | CHATBOT (agente Gemini WhatsApp) | IVR (llamada de voz)
---
Modelos de datos para el módulo de chat de EnterpriseBot.

H17 — Paso 1: ChatRoom, ChatMessage y BreakdownConversationTurn eliminados.
BreakdownTicket.room (FK → ChatRoom) sustituido por BreakdownTicket.company
(FK → Company) para acceso directo a la empresa sin la indirección de la sala.

Ciclo de vida BreakdownTicket (rediseño Hito 14):
  OPEN → IN_PROGRESS (operario asignado) → CLOSED
  OPEN/IN_PROGRESS → PAUSED (operario reasignado a otro ticket)
  ticket_date_code: YYYYMMDD-NN (diario por empresa, ej. 20260618-01)
  origin: MANUAL (panel) | CHATBOT (agente Gemini WhatsApp) | IVR (llamada de voz)
"""

from django.db import models
from django.utils import timezone

from ivr_config.models import Company, CompanyUser, Contact, Section


class BreakdownTicket(models.Model):
    """
    Represents a breakdown ticket created either manually from the panel,
    automatically by the Gemini WhatsApp agent, or via the IVR voice channel.

    Status lifecycle (Hito 14 redesign):
      OPEN        — ticket created, no operator assigned.
      IN_PROGRESS — operator assigned; ticket is an active repair order (OT).
      PAUSED      — operator was reassigned to another ticket; awaiting a new one.
      CLOSED      — work finished; resolved_by and resolved_at are set.

    ticket_date_code: human-readable identifier YYYYMMDD-NN, daily sequential
    per company (e.g. 20260618-01). Assigned automatically on first save().

    origin: MANUAL (panel creation) | CHATBOT (Gemini WhatsApp agent) | IVR (voice call).

    BreakdownTickets are never automatically purged.
    ---
    Representa un ticket de avería creado manualmente desde el panel,
    automáticamente por el agente Gemini de WhatsApp, o a través del
    canal de voz IVR.

    Ciclo de vida del estado (rediseño Hito 14):
      OPEN        — ticket creado, sin operario asignado.
      IN_PROGRESS — operario asignado; el ticket es una OT activa.
      PAUSED      — el operario fue reasignado a otro ticket; espera uno nuevo.
      CLOSED      — trabajo finalizado; resolved_by y resolved_at asignados.

    ticket_date_code: identificador legible YYYYMMDD-NN, secuencial diario
    por empresa (ej. 20260618-01). Se asigna automáticamente en el primer save().

    origin: MANUAL (creación desde panel) | CHATBOT (agente Gemini WhatsApp) | IVR (llamada de voz).

    Los BreakdownTicket nunca se eliminan automáticamente.
    """

    # --- Status choices ---------------------------------------------------
    STATUS_OPEN        = "OPEN"
    STATUS_IN_PROGRESS = "IN_PROGRESS"
    STATUS_PAUSED      = "PAUSED"
    STATUS_CLOSED      = "CLOSED"
    STATUS_CHOICES     = [
        (STATUS_OPEN,        "Abierto"),
        (STATUS_IN_PROGRESS, "En curso"),
        (STATUS_PAUSED,      "Pausado"),
        (STATUS_CLOSED,      "Cerrado"),
    ]

    # --- Urgency choices --------------------------------------------------
    URGENCY_LOW      = "LOW"
    URGENCY_MEDIUM   = "MEDIUM"
    URGENCY_HIGH     = "HIGH"
    URGENCY_CRITICAL = "CRITICAL"
    URGENCY_CHOICES  = [
        (URGENCY_LOW,      "Baja"),
        (URGENCY_MEDIUM,   "Media"),
        (URGENCY_HIGH,     "Alta"),
        (URGENCY_CRITICAL, "Crítica"),
    ]

    # --- Origin choices ---------------------------------------------------
    ORIGIN_MANUAL  = "MANUAL"
    ORIGIN_CHATBOT = "CHATBOT"
    ORIGIN_IVR     = "IVR"
    # ORIGIN_AUTO: ticket pregenerado por el sistema (H10 Paso 4-bis,
    # chat/services.py::get_or_create_ticket_for_machine) al registrar
    # una tarea de parte o confirmar un albarán sin ningún ticket
    # OPEN/IN_PROGRESS ni cerrado reciente para la máquina -- metadato
    # meramente informativo (diseño Paso 4-bis, punto 6), nunca bloqueante.
    # ORIGIN_AUTO: ticket pregenerated by the system (H10 Paso 4-bis,
    # chat/services.py::get_or_create_ticket_for_machine) when recording
    # a task or confirming a delivery note with no OPEN/IN_PROGRESS or
    # recently closed ticket for the machine -- purely informative
    # metadata (Paso 4-bis design, point 6), never blocking.
    ORIGIN_AUTO    = "AUTO"
    ORIGIN_CHOICES = [
        (ORIGIN_MANUAL,  "Manual"),
        (ORIGIN_CHATBOT, "Chatbot"),
        (ORIGIN_IVR,     "IVR (llamada de voz)"),
        (ORIGIN_AUTO,    "Auto-generado"),
    ]

    # --- Tipo de tarea (H10 Paso 4-bis, punto 4) ---------------------------
    # BreakdownTicket amplía su alcance para anclar no solo averías sino
    # cualquier tarea (mejora, mantenimiento, fabricación...). fault_category/
    # fault_subcategory (en WorkOrderEntryLine) solo aplican cuando
    # tipo_tarea=AVERIA; para el resto, task_category_free recoge una
    # categorización libre sin taxonomía rígida. Clasificado por Gemini,
    # asíncrono (Celery), al grabar la tarea -- ver
    # work_order_processor.tasks.classify_fault_line.
    # ---
    # BreakdownTicket widens its scope to anchor not just breakdowns but any
    # task (improvement, maintenance, fabrication...). fault_category/
    # fault_subcategory (on WorkOrderEntryLine) only apply when
    # tipo_tarea=AVERIA; for everything else, task_category_free holds a
    # free-form categorization with no rigid taxonomy. Classified by Gemini,
    # asynchronously (Celery), when the task is saved -- see
    # work_order_processor.tasks.classify_fault_line.
    TIPO_TAREA_AVERIA        = "AVERIA"
    TIPO_TAREA_MEJORA        = "MEJORA"
    TIPO_TAREA_MANTENIMIENTO = "MANTENIMIENTO"
    TIPO_TAREA_FABRICACION   = "FABRICACION"
    TIPO_TAREA_CHOICES = [
        (TIPO_TAREA_AVERIA,        "Avería"),
        (TIPO_TAREA_MEJORA,        "Mejora"),
        (TIPO_TAREA_MANTENIMIENTO, "Mantenimiento"),
        (TIPO_TAREA_FABRICACION,   "Fabricación"),
    ]
    tipo_tarea = models.CharField(
        max_length=15,
        choices=TIPO_TAREA_CHOICES,
        blank=True,
        default="",
        verbose_name="Tipo de tarea",
        help_text=(
            "Naturaleza de la tarea anclada a este ticket. Vacío hasta que "
            "la tarea Celery classify_fault_line lo clasifica al grabar la "
            "primera tarea del ticket. AVERIA usa fault_category/"
            "fault_subcategory (en WorkOrderEntryLine); el resto usa "
            "task_category_free."
        ),
    )
    task_category_free = models.CharField(
        max_length=200,
        blank=True,
        default="",
        verbose_name="Categoría de tarea (libre)",
        help_text=(
            "Categorización libre generada por Gemini para tareas con "
            "tipo_tarea distinto de AVERIA (mejora, mantenimiento, "
            "fabricación...), sin taxonomía rígida. Vacío cuando "
            "tipo_tarea=AVERIA (se usa fault_category/fault_subcategory "
            "en su lugar) o cuando el ticket todavía no se ha clasificado."
        ),
    )

    # --- ticket_date_code: YYYYMMDD-NN daily sequential per company. ------
    ticket_date_code = models.CharField(
        max_length=11,
        blank=True,
        default="",
        verbose_name="Código de ticket",
        help_text=(
            "Identificador legible del ticket: YYYYMMDD-NN. "
            "Secuencial diario por empresa. Se asigna automáticamente "
            "en el primer save()."
        ),
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="breakdown_tickets",
        verbose_name="Empresa",
        help_text="Empresa a la que pertenece este ticket de avería.",
    )
    contact = models.ForeignKey(
        Contact,
        on_delete=models.CASCADE,
        related_name="breakdown_tickets",
        verbose_name="Contacto",
        help_text="Contacto de WhatsApp que inició el reporte de avería.",
    )
    reported_by = models.ForeignKey(
        Contact,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reported_breakdown_tickets",
        verbose_name="Detectado por",
        help_text=(
            "Contacto que detectó la avería. Puede diferir del contacto "
            "que abrió el ticket (ej. chofer que llama vs. jefe de taller)."
        ),
    )
    section = models.ForeignKey(
        "ivr_config.Section",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="breakdown_tickets",
        verbose_name="Sección",
        help_text=(
            "Sección del contacto en el momento de abrir el ticket. "
            "Se registra para trazabilidad aunque la membresía M2M pueda cambiar."
        ),
    )
    machine = models.ForeignKey(
        "fleet.MachineAsset",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="breakdown_tickets",
        verbose_name="Máquina / Centro de gasto",
        help_text=(
            "MachineAsset resuelto a partir de machine_raw. "
            "Null hasta que se identifica la máquina en el catálogo."
        ),
    )
    origin = models.CharField(
        max_length=8,
        choices=ORIGIN_CHOICES,
        default=ORIGIN_MANUAL,
        verbose_name="Origen",
        help_text="Indica si el ticket fue creado manualmente, por el chatbot o por IVR.",
    )
    fault_category = models.CharField(
        max_length=30,
        blank=True,
        default="",
        verbose_name="Categoría de avería",
        help_text=(
            "Categoría principal de la avería. Usa los mismos códigos que "
            "FaultCategory en work_order_processor (ej. HYDRAULIC, ELECTRICAL_ELECTRONIC)."
        ),
    )
    photos = models.JSONField(
        default=list,
        verbose_name="Fotos adjuntas",
        help_text=(
            "Lista de rutas o URLs de las fotos adjuntas enviadas por el "
            "contacto durante el diálogo. El agente Gemini acepta hasta 3 "
            "imágenes vía WhatsApp Media."
        ),
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=STATUS_OPEN,
        verbose_name="Estado",
        help_text=(
            "Estado actual del ticket. "
            "Ciclo: OPEN → IN_PROGRESS → CLOSED | OPEN/IN_PROGRESS → PAUSED."
        ),
    )
    machine_raw = models.CharField(
        max_length=200,
        blank=True,
        default="",
        verbose_name="Máquina / Vehículo",
        help_text=(
            "Identificación de la máquina o vehículo afectado tal como "
            "la describe el contacto o el agente."
        ),
    )
    fault_summary = models.TextField(
        blank=True,
        default="",
        verbose_name="Resumen de la avería",
        help_text="Descripción de la avería recogida mediante diálogo o entrada manual.",
    )
    location = models.CharField(
        max_length=200,
        blank=True,
        default="",
        verbose_name="Ubicación",
        help_text="Ubicación actual del vehículo o lugar donde ocurrió la avería.",
    )
    urgency = models.CharField(
        max_length=10,
        choices=URGENCY_CHOICES,
        blank=True,
        default="",
        verbose_name="Urgencia",
        help_text="Nivel de urgencia.",
    )
    notes = models.TextField(
        blank=True,
        default="",
        verbose_name="Notas adicionales",
        help_text="Observaciones adicionales recogidas durante el diálogo o la gestión.",
    )
    # --- Paso 23 H14: geolocalización y ubicación exacta en máquina -------
    fault_location = models.CharField(
        max_length=255,
        blank=True,
        default="",
        verbose_name="Ubicación en máquina",
        help_text=(
            "Ubicación exacta de la avería en la máquina "
            "(ej. 'rueda delantera lado conductor'). "
            "Recogida por el agente IVR o WhatsApp."
        ),
    )
    geo_lat = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        null=True,
        blank=True,
        verbose_name="Latitud GPS",
        help_text=(
            "Latitud GPS real de la avería. Recibida vía WhatsApp location "
            "o resuelta desde la base más próxima."
        ),
    )
    geo_lng = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        null=True,
        blank=True,
        verbose_name="Longitud GPS",
        help_text=(
            "Longitud GPS real de la avería. Recibida vía WhatsApp location "
            "o resuelta desde la base más próxima."
        ),
    )
    location_warning = models.BooleanField(
        default=False,
        verbose_name="Sin geolocalización",
        help_text=(
            "True si no se pudo obtener geolocalización: el contacto no envió "
            "ubicación o se superó el timeout de 3 minutos."
        ),
    )
    assigned_to = models.ForeignKey(
        CompanyUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_breakdown_tickets",
        verbose_name="Asignado a",
        help_text=(
            "Operario de taller (WORKSHOPBOSS) al que se ha asignado este ticket. "
            "Null cuando el ticket está disponible para asignar."
        ),
    )
    paused_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Fecha de pausa",
        help_text=(
            "Timestamp en que el ticket pasó a estado PAUSED por "
            "reasignación del operario a otro ticket."
        ),
    )
    resolved_by = models.ForeignKey(
        CompanyUser,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="resolved_breakdown_tickets",
        verbose_name="Cerrado por",
        help_text="Usuario del panel que cerró el ticket.",
    )
    resolved_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Fecha de cierre",
        help_text="Timestamp en que se marcó el ticket como CLOSED.",
    )
    # --- H17 Paso 2: log de conversación unificado IVR + WhatsApp ----------
    conversation_log = models.JSONField(
        default=list,
        verbose_name="Log de conversación",
        help_text=(
            "Historial unificado de la conversación asociada a este ticket. "
            "Lista de entradas con formato: "
            "{timestamp, source ('IVR'|'WHATSAPP'|'SYSTEM'), role ('USER'|'MODEL'), content}. "
            "Poblado por el agente IVR (Alia) y el agente WhatsApp."
        ),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Fecha de creación",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="Fecha de modificación",
    )

    class Meta:
        verbose_name = "Ticket de avería"
        verbose_name_plural = "Tickets de avería"
        ordering = ["-created_at"]

    def save(self, *args, **kwargs):
        """
        Assigns ticket_date_code on first save if not already set.
        Format: YYYYMMDD-NN — daily sequential per company (01-99).
        ---
        Asigna ticket_date_code en el primer save si no está asignado.
        Formato: YYYYMMDD-NN — secuencial diario por empresa (01-99).
        """
        if not self.ticket_date_code:
            today    = timezone.localdate()
            date_str = today.strftime("%Y%m%d")
            company  = self.company if self.company_id else None
            if company:
                existing = BreakdownTicket.objects.filter(
                    company=company,
                    ticket_date_code__startswith=date_str,
                ).count()
                ordinal = existing + 1
            else:
                ordinal = 1
            self.ticket_date_code = f"{date_str}-{ordinal:02d}"
        super().save(*args, **kwargs)

    def __str__(self):
        code = self.ticket_date_code or f"pk:{self.pk}"
        return (
            f"[{code}] [{self.get_status_display()}] "
            f"{self.machine_raw or 'Máquina no identificada'}"
        )
