# Generated by Django 5.2.12 on 2026-04-22 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0010_alter_datacaptureset_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_pdf",
                    models.FileField(
                        help_text="Archivo PDF con las fotografías de los partes de trabajo.",
                        upload_to="work_orders/pdf/%Y/%m/",
                        verbose_name="PDF Original",
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        help_text="Informe Excel generado automáticamente. Disponible únicamente cuando el estado es DONE.",
                        null=True,
                        upload_to="work_orders/excel/%Y/%m/",
                        verbose_name="Informe Excel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("DONE", "Completado"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Estado actual del procesamiento del PDF.",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se subió el PDF al sistema.",
                        verbose_name="Fecha de Carga",
                    ),
                ),
                (
                    "total_pages",
                    models.IntegerField(
                        default=0,
                        help_text="Número total de páginas detectadas en el PDF original.",
                        verbose_name="Total de Páginas",
                    ),
                ),
                (
                    "processed_pages",
                    models.IntegerField(
                        default=0,
                        help_text="Número de páginas procesadas correctamente por Gemini Vision.",
                        verbose_name="Páginas Procesadas",
                    ),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True,
                        help_text="Detalle de errores producidos durante el procesamiento. Se cumplimenta únicamente cuando el estado es ERROR.",
                        verbose_name="Registro de Errores",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa propietaria de este parte de trabajo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Usuario de empresa que realizó la carga del PDF.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="ivr_config.companyuser",
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parte de Trabajo",
                "verbose_name_plural": "Partes de Trabajo",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        help_text="Número de página en el PDF original (base 1).",
                        verbose_name="Número de Página",
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre completo del operario tal como aparece en el parte.",
                        max_length=200,
                        verbose_name="Nombre del Operario",
                    ),
                ),
                (
                    "work_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la jornada registrada en el parte.",
                        null=True,
                        verbose_name="Fecha del Parte",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de inicio de la jornada (H.C.).",
                        null=True,
                        verbose_name="Hora de Inicio",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de fin de la jornada (H.F.).",
                        null=True,
                        verbose_name="Hora de Fin",
                    ),
                ),
                (
                    "vehicle_ref",
                    models.CharField(
                        blank=True,
                        help_text="Código o matrícula del vehículo tal como aparece en el parte. Se normaliza según directriz D4 antes de cruzar con el catálogo.",
                        max_length=100,
                        verbose_name="Referencia de Vehículo",
                    ),
                ),
                (
                    "work_description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de las tareas realizadas durante la jornada. Interpretada en contexto de vehículos pesados industriales (D7).",
                        verbose_name="Descripción de los Trabajos",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lugar o dirección donde se realizaron los trabajos.",
                        max_length=300,
                        verbose_name="Lugar de Intervención",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales anotadas por el operario.",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "raw_gemini_response",
                    models.JSONField(
                        blank=True,
                        help_text="Respuesta JSON completa devuelta por Gemini Vision para esta página. Se conserva íntegra para auditoría y trazabilidad de la extracción.",
                        null=True,
                        verbose_name="Respuesta Cruda de Gemini",
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("HIGH", "Alta"),
                            ("MEDIUM", "Media"),
                            ("LOW", "Baja"),
                            ("FAILED", "Fallida"),
                        ],
                        default="MEDIUM",
                        help_text="Nivel de confianza global de la extracción para esta página, evaluado por Gemini Vision.",
                        max_length=10,
                        verbose_name="Confianza de Extracción",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Parte de trabajo al que pertenece esta entrada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="work_order_processor.workorder",
                        verbose_name="Parte de Trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Parte",
                "verbose_name_plural": "Entradas de Parte",
                "ordering": ["work_order", "page_number"],
                "unique_together": {("work_order", "page_number")},
            },
        ),
    ]
