# Generated by Django 5.2.12 on 2026-04-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("work_order_processor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorderentry",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="workorderentry",
            name="location",
        ),
        migrations.RemoveField(
            model_name="workorderentry",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="workorderentry",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="workorderentry",
            name="vehicle_ref",
        ),
        migrations.RemoveField(
            model_name="workorderentry",
            name="work_description",
        ),
        migrations.AddField(
            model_name="workorderentry",
            name="fecha_incierta",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la fecha de esta página es dudosa y requiere verificación humana (directriz D1 de la skill partes-trabajo).",
                verbose_name="Fecha Incierta",
            ),
        ),
        migrations.AlterField(
            model_name="workorderentry",
            name="work_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha de la jornada registrada en el parte. Puede ser deducida por contexto calendario (directriz D2).",
                null=True,
                verbose_name="Fecha del Parte",
            ),
        ),
        migrations.AlterField(
            model_name="workorderentry",
            name="work_order",
            field=models.ForeignKey(
                help_text="Parte de trabajo al que pertenece esta entrada de página.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="work_order_processor.workorder",
                verbose_name="Parte de Trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="workorderentry",
            name="worker_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del operario derivado del nombre del fichero PDF fuente. Formato: NOMBRE APELLIDO1 APELLIDO2 en mayúsculas. No se extrae del texto manuscrito para evitar variantes ortográficas.",
                max_length=200,
                verbose_name="Nombre del Operario",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(
                        help_text="Posición del bloque dentro de la página (1–4). Refleja el orden de aparición en el formulario impreso.",
                        verbose_name="Número de Bloque",
                    ),
                ),
                (
                    "maquina_raw",
                    models.CharField(
                        blank=True,
                        help_text="Referencia de máquina tal como la extrae Gemini Vision del manuscrito. Se preserva sin modificar para auditoría.",
                        max_length=100,
                        verbose_name="Máquina (Raw)",
                    ),
                ),
                (
                    "maquina_norm",
                    models.CharField(
                        blank=True,
                        help_text="Referencia de máquina normalizada según directriz D4: mayúsculas, guion entre letra y número, relleno de ceros. Clave usada para la búsqueda en MachineAsset.",
                        max_length=100,
                        verbose_name="Máquina (Normalizada)",
                    ),
                ),
                (
                    "descripcion_averia",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la avería o tarea anotada en el parte. Interpretada en contexto de vehículos pesados industriales (D7).",
                        verbose_name="Descripción de Avería",
                    ),
                ),
                (
                    "reparacion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la reparación o intervención realizada, tal como figura en la columna REPARACION del formulario.",
                        verbose_name="Reparación",
                    ),
                ),
                (
                    "hc",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de inicio del bloque de trabajo. Redondeada a fracción de media hora según directriz D3.",
                        null=True,
                        verbose_name="H.C. (Hora de Comienzo)",
                    ),
                ),
                (
                    "hf",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de fin del bloque de trabajo. Redondeada a fracción de media hora según directriz D3.",
                        null=True,
                        verbose_name="H.F. (Hora de Finalización)",
                    ),
                ),
                (
                    "or_val",
                    models.CharField(
                        blank=True,
                        help_text="Referencia de Orden de Reparación anotada en el parte, si existe.",
                        max_length=50,
                        verbose_name="O.R.",
                    ),
                ),
                (
                    "delta_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas netas del bloque tras descontar la pausa de comida (13:30–15:00, 90 min) si el tramo la cubre. Calculado automáticamente durante el procesamiento.",
                        max_digits=5,
                        null=True,
                        verbose_name="Δ Horas (Netas)",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de campos con lectura incierta en este bloque. Valores posibles: 'H.C.', 'H.F.', 'DESCRIPCION', 'MAQUINA'. Se usa para generar el Manifiesto de Incidencias en el Excel.",
                        verbose_name="Flags de Incidencia",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="Página del parte a la que pertenece este bloque de trabajo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="work_order_processor.workorderentry",
                        verbose_name="Entrada de Página",
                    ),
                ),
                (
                    "machine_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Máquina del catálogo de flota resuelta a partir de maquina_norm. Nulo si el código no se encontró en el catálogo tras aplicar D4.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines",
                        to="fleet.machineasset",
                        verbose_name="Activo de Flota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Bloque de Trabajo",
                "verbose_name_plural": "Líneas de Bloque de Trabajo",
                "ordering": ["entry", "line_number"],
                "unique_together": {("entry", "line_number")},
            },
        ),
    ]
