# Generated by Django 5.2.12 on 2026-04-28 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0013_alter_companyuser_role"),
        ("work_order_processor", "0002_remove_workorderentry_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="reviewed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indica si un Supervisor ha revisado y validado este parte de trabajo. Se activa mediante WorkOrderMarkReviewedView.",
                verbose_name="Revisado",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp UTC en que el Supervisor marcó el parte como revisado. Se limpia automáticamente al desmarcar la revisión.",
                null=True,
                verbose_name="Fecha de revisión",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario de empresa (rol SUPERVISOR o ADMIN) que marcó el parte como revisado. Se limpia automáticamente al desmarcar la revisión.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_work_orders",
                to="ivr_config.companyuser",
                verbose_name="Revisado por",
            ),
        ),
    ]
