# Generated by Django 5.2.12 on 2026-04-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "work_order_processor",
            "0003_workorder_reviewed_workorder_reviewed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="source_pdf_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA-256 del fichero PDF original calculado en el momento de la carga. Permite detectar duplicados exactos con independencia del nombre del fichero. Vacío en registros anteriores a la implantación del Bloque I — rellenable mediante el comando de gestión backfill_pdf_hashes.",
                max_length=64,
                verbose_name="Hash SHA-256 del PDF",
            ),
        ),
    ]
