# Generated by Django 5.2.12 on 2026-04-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_maintenancelog_work_entry_line"),
        ("work_order_processor", "0004_workorder_source_pdf_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveSmallIntegerField(
                        help_text="Posición de esta línea de repuesto dentro del bloque de trabajo (base 1).",
                        verbose_name="Número de Línea",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencia del repuesto tal como aparece en el albarán del proveedor. Se usa como clave de identificación y puede usarse para inferir la descripción del material.",
                        max_length=100,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del material o repuesto. Puede inferirse de la referencia del albarán cuando el operario no la especifica explícitamente.",
                        max_length=200,
                        verbose_name="Material",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Número de unidades consumidas del repuesto. Admite decimales para materiales vendidos por peso o longitud.",
                        max_digits=9,
                        null=True,
                        verbose_name="Unidades",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SUPPLIER", "Proveedor"), ("WAREHOUSE", "Almacén")],
                        default="WAREHOUSE",
                        help_text="Indica si el material llegó directamente de un proveedor externo (Proveedor) o se extrajo del stock del almacén interno (Almacén).",
                        max_length=10,
                        verbose_name="Procedencia",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del proveedor externo. Se cumplimenta únicamente cuando source = SUPPLIER. Se deja vacío si el material es de almacén.",
                        max_length=200,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de campos con lectura incierta extraídos por Gemini Vision de la parte trasera del formulario. Valores posibles: 'REFERENCIA', 'MATERIAL', 'UNIDADES', 'VEHICULO', 'PROCEDENCIA'. Vacío para líneas introducidas manualmente (Form / STT).",
                        verbose_name="Flags de Incidencia",
                    ),
                ),
                (
                    "entry_line",
                    models.ForeignKey(
                        help_text="Bloque de trabajo al que pertenece este repuesto. Un bloque puede tener varios repuestos asociados.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Línea de Bloque de Trabajo",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehículo o máquina al que se imputa este repuesto. Suele coincidir con la máquina del bloque de trabajo, pero puede diferir si el repuesto se aplica a otra unidad.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_part_lines",
                        to="fleet.machineasset",
                        verbose_name="Vehículo / Centro de Gasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Repuesto",
                "verbose_name_plural": "Líneas de Repuesto",
                "ordering": ["entry_line", "line_number"],
                "unique_together": {("entry_line", "line_number")},
            },
        ),
    ]
