# Generated by Django 5.2.12 on 2026-05-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_alter_machineasset_options_and_more"),
        ("work_order_processor", "0009_workorder_has_cg_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentryline",
            name="crane_hours_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Lectura del horómetro de grúa (horas) en el momento del bloque de trabajo. Obligatoria si MachineAsset.has_crane_hours=True.",
                max_digits=10,
                null=True,
                verbose_name="Lectura horómetro grúa",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="engine_hours_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Lectura del horómetro de motor (horas) en el momento del bloque de trabajo. Obligatoria si MachineAsset.has_engine_hours=True.",
                max_digits=10,
                null=True,
                verbose_name="Lectura horómetro motor",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="odometer_reading",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Lectura del odómetro (kilómetros) en el momento del bloque de trabajo. Obligatoria si MachineAsset.has_odometer=True.",
                max_digits=10,
                null=True,
                verbose_name="Lectura km",
            ),
        ),
        migrations.AlterField(
            model_name="workorderentryline",
            name="machine_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Máquina del catálogo de flota resuelta a partir de machine_norm. Nulo si el código no se encontró en el catálogo tras aplicar D4.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_order_lines",
                to="fleet.machineasset",
                verbose_name="Activo de Flota",
            ),
        ),
    ]
