# Generated by Django 5.2.12 on 2026-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "work_order_processor",
            "0010_workorderentryline_crane_hours_reading_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepartline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio unitario del repuesto en el momento de la imputación. No lo rellena el operario — lo cumplimenta un SUPERVISOR o el pipeline de albaranes de proveedor (Hito 10). Permite calcular el coste de materiales por máquina en los informes de analítica cruzada (Hito 9).",
                max_digits=10,
                null=True,
                verbose_name="Precio unitario",
            ),
        ),
    ]
