# Generated by Django 5.2.12 on 2026-05-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0015_workerabsence_workperiod"),
        ("work_order_processor", "0011_sparepartline_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor o ADMIN que generó este parte sintético desde un registro de ausencia (WorkerAbsence). Nulo en partes subidos manualmente o enviados por el propio operario desde el panel.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_work_orders",
                to="ivr_config.companyuser",
                verbose_name="Generado por",
            ),
        ),
    ]
