# Generated by Django 5.2.12 on 2026-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0012_workorder_generated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="source",
            field=models.CharField(
                choices=[
                    ("PDF_UPLOAD", "Subida PDF (pipeline clásico)"),
                    ("DIGITAL", "Digital (operario — Form / STT / Upload)"),
                    ("GENERATED", "Generado automáticamente (ausencia)"),
                ],
                db_index=True,
                default="PDF_UPLOAD",
                help_text="Clasificación del origen del parte: PDF_UPLOAD (pipeline clásico de subida de PDF), DIGITAL (entrada directa del operario via Form/STT/Upload) o GENERATED (generado automáticamente desde un registro de ausencia).",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
    ]
