# Generated by Django 5.2.12 on 2026-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0013_workorder_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentryline",
            name="fault_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENGINE_TRANSMISSION", "Motor y transmisión"),
                    ("HYDRAULIC", "Sistema hidráulico"),
                    ("ELECTRICAL_ELECTRONIC", "Eléctrico y electrónico"),
                    ("BRAKES_STEERING_SUSPENSION", "Frenos, dirección y suspensión"),
                    ("TYRES_RUNNING_GEAR", "Neumáticos y rodadura"),
                    ("LIFTING_STRUCTURE", "Estructura y sistemas de elevación"),
                    ("BODYWORK_CHASSIS", "Carrocería y chasis"),
                    ("OTHER", "Otras averías"),
                ],
                db_index=True,
                default="",
                help_text="Grupo principal de avería asignado automáticamente por Gemini Flash tras el guardado del bloque. No lo rellena el operario. Vacío hasta que la tarea Celery classify_fault_line lo procese.",
                max_length=40,
                verbose_name="Categoría de avería",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="fault_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ET_ENGINE", "Motor"),
                    ("ET_TRANSMISSION", "Transmisión"),
                    ("ET_PTO", "Toma de fuerza (PTO)"),
                    ("ET_COOLING", "Sistema de refrigeración"),
                    ("ET_FUEL", "Sistema de combustible"),
                    ("HY_PUMP", "Bomba hidráulica"),
                    ("HY_CYLINDERS", "Cilindros hidráulicos"),
                    ("HY_VALVES", "Válvulas hidráulicas"),
                    ("HY_OIL", "Aceite y circuito hidráulico"),
                    ("HY_CENTRAL", "Central hidráulica"),
                    ("EE_WIRING", "Cableado y conectores"),
                    ("EE_SENSORS", "Sensores y sondas"),
                    ("EE_CONTROLS", "Mandos y controles"),
                    ("EE_LIGHTS", "Iluminación"),
                    ("EE_BATTERY", "Batería y sistema de carga"),
                    ("BSS_BRAKES", "Frenos"),
                    ("BSS_STEERING", "Dirección"),
                    ("BSS_SUSPENSION", "Suspensión"),
                    ("TRG_TYRES", "Neumáticos"),
                    ("TRG_AXLES", "Ejes y transmisión de rueda"),
                    ("TRG_TRACKS", "Cadenas y rodadura oruga"),
                    ("LS_BOOM", "Pluma y brazo"),
                    ("LS_HOOK_PULLEYS", "Gancho y poleas"),
                    ("LS_CABLE", "Cable de elevación"),
                    ("LS_ROTATION", "Sistema de rotación"),
                    ("LS_STABILIZERS", "Estabilizadores y apoyos"),
                    ("LS_MAST", "Mástil y horquillas"),
                    ("LS_PLATFORM", "Plataforma elevadora"),
                    ("LS_FIFTH_WHEEL", "Quinta rueda"),
                    ("LS_CHASSIS_TRAILER", "Chasis de semirremolque"),
                    ("BC_BODYWORK", "Carrocería"),
                    ("BC_CHASSIS", "Chasis estructural"),
                    ("OT_OTHER", "Otra avería no clasificada"),
                ],
                db_index=True,
                default="",
                help_text="Subgrupo detallado de avería asignado automáticamente por Gemini Flash tras el guardado del bloque. No lo rellena el operario. Vacío hasta que la tarea Celery classify_fault_line lo procese.",
                max_length=60,
                verbose_name="Subcategoría de avería",
            ),
        ),
    ]
