# Generated by Django 5.2.12 on 2026-05-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0016_workdayschedule_absencecategory"),
        ("work_order_processor", "0016_workorder_source_pdf_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PROCESSING", "Procesando"),
                    ("DONE", "Completado"),
                    ("ERROR", "Error"),
                    ("PENDING_GAPS", "Pendiente de justificación de jornada"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Estado actual del procesamiento del PDF.",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="WorkdayGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gap_type",
                    models.CharField(
                        choices=[
                            ("GAP", "Laguna entre bloques"),
                            ("LATE_START", "Inicio tardío"),
                            ("EARLY_END", "Cierre anticipado"),
                        ],
                        help_text="Tipo de desviación de jornada detectada por Gate 4.",
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "gap_start",
                    models.TimeField(
                        help_text="Hora de inicio del intervalo sin cubrir o de la desviación detectada.",
                        verbose_name="Inicio de laguna",
                    ),
                ),
                (
                    "gap_end",
                    models.TimeField(
                        help_text="Hora de fin del intervalo sin cubrir o de la desviación detectada.",
                        verbose_name="Fin de laguna",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        help_text="Duración de la laguna en minutos. Campo calculado — no editar manualmente.",
                        verbose_name="Duración (minutos)",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Nota libre del operario para justificar la laguna. Obligatoria cuando AbsenceCategory.requires_note=True.",
                        verbose_name="Nota",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando el operario ha asignado una AbsenceCategory y proporcionado nota si era requerida. Gate 4 requiere que todos los gaps de un WorkOrder estén resueltos antes de promoverlo a DONE.",
                        verbose_name="Resuelto",
                    ),
                ),
                (
                    "absence_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría de ausencia seleccionada por el operario para justificar esta laguna. Obligatoria para marcar el gap como resuelto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workday_gaps",
                        to="ivr_config.absencecategory",
                        verbose_name="Categoría de ausencia",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Parte digital al que pertenece esta laguna de jornada. El parte debe tener status=PENDING_GAPS mientras tenga gaps no resueltos.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workday_gaps",
                        to="work_order_processor.workorder",
                        verbose_name="Parte de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laguna de jornada",
                "verbose_name_plural": "Lagunas de jornada",
                "ordering": ["work_order", "gap_start"],
            },
        ),
    ]
