# Generated by Django 5.2.12 on 2026-05-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0018_workdayschedule_season_split_times"),
        ("work_order_processor", "0017_workdaygap_pending_gaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="workdaygap",
            name="lunch_had",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Solo para gaps de tipo LUNCH_BREAK. True: el operario paró a comer (gap resuelto sin nota). False: el operario no paró a comer — nota libre obligatoria. None: no aplica (gap de tipo distinto a LUNCH_BREAK).",
                null=True,
                verbose_name="¿Ha comido?",
            ),
        ),
        migrations.AddField(
            model_name="workdaygap",
            name="lunch_time",
            field=models.TimeField(
                blank=True,
                help_text="Solo para gaps de tipo LUNCH_BREAK cuando lunch_had=True. Hora aproximada a la que el operario paró a comer. Opcional.",
                null=True,
                verbose_name="Hora de comida",
            ),
        ),
        migrations.AlterField(
            model_name="workdaygap",
            name="absence_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría de ausencia seleccionada por el operario para justificar esta laguna. Obligatoria para gaps de tipo GAP, LATE_START y EARLY_END. No aplica para LUNCH_BREAK.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workday_gaps",
                to="ivr_config.absencecategory",
                verbose_name="Categoría de ausencia",
            ),
        ),
        migrations.AlterField(
            model_name="workdaygap",
            name="gap_type",
            field=models.CharField(
                choices=[
                    ("GAP", "Laguna entre bloques"),
                    ("LATE_START", "Inicio tardío"),
                    ("EARLY_END", "Cierre anticipado"),
                    ("LUNCH_BREAK", "Pausa de mediodía"),
                ],
                help_text="Tipo de desviación de jornada detectada por Gate 4.",
                max_length=15,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="workdaygap",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Nota libre del operario para justificar la laguna. Obligatoria cuando AbsenceCategory.requires_note=True (gaps estándar) o cuando lunch_had=False (LUNCH_BREAK).",
                verbose_name="Nota",
            ),
        ),
        migrations.AlterField(
            model_name="workdaygap",
            name="resolved",
            field=models.BooleanField(
                default=False,
                help_text="True cuando el operario ha completado la resolución del gap según las reglas de su tipo. Gate 4 requiere que todos los gaps de un WorkOrder estén resueltos antes de promoverlo a DONE.",
                verbose_name="Resuelto",
            ),
        ),
    ]
