# Generated by Django 5.2.12 on 2026-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0018_workdaygap_lunch_break"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentry",
            name="lunch_break_end",
            field=models.TimeField(
                blank=True,
                help_text="Hora de fin de la pausa de comida del operario. Prerrellenada desde el WorkdaySchedule (start_time_afternoon) cuando la jornada es partida. Nula si no ha parado a comer.",
                null=True,
                verbose_name="Fin pausa de comida",
            ),
        ),
        migrations.AddField(
            model_name="workorderentry",
            name="lunch_break_start",
            field=models.TimeField(
                blank=True,
                help_text="Hora de inicio de la pausa de comida del operario. Prerrellenada desde el WorkdaySchedule (end_time_morning) cuando la jornada es partida. Nula si no ha parado a comer.",
                null=True,
                verbose_name="Inicio pausa de comida",
            ),
        ),
    ]
