# Generated by Django 5.2.12 on 2026-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0019_add_lunch_break_to_workorderentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentry",
            name="no_lunch_break",
            field=models.BooleanField(
                default=False,
                help_text="Indica que el operario no ha realizado pausa de comida. Cuando está activo, el sistema no descuenta la pausa de comida del cálculo de horas ni valida la ventana de mediodía como laguna de jornada.",
                verbose_name="No he parado a comer",
            ),
        ),
    ]
