# Generated by Django 5.2.12 on 2026-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0020_add_no_lunch_break_to_workorderentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("PROCESSING", "Procesando"),
                    ("DONE", "Completado"),
                    ("ERROR", "Error"),
                    ("PENDING_GAPS", "Pendiente de justificación de jornada"),
                    ("IN_PROGRESS", "En curso (guardado progresivo)"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Estado actual del procesamiento del PDF.",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
