# Generated by Django 5.2.12 on 2026-06-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0032_add_section_is_broadcast_enabled"),
        ("work_order_processor", "0021_add_in_progress_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo de la plantilla. Visible en el modal de exportación.",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, esta plantilla se preselecciona automáticamente en el modal de exportación. Solo puede haber una plantilla por defecto por usuario.",
                        verbose_name="Plantilla por defecto",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="Lista ordenada de claves de columna a incluir en el Excel. Valores válidos: fecha, operario, maquina, descripcion, notas, hc, hf, delta_horas, estado, familia, origen.",
                        verbose_name="Columnas",
                    ),
                ),
                (
                    "sheet_format",
                    models.CharField(
                        choices=[
                            ("single_sheet", "Una sola hoja"),
                            ("multi_sheet", "Una hoja por operario"),
                        ],
                        default="single_sheet",
                        help_text="single_sheet: todas las filas en una sola hoja agrupadas por operario. multi_sheet: una hoja por operario distinto.",
                        max_length=20,
                        verbose_name="Formato de hoja",
                    ),
                ),
                (
                    "operator_scope",
                    models.CharField(
                        choices=[
                            ("all", "Todos los operarios"),
                            ("selection", "Selección manual"),
                        ],
                        default="all",
                        help_text="all: exportar todos los operarios del listado filtrado. selection: el usuario selecciona manualmente los operarios a incluir.",
                        max_length=20,
                        verbose_name="Alcance de operarios",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizada el"),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        help_text="Usuario propietario de esta plantilla. Cada usuario gestiona sus propias plantillas de forma independiente.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_templates",
                        to="ivr_config.companyuser",
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de exportación",
                "verbose_name_plural": "Plantillas de exportación",
                "ordering": ["company_user", "-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_user", "name"),
                        name="unique_export_template_name_per_user",
                    )
                ],
            },
        ),
    ]
