# Generated by Django 5.2.12 on 2026-06-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0032_add_section_is_broadcast_enabled"),
        ("work_order_processor", "0022_exporttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorMonthlyCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        max_length=200, verbose_name="nombre del operario"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="año")),
                ("month", models.PositiveSmallIntegerField(verbose_name="mes")),
                (
                    "monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="coste mensual (EUR)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_monthly_costs",
                        to="ivr_config.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coste mensual de operario",
                "verbose_name_plural": "Costes mensuales de operarios",
                "ordering": ["-year", "-month", "worker_name"],
                "unique_together": {("company", "worker_name", "year", "month")},
            },
        ),
    ]
