# Generated by Django 5.2.12 on 2026-06-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0033_companyuser_is_intensive_override"),
        ("work_order_processor", "0023_operator_monthly_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exporttemplate",
            options={
                "ordering": ["-is_global", "company_user", "-is_default", "name"],
                "verbose_name": "Plantilla de exportación",
                "verbose_name_plural": "Plantillas de exportación",
            },
        ),
        migrations.RemoveConstraint(
            model_name="exporttemplate",
            name="unique_export_template_name_per_user",
        ),
        migrations.AddField(
            model_name="exporttemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria de la plantilla global. Solo se usa cuando is_global=True. Null para plantillas personales.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_export_templates",
                to="ivr_config.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="exporttemplate",
            name="is_global",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Si True, esta plantilla pertenece a la empresa y es visible por todos los supervisores en modo lectura. Solo los ADMIN pueden crearla o editarla. Si un supervisor la edita, se crea automáticamente una copia personal.",
                verbose_name="Plantilla global",
            ),
        ),
        migrations.AlterField(
            model_name="exporttemplate",
            name="company_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario propietario de esta plantilla (plantillas personales). Null para plantillas globales de empresa.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="export_templates",
                to="ivr_config.companyuser",
                verbose_name="Usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="exporttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company_user__isnull", False)),
                fields=("company_user", "name"),
                name="unique_export_template_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="exporttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_global", True)),
                fields=("company", "name"),
                name="unique_export_template_name_per_company_global",
            ),
        ),
    ]
