# Generated by Django 5.2.12 on 2026-06-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_breakdownticket_conversation_log_and_more"),
        ("work_order_processor", "0024_alter_exporttemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentryline",
            name="breakdown_ticket",
            field=models.ForeignKey(
                blank=True,
                help_text="Ticket de avería al que corresponde este bloque de trabajo. Proporciona trazabilidad completa de horas invertidas por avería. Opcional — solo se informa cuando el bloque es una orden de reparación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_entry_lines",
                to="chat.breakdownticket",
                verbose_name="Ticket de avería",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="ticket_closed",
            field=models.BooleanField(
                default=False,
                help_text="Marcar para cerrar el ticket de avería vinculado al guardar este bloque. El sistema establece BreakdownTicket.status=CLOSED automáticamente. Solo aplica cuando breakdown_ticket está informado.",
                verbose_name="Ticket cerrado",
            ),
        ),
    ]
