# Generated by Django 5.2.12 on 2026-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0025_workorderentryline_breakdown_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentry",
            name="has_diet",
            field=models.BooleanField(
                default=False,
                help_text="Indica que el operario ha percibido dieta en esta jornada (trabajo fuera de la base habitual). Se informa a nivel de parte, no de tarea individual.",
                verbose_name="Dieta",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="is_on_site",
            field=models.BooleanField(
                default=False,
                help_text="Indica que el mecánico se desplazó al lugar donde se encontraba la máquina para realizar la reparación (fuera del taller).",
                verbose_name="Trabajo in situ",
            ),
        ),
    ]
