# Generated by Django 5.2.12 on 2026-06-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0001_initial"),
        ("work_order_processor", "0026_workorderentry_has_diet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepartline",
            name="spare_part_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Repuesto del almacén digital (app spare_parts) que originó esta línea al cerrar el parte de trabajo. Nulo para líneas históricas o introducidas manualmente sin pasar por el circuito de almacén del Hito 10.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resulting_spare_part_lines",
                to="spare_parts.sparepartentry",
                verbose_name="Entrada de Almacén Origen",
            ),
        ),
    ]
