# Generated by Django 5.2.12 on 2026-07-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_order_processor", "0027_sparepartline_spare_part_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderentryline",
            name="task_category_free",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Categorización libre generada por Gemini para bloques con tipo_tarea distinto de AVERIA (mejora, mantenimiento, fabricación...), sin taxonomía rígida. Vacío cuando tipo_tarea=AVERIA (se usa fault_category/fault_subcategory en su lugar) o cuando el bloque todavía no se ha clasificado.",
                max_length=200,
                verbose_name="Categoría de tarea (libre)",
            ),
        ),
        migrations.AddField(
            model_name="workorderentryline",
            name="tipo_tarea",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVERIA", "Avería"),
                    ("MEJORA", "Mejora"),
                    ("MANTENIMIENTO", "Mantenimiento"),
                    ("FABRICACION", "Fabricación"),
                ],
                db_index=True,
                default="",
                help_text="Naturaleza de este bloque de trabajo (avería, mejora, mantenimiento, fabricación). Poblado automáticamente por classify_fault_line junto con fault_category/fault_subcategory (solo si AVERIA) o task_category_free (el resto). No lo rellena el operario.",
                max_length=15,
                verbose_name="Tipo de tarea",
            ),
        ),
    ]
