# Generated by Django 5.2.12 on 2026-07-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0040_companyuser_can_view_budget_breakdown"),
        ("work_order_processor", "0028_workorderentryline_task_category_free_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatormonthlycost",
            options={
                "ordering": ["-work_period__start_date"],
                "verbose_name": "Coste de operario por periodo",
                "verbose_name_plural": "Costes de operarios por periodo",
            },
        ),
        migrations.AlterUniqueTogether(
            name="operatormonthlycost",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="operatormonthlycost",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Coste total del operario para este periodo: nómina completa más horas extraordinarias ya incluidas en un único importe.",
                max_digits=10,
                verbose_name="coste total del periodo (EUR)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operatormonthlycost",
            name="work_period",
            field=models.OneToOneField(
                default=1,
                help_text="Periodo de contrato/liquidación (ivr_config.WorkPeriod) al que corresponde este coste. Un único registro de coste por periodo -- la empresa y el operario se derivan de work_period.company_user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_cost",
                to="ivr_config.workperiod",
                verbose_name="periodo de trabajo",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="operatormonthlycost",
            name="company",
        ),
        migrations.RemoveField(
            model_name="operatormonthlycost",
            name="month",
        ),
        migrations.RemoveField(
            model_name="operatormonthlycost",
            name="monthly_cost",
        ),
        migrations.RemoveField(
            model_name="operatormonthlycost",
            name="worker_name",
        ),
        migrations.RemoveField(
            model_name="operatormonthlycost",
            name="year",
        ),
    ]
