# Generated by Django 5.2.12 on 2026-07-14 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_breakdownticket_task_category_free_and_more"),
        ("fleet", "0005_add_first_repair_to_machineasset"),
        ("ivr_config", "0040_companyuser_can_view_budget_breakdown"),
        ("work_order_processor", "0029_alter_operatormonthlycost_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Archivo original subido por el operario. Se sube a Google Drive tras la confirmación y se borra del servidor -- mismo criterio que spare_parts.DeliveryNote (S014-H10).",
                        upload_to="task_photos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción opcional de lo que muestra la foto.",
                        max_length=200,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="ID de archivo en Google Drive",
                    ),
                ),
                (
                    "drive_web_link",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Enlace de Google Drive",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "breakdown_ticket",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ticket de avería vinculado a la línea en el momento de creación de la foto (denormalizado desde line.breakdown_ticket). Nulo cuando la línea no tiene ticket vinculado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_photos",
                        to="chat.breakdownticket",
                        verbose_name="Ticket de avería",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece esta foto, denormalizada desde line.entry.work_order.company en el momento de creación.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_photos",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="Bloque de trabajo (tarea) al que pertenece esta foto. Un bloque puede tener cero o más fotos.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Bloque de trabajo",
                    ),
                ),
                (
                    "machine_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Máquina o centro de gasto vinculado a la línea en el momento de creación de la foto (denormalizado desde line.machine_asset).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_photos",
                        to="fleet.machineasset",
                        verbose_name="Máquina / Centro de gasto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario del panel que adjuntó esta foto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_photos_uploaded",
                        to="ivr_config.companyuser",
                        verbose_name="Subida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de tarea",
                "verbose_name_plural": "Fotos de tarea",
                "ordering": ["-created_at"],
            },
        ),
    ]
