# Generated by Django 5.2.12 on 2026-04-08 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre comercial de la empresa cliente.",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador URL único, generado automáticamente desde el nombre.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logotipo de la empresa en formato de imagen.",
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la empresa está operativa en la plataforma.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CallFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del flujo IVR (p. ej. Recepción principal Grupo Álvarez).",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "system_instruction",
                    models.TextField(
                        help_text="Instrucción completa de sistema para el agente Gemini Live. Define rol, reglas y comportamiento.",
                        verbose_name="Instrucción de sistema",
                    ),
                ),
                (
                    "initial_greeting",
                    models.TextField(
                        help_text="Texto del saludo inicial que el agente pronuncia al conectar la llamada.",
                        verbose_name="Saludo inicial",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este flujo IVR está disponible para su asignación a números.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este flujo IVR.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_flows",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flujo IVR",
                "verbose_name_plural": "Flujos IVR",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("OPERATOR", "Operador")],
                        default="OPERATOR",
                        help_text="ADMIN: acceso completo a la configuración de la empresa. OPERATOR: solo gestión de presencia propia.",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el usuario tiene acceso activo al panel.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este usuario.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_users",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario de autenticación Django vinculado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de empresa",
                "verbose_name_plural": "Usuarios de empresa",
                "ordering": ["company__name", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo del contacto.",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono en formato E.164 (p. ej. +34XXXXXXXXX).",
                        max_length=20,
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="True si el contacto es un empleado interno con acceso al panel.",
                        verbose_name="Interno",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este contacto.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario de empresa vinculado. Obligatorio si el contacto es interno.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_profile",
                        to="ivr_config.companyuser",
                        verbose_name="Usuario de empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CorporateVoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tone_guidelines",
                    models.TextField(
                        help_text="Descripción del tono y estilo de comunicación esperado del agente IVR.",
                        verbose_name="Directrices de tono",
                    ),
                ),
                (
                    "sample_responses",
                    models.JSONField(
                        default=list,
                        help_text="Lista de ejemplos de respuestas correctas para calibrar el tono del agente.",
                        verbose_name="Respuestas de ejemplo",
                    ),
                ),
                (
                    "forbidden_phrases",
                    models.JSONField(
                        default=list,
                        help_text="Lista de expresiones que el agente IVR debe evitar en todo momento.",
                        verbose_name="Frases prohibidas",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este perfil de voz está en uso.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa a la que pertenece este perfil de voz corporativa.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profile",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de voz corporativa",
                "verbose_name_plural": "Perfiles de voz corporativa",
            },
        ),
        migrations.CreateModel(
            name="DataCaptureSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del conjunto de captura de datos.",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text="Estructura JSON de campos a recopilar. PENDIENTE: definir con empresa piloto.",
                        verbose_name="Campos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este conjunto de captura de datos.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_capture_sets",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conjunto de captura de datos",
                "verbose_name_plural": "Conjuntos de captura de datos",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número de teléfono Twilio en formato E.164 (p. ej. +12603466780).",
                        max_length=20,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "friendly_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo del número para identificación interna.",
                        max_length=200,
                        verbose_name="Nombre amigable",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este número está operativo para recibir llamadas.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "call_flow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Flujo IVR que gestiona las llamadas entrantes a este número.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_numbers",
                        to="ivr_config.callflow",
                        verbose_name="Flujo IVR",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que está asignado este número Twilio.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Número de teléfono",
                "verbose_name_plural": "Números de teléfono",
                "ordering": ["company__name", "number"],
            },
        ),
        migrations.CreateModel(
            name="PresenceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("IN_MEETING", "Reunido"),
                            ("BUSY_UNTIL", "Ocupado hasta"),
                            ("ABSENT_SCHEDULED", "Ausente programado"),
                            ("ABSENT_VACATION", "Vacaciones"),
                        ],
                        default="AVAILABLE",
                        help_text="Estado de presencia actual del usuario.",
                        max_length=30,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de inicio del estado de presencia.",
                        verbose_name="Inicio",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de fin del estado. Null indica estado abierto sin fin definido.",
                        null=True,
                        verbose_name="Fin",
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se envió el recordatorio SMS/WhatsApp para IN_MEETING.",
                        null=True,
                        verbose_name="Recordatorio enviado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        help_text="Usuario de empresa al que pertenece este estado de presencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence_statuses",
                        to="ivr_config.companyuser",
                        verbose_name="Usuario de empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de presencia",
                "verbose_name_plural": "Estados de presencia",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la sección o departamento (p. ej. Elevación, Asistencia).",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del ámbito y función de esta sección.",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta sección está operativa para el enrutamiento IVR.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece esta sección.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Personas asociadas a esta sección a las que el IVR puede derivar llamadas.",
                        related_name="sections",
                        to="ivr_config.contact",
                        verbose_name="Contactos",
                    ),
                ),
                (
                    "data_capture_set",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conjunto de datos a recopilar para las llamadas de esta sección.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="ivr_config.datacaptureset",
                        verbose_name="Conjunto de captura de datos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["company__name", "name"],
            },
        ),
    ]
