# Generated by Django 5.2.12 on 2026-04-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="capabilities",
            field=models.CharField(
                choices=[
                    ("VOICE", "Solo voz (IVR)"),
                    ("WHATSAPP", "Solo WhatsApp"),
                    ("BOTH", "Voz + WhatsApp"),
                ],
                default="VOICE",
                help_text="Canal o canales de comunicación autorizados para este número: VOICE (solo IVR de voz), WHATSAPP (solo mensajería WhatsApp) o BOTH (voz e IVR + WhatsApp simultáneamente).",
                max_length=10,
                verbose_name="Capacidades",
            ),
        ),
    ]
