# Generated by Django 5.2.12 on 2026-04-13 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0002_phonenumber_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callflow",
            name="notification_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Contacto designado para recibir la notificación (llamada saliente + correo) cuando una llamada no encaja en ninguna sección conocida del flujo IVR. Si está vacío, las llamadas de actividad no recogida no generan notificación.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_flows",
                to="ivr_config.contact",
                verbose_name="Contacto de notificación",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Dirección de correo electrónico para notificaciones de llamada al responsable.",
                max_length=254,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Sr."), ("F", "Sra.")],
                help_text="Género del contacto para tratamiento verbal por María (Sr./Sra.). Si está vacío, María usará el nombre sin tratamiento.",
                max_length=1,
                verbose_name="Género",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="is_24h",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, la sección se considera siempre disponible independientemente del horario definido en SectionSchedule. Usar para servicios de guardia permanente (p. ej. Asistencia en carretera).",
                verbose_name="Disponible 24 horas",
            ),
        ),
        migrations.CreateModel(
            name="SectionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="Día de la semana al que aplica esta franja horaria (0=Lunes, 6=Domingo).",
                        verbose_name="Día de la semana",
                    ),
                ),
                (
                    "time_open",
                    models.TimeField(
                        help_text="Hora de inicio de la franja de disponibilidad (formato HH:MM).",
                        verbose_name="Hora de apertura",
                    ),
                ),
                (
                    "time_close",
                    models.TimeField(
                        help_text="Hora de fin de la franja de disponibilidad (formato HH:MM).",
                        verbose_name="Hora de cierre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Sección a la que pertenece esta franja horaria.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="ivr_config.section",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de sección",
                "verbose_name_plural": "Horarios de sección",
                "ordering": [
                    "section__company__name",
                    "section__name",
                    "weekday",
                    "time_open",
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockedCaller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono bloqueado en formato E.164 (p. ej. +34XXXXXXXXX).",
                        max_length=20,
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del motivo del bloqueo para registro interno.",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de bloqueo"
                    ),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del bloqueo. Por defecto: 24 horas desde el bloqueo.",
                        verbose_name="Bloqueado hasta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario administrador que aplicó el bloqueo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_callers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bloqueado por",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa para la que se aplica este bloqueo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_callers",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llamante bloqueado",
                "verbose_name_plural": "Llamantes bloqueados",
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "phone_number"],
                        name="ivr_blocked_company_phone_idx",
                    )
                ],
            },
        ),
    ]
