# Generated by Django 5.2.12 on 2026-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0003_callflow_notification_contact_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="must_change_password",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo, el usuario será redirigido obligatoriamente a la pantalla de cambio de contraseña al iniciar sesión. Se activa automáticamente al crear el usuario o cuando el ADMIN fuerza un reset.",
                verbose_name="Debe cambiar contraseña",
            ),
        ),
    ]
