# Generated by Django 5.2.12 on 2026-04-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0004_companyuser_add_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporatevoiceprofile",
            name="voice_name",
            field=models.CharField(
                choices=[
                    ("Aoede", "Aoede — Femenina, cálida (por defecto)"),
                    ("Puck", "Puck — Masculina, juvenil y conversacional"),
                    ("Charon", "Charon — Masculina, profunda y autoritaria"),
                    ("Kore", "Kore — Femenina, clara y profesional"),
                    ("Fenrir", "Fenrir — Masculina, cercana y accesible"),
                    ("Leda", "Leda — Femenina, suave"),
                    ("Orus", "Orus — Masculina, neutra"),
                    ("Zephyr", "Zephyr — Femenina, enérgica"),
                ],
                default="Aoede",
                help_text="Voz Gemini Live que el agente IVR usará en las llamadas entrantes. Voces disponibles para gemini-live-2.5-flash-native-audio en Vertex AI. El cambio tiene efecto en la siguiente llamada sin necesidad de reiniciar.",
                max_length=50,
                verbose_name="Voz del agente",
            ),
        ),
    ]
