# Generated by Django 5.2.12 on 2026-04-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0005_corporatevoiceprofile_add_voice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="callflow",
            name="backup_initial_greeting",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Copia anterior de initial_greeting para restauración de un clic.",
                verbose_name="Backup saludo inicial",
            ),
        ),
        migrations.AddField(
            model_name="callflow",
            name="backup_notification_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Copia anterior de notification_contact para restauración de un clic.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_notification_flows",
                to="ivr_config.contact",
                verbose_name="Backup contacto de notificación",
            ),
        ),
        migrations.AddField(
            model_name="callflow",
            name="backup_system_instruction",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Copia anterior de system_instruction para restauración de un clic.",
                verbose_name="Backup instrucción de sistema",
            ),
        ),
        migrations.AddField(
            model_name="corporatevoiceprofile",
            name="backup_forbidden_phrases",
            field=models.JSONField(
                default=list,
                help_text="Copia anterior de forbidden_phrases para restauración de un clic.",
                verbose_name="Backup frases prohibidas",
            ),
        ),
        migrations.AddField(
            model_name="corporatevoiceprofile",
            name="backup_sample_responses",
            field=models.JSONField(
                default=list,
                help_text="Copia anterior de sample_responses para restauración de un clic.",
                verbose_name="Backup respuestas de ejemplo",
            ),
        ),
        migrations.AddField(
            model_name="corporatevoiceprofile",
            name="backup_tone_guidelines",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Copia anterior de tone_guidelines para restauración de un clic.",
                verbose_name="Backup directrices de tono",
            ),
        ),
        migrations.AddField(
            model_name="corporatevoiceprofile",
            name="backup_voice_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Copia anterior de voice_name para restauración de un clic.",
                max_length=50,
                verbose_name="Backup voz del agente",
            ),
        ),
    ]
