# Generated by Django 5.2.12 on 2026-04-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0006_callflow_voiceprofile_add_backup_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="callflow",
            name="fallback_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Sección de último recurso para este flujo IVR. Cuando ninguna sección activa puede atender al llamante, el agente transfiere la llamada al responsable humano de esta sección. Cada número puede tener su propia sección de fallback independiente según las necesidades de la empresa.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fallback_for_call_flows",
                to="ivr_config.section",
                verbose_name="Sección de fallback",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="call_flow",
            field=models.ForeignKey(
                blank=True,
                help_text="Flujo IVR específico de esta sección. Cuando el agente identifica que el llamante desea ser atendido por esta sección, carga este CallFlow para continuar la conversación con el contexto específico de la sección. Las secciones sin CallFlow asignado son ignoradas por el motor en tiempo de llamada (Estrategia B — carga dinámica por intención).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="ivr_config.callflow",
                verbose_name="Flujo IVR de sección",
            ),
        ),
    ]
