# Generated by Django 5.2.12 on 2026-04-20 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0008_sectioncontact_transferattempt_pendingnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingnotification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp"),
                    ("SMS", "SMS"),
                    ("EMAIL", "Correo electrónico"),
                    ("PENDING", "Pendiente"),
                ],
                default="PENDING",
                help_text="Canal por el que se enviará la notificación al responsable. PENDING: aún no procesado por Celery. El worker de Hito 4 actualizará este campo al enviar la notificación real.",
                max_length=20,
                verbose_name="Canal de notificación",
            ),
        ),
        migrations.AlterField(
            model_name="pendingnotification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sectioncontact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sectioncontact",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Orden de intento de transferencia. Menor número = mayor prioridad. El motor intentará contactar primero al registro con priority=0, luego al siguiente, hasta agotar todos los contactos de la sección.",
                verbose_name="Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="transferattempt",
            name="contact_index",
            field=models.IntegerField(
                default=0,
                help_text="Índice (base 0) del contacto de sección que se está intentando en este momento, ordenado por SectionContact.priority ASC. El webhook TransferStatusView incrementa este valor en cada intento fallido para avanzar al siguiente contacto.",
                verbose_name="Índice de contacto",
            ),
        ),
        migrations.AlterField(
            model_name="transferattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="CallDataCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador unico del tramo de llamada Twilio (CA...). No es unique: una misma llamada puede generar multiples capturas si el flujo IVR atraviesa mas de una seccion con DataCaptureSet.",
                        max_length=40,
                        verbose_name="Call SID",
                    ),
                ),
                (
                    "captured_data",
                    models.JSONField(
                        default=dict,
                        help_text="Diccionario clave->valor con los datos recopilados por el DataCaptureSet activo. Estructura: {nombre_campo: valor_capturado}. Ejemplo: {nombre: Juan Garcia, telefono: +34600000000, motivo: Averia grua}.",
                        verbose_name="Datos capturados",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp UTC en que se completo el ciclo de captura.",
                        verbose_name="Fecha de captura",
                    ),
                ),
                (
                    "notified_via_whatsapp",
                    models.BooleanField(
                        default=False,
                        help_text="True si la notificacion WhatsApp al contacto referente fue enviada y confirmada por la API de Twilio. False hasta entonces.",
                        verbose_name="Notificado via WhatsApp",
                    ),
                ),
                (
                    "whatsapp_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp UTC en que la notificacion WhatsApp fue confirmada como enviada.",
                        null=True,
                        verbose_name="Fecha de envio WhatsApp",
                    ),
                ),
                (
                    "call_flow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Flujo IVR activo en el momento de la captura.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_data_captures",
                        to="ivr_config.callflow",
                        verbose_name="Flujo IVR",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot del contacto referente de la seccion en el momento de la captura. Se almacena como FK para trazabilidad historica; el contacto puede cambiar posteriormente sin afectar al registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_data_captures",
                        to="ivr_config.contact",
                        verbose_name="Contacto referente",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seccion en la que se produjo la captura de datos.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_data_captures",
                        to="ivr_config.section",
                        verbose_name="Seccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Captura de datos de llamada",
                "verbose_name_plural": "Capturas de datos de llamada",
                "ordering": ["-captured_at"],
            },
        ),
    ]
