# Generated by Django 5.2.12 on 2026-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0009_add_call_data_capture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacaptureset",
            name="fields",
            field=models.JSONField(
                default=list,
                help_text="Lista de objetos JSON con estructura [{key, label, type, required}]. Tipos soportados: text, phone, location, reference, date, free_text.",
                verbose_name="Campos",
            ),
        ),
    ]
