# Generated by Django 5.2.12 on 2026-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0010_alter_datacaptureset_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="fleet_families",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de familias del catálogo MachineAsset a incluir en el contexto IVR de esta sección. Ejemplo: ["PLATAFOR"] para Elevación, ["MOVILES", "AUTOCARG"] para Grúas. Los activos de estas familias se inyectan automáticamente en el system_instruction del CallFlow de sección al generarse o regenerarse.',
                verbose_name="Familias de flota",
            ),
        ),
    ]
