# Generated by Django 5.2.12 on 2026-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0011_section_fleet_families"),
    ]

    operations = [
        migrations.AddField(
            model_name="callflow",
            name="backup_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Copia anterior del nombre del flujo IVR para restauración de un clic.",
                max_length=200,
                verbose_name="Backup nombre",
            ),
        ),
    ]
