# Generated by Django 5.2.12 on 2026-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0012_callflow_backup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("OPERATOR", "Operador"),
                    ("WORKSHOP", "Operario de taller"),
                    ("SUPERVISOR", "Supervisor"),
                    ("DRIVER", "Chófer"),
                ],
                default="OPERATOR",
                help_text="ADMIN: acceso completo a la configuración. OPERATOR: gestión de presencia. WORKSHOP: partes de taller. SUPERVISOR: revisión y exportación de partes PDF. DRIVER: reservado.",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
