# Generated by Django 5.2.12 on 2026-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0013_alter_companyuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="dni",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Documento Nacional de Identidad o NIF del usuario de empresa. Se usa para identificar al operario en el registro de signup. Debe ser único por empresa cuando se informe.",
                max_length=20,
                verbose_name="DNI / NIF",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de teléfono de contacto del usuario de empresa. Formato libre (p. ej. +34XXXXXXXXX). Opcional.",
                max_length=20,
                verbose_name="Teléfono",
            ),
        ),
    ]
