# Generated by Django 5.2.12 on 2026-05-08 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0014_companyuser_dni_companyuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("VACATION", "Vacaciones anuales"),
                            ("SICK_LEAVE", "Baja médica (IT enfermedad común)"),
                            ("WORK_ACCIDENT", "Accidente laboral (IT profesional)"),
                            ("MATERNITY_PATERNITY", "Maternidad / Paternidad"),
                            ("BEREAVEMENT", "Defunción de familiar"),
                            ("PERSONAL", "Asuntos propios"),
                            ("OTHER", "Otros"),
                        ],
                        help_text="Categoría de la ausencia según los tipos definidos por la plataforma.",
                        max_length=30,
                        verbose_name="Tipo de ausencia",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Primer día de la ausencia (inclusive).",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Último día de la ausencia (inclusive).",
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones adicionales sobre la ausencia. Campo libre, opcional.",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        help_text="Operario de taller al que pertenece este registro de ausencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="ivr_config.companyuser",
                        verbose_name="Operario",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor o ADMIN que registró esta ausencia. Se establece automáticamente desde el usuario autenticado en el momento del alta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_absences",
                        to="ivr_config.companyuser",
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausencia de operario",
                "verbose_name_plural": "Ausencias de operario",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Primer día del periodo de trabajo (inclusive).",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Último día del periodo de trabajo (inclusive). Null indica periodo abierto — el operario está activo en este periodo.",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre descriptivo opcional del periodo (p. ej. 'Mayo 2026', 'Verano 2026'). Se muestra en el historial de partes del operario como cabecera de grupo.",
                        max_length=100,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        help_text="Operario de taller al que pertenece este periodo de trabajo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_periods",
                        to="ivr_config.companyuser",
                        verbose_name="Operario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor o ADMIN que creó este periodo. Se establece automáticamente desde el usuario autenticado en el momento del alta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_periods",
                        to="ivr_config.companyuser",
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de trabajo",
                "verbose_name_plural": "Periodos de trabajo",
                "ordering": ["-start_date"],
            },
        ),
    ]
