# Generated by Django 5.2.12 on 2026-05-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0015_workerabsence_workperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkdaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Hora de inicio ordinaria de la jornada laboral. Los partes cuyo primer bloque comience después de esta hora más el margen de tolerancia generarán un aviso de inicio tardío.",
                        verbose_name="Hora de entrada",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Hora de fin ordinaria de la jornada laboral. Los partes cuyo último bloque termine antes de esta hora menos el margen de tolerancia generarán un aviso de cierre anticipado.",
                        verbose_name="Hora de salida",
                    ),
                ),
                (
                    "tolerance_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Margen de tolerancia en minutos aplicado tanto al inicio como al fin de la jornada antes de registrar un aviso. Por defecto: 15 min.",
                        verbose_name="Tolerancia (minutos)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Empresa a la que pertenece este horario de jornada de referencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workday_schedule",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de jornada",
                "verbose_name_plural": "Horarios de jornada",
            },
        ),
        migrations.CreateModel(
            name="AbsenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador interno de la categoría (p. ej. MEDICAL, DAY_OFF). Único por empresa. Usado por el seed y la lógica de Gate 4.",
                        max_length=40,
                        verbose_name="Código",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Texto visible para el operario en el selector de justificación de lagunas de jornada (WorkdayGapResolutionView).",
                        max_length=100,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "requires_note",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el operario debe rellenar el campo de notas para poder guardar la justificación de la laguna.",
                        verbose_name="Requiere nota",
                    ),
                ),
                (
                    "is_justified",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta categoría de ausencia se considera justificada a efectos de informes de incidencias de jornada.",
                        verbose_name="Justificada",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactivar en lugar de eliminar para preservar referencias históricas en WorkdayGap ya registrados.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posición de esta categoría en el selector del operario. Menor número = aparece antes. Las categorías con el mismo orden se ordenan alfabéticamente por etiqueta.",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece esta categoría de ausencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_categories",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de ausencia",
                "verbose_name_plural": "Categorías de ausencia",
                "ordering": ["company__name", "order", "label"],
                "unique_together": {("company", "code")},
            },
        ),
    ]
