# Generated by Django 5.2.12 on 2026-05-14 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0016_workdayschedule_absencecategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workdayschedule",
            options={
                "ordering": ["company__name", "label"],
                "verbose_name": "Horario de jornada",
                "verbose_name_plural": "Horarios de jornada",
            },
        ),
        migrations.AddField(
            model_name="companyuser",
            name="workday_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Horario de jornada asignado a este operario por el supervisor. Gate 4 usa este horario con prioridad máxima. Si no está asignado, Gate 4 aplica el horario por defecto de la empresa. Si tampoco existe horario por defecto, Gate 4 se omite completamente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_users",
                to="ivr_config.workdayschedule",
                verbose_name="Horario de jornada",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, este horario se aplica como fallback a los operarios que no tienen un horario específicamente asignado. Solo puede haber un horario por defecto por empresa — activarlo aquí desactiva automáticamente el anterior horario por defecto.",
                verbose_name="Horario por defecto",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="label",
            field=models.CharField(
                default="",
                help_text="Nombre descriptivo del perfil de turno (p. ej. 'Mecánicos', 'Chóferes de grúa', 'Administración'). Visible en el panel del supervisor al asignar horarios a operarios.",
                max_length=100,
                verbose_name="Nombre del horario",
            ),
        ),
        migrations.AlterField(
            model_name="workdayschedule",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa a la que pertenece este horario de jornada.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workday_schedules",
                to="ivr_config.company",
                verbose_name="Empresa",
            ),
        ),
    ]
