# Generated by Django 5.2.12 on 2026-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0017_workdayschedule_refactor_multiprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workdayschedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="workdayschedule",
            name="start_time",
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="end_time_afternoon",
            field=models.TimeField(
                blank=True,
                help_text="Hora de fin del tramo de tarde y de la jornada completa. Dejar en blanco para jornada intensiva (is_intensive=True).",
                null=True,
                verbose_name="Salida tarde",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="end_time_morning",
            field=models.TimeField(
                default="15:00",
                help_text="Hora de fin del tramo de mañana. En jornada intensiva (is_intensive=True) es también la hora de salida final de la jornada completa.",
                verbose_name="Salida mañana",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="is_intensive",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, este horario corresponde a jornada intensiva: Gate 4 solo valida el tramo de mañana y los campos de tarde quedan ignorados. Típico en temporada de verano.",
                verbose_name="Jornada intensiva",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="season",
            field=models.CharField(
                choices=[("WINTER", "Invierno"), ("SUMMER", "Verano")],
                default="WINTER",
                help_text="Temporada a la que aplica este horario. INVIERNO: turno partido con tramo de mañana y tarde. VERANO: jornada intensiva (solo mañana si is_intensive=True).",
                max_length=10,
                verbose_name="Temporada",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="start_time_afternoon",
            field=models.TimeField(
                blank=True,
                help_text="Hora de inicio del tramo de tarde. Dejar en blanco para jornada intensiva (is_intensive=True). La ventana entre la salida de mañana y esta hora se trata como pausa de mediodía y no genera aviso de laguna en Gate 4.",
                null=True,
                verbose_name="Entrada tarde",
            ),
        ),
        migrations.AddField(
            model_name="workdayschedule",
            name="start_time_morning",
            field=models.TimeField(
                default="07:00",
                help_text="Hora de inicio del tramo de mañana. Los partes cuyo primer bloque comience después de esta hora más el margen de tolerancia generarán un aviso de inicio tardío.",
                verbose_name="Entrada mañana",
            ),
        ),
        migrations.AlterField(
            model_name="workdayschedule",
            name="tolerance_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Margen de tolerancia en minutos aplicado tanto al inicio como al fin de cada tramo antes de registrar un aviso. Por defecto: 15 min.",
                verbose_name="Tolerancia (minutos)",
            ),
        ),
    ]
