# Generated by Django 5.2.12 on 2026-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0018_workdayschedule_season_split_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Apodo del contacto en el chat IRC de grupo. Se recoge la primera vez que el contacto escribe en su sala SECTION via WhatsApp. Hasta que no está configurado, los mensajes del contacto no se reenvían al grupo — el chatbot le solicita que elija su alias. Los contactos sin sección asignada (clientes) no tienen alias y nunca se les solicita. Para contactos internos (is_internal=True), este alias es compartido con su CompanyUser vinculado — no existe campo alias en CompanyUser.",
                max_length=50,
                verbose_name="Alias de chat",
            ),
        ),
    ]
