# Generated by Django 5.2.12 on 2026-05-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0019_contact_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Apodo del usuario en el chat IRC de grupo. Fuente de verdad única para los mensajes enviados desde el panel. Se solicita mediante modal al acceder a una sala de chat por primera vez sin alias configurado. Los contactos externos (sin CompanyUser) usan Contact.alias para los mensajes recibidos por WhatsApp.",
                max_length=50,
                verbose_name="Alias de chat",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Apodo del contacto externo en el chat IRC de grupo. Se recoge la primera vez que el contacto escribe en su sala SECTION via WhatsApp. Hasta que no está configurado, sus mensajes no se reenvían al grupo — el chatbot le solicita que elija su alias. Los contactos sin sección asignada (clientes) no tienen alias y nunca se les solicita. Para contactos internos (is_internal=True) vinculados a un CompanyUser, el alias canónico es CompanyUser.alias — este campo queda en desuso para contactos internos.",
                max_length=50,
                verbose_name="Alias de chat",
            ),
        ),
    ]
