# Generated by Django 5.2.12 on 2026-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0020_companyuser_alias_alter_contact_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="default_role",
            field=models.CharField(
                choices=[("WORKSHOP", "Operario de taller"), ("DRIVER", "Chófer")],
                default="WORKSHOP",
                help_text="Rol asignado automáticamente a los contactos de esta sección cuando se registran en la plataforma vía onboarding WhatsApp. WORKSHOP: operario de taller. DRIVER: chófer. Los roles de mayor rango (ADMIN, SUPERVISOR, OPERATOR) se asignan manualmente desde la consola de administración.",
                max_length=20,
                verbose_name="Rol por defecto",
            ),
        ),
    ]
