# Generated by Django 5.2.12 on 2026-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0021_section_default_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="alias_onboarding_proposed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alias propuesto por el contacto durante el diálogo de onboarding. Se guarda en el Paso B y se confirma o descarta en el Paso C.",
                max_length=50,
                verbose_name="Alias propuesto en onboarding",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="alias_onboarding_step",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin estado"),
                    ("PENDING", "Esperando nombre"),
                    ("CONFIRMING", "Esperando confirmación"),
                ],
                default="NONE",
                help_text="Estado actual del diálogo de recogida de alias vía WhatsApp. NONE: sin diálogo activo. PENDING: se ha pedido el nombre, esperando respuesta. CONFIRMING: se ha recibido un alias propuesto, esperando confirmación SÍ/NO.",
                max_length=12,
                verbose_name="Paso de onboarding de alias",
            ),
        ),
    ]
