# Generated by Django 5.2.12 on 2026-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0022_contact_alias_onboarding_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="opt_out_broadcast",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el contacto ha optado por no recibir mensajes de broadcast del grupo de su sección. Se activa cuando el contacto pulsa 'No, gracias' en el template chat_session_renewal. Los contactos con este flag activo se excluyen del bucle de broadcast en ChatSendView.",
                verbose_name="Baja del broadcast",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="pending_routing_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Cuerpo del mensaje original recibido del contacto mientras se espera su selección de sala en el diálogo de enrutamiento dinámico. Se guarda cuando routing_state pasa a AWAITING_ROUTE y se descarta tras procesar la respuesta del contacto.",
                verbose_name="Mensaje pendiente de enrutamiento",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="routing_state",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin enrutamiento pendiente"),
                    ("AWAITING_ROUTE", "Esperando selección de sala"),
                ],
                default="NONE",
                help_text="Estado del diálogo de enrutamiento dinámico para contactos con sección y acceso a la sala BREAKDOWNS. NONE: sin diálogo activo. AWAITING_ROUTE: se ha enviado el Quick Reply de selección de sala y se espera la respuesta del contacto.",
                max_length=20,
                verbose_name="Estado de enrutamiento",
            ),
        ),
    ]
