# Generated by Django 5.2.12 on 2026-05-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0023_contact_opt_out_broadcast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="workday_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Horario de jornada que se aplica por defecto a todos los trabajadores de esta sección. Un trabajador con horario individual asignado (CompanyUser.workday_schedule) tiene prioridad sobre este valor. Si no hay horario de sección ni individual, Gate 4 usa el horario por defecto de empresa (WorkdaySchedule.is_default=True).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="ivr_config.workdayschedule",
                verbose_name="Horario de trabajo por defecto",
            ),
        ),
    ]
