# Generated by Django 5.2.12 on 2026-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0025_workshopboss_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="trusted_device_token",
            field=models.UUIDField(
                blank=True,
                default=None,
                help_text="UUID generado automáticamente cuando el usuario establece su contraseña por primera vez. Se almacena en una cookie HttpOnly firmada en el navegador del usuario para permitir el acceso sin formulario de login desde ese dispositivo. Anularlo fuerza al usuario a autenticarse de nuevo con contraseña.",
                null=True,
                verbose_name="Token de dispositivo de confianza",
            ),
        ),
    ]
