# Generated by Django 5.2.12 on 2026-05-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0026_add_trusted_device_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="workshop_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MECHANICAL", "Taller Mecánico"),
                    ("ELEVATION", "Taller Elevación"),
                ],
                help_text="Solo aplica para el rol WORKSHOPBOSS. Determina qué familia de centros de gasto gestiona este jefe de taller y qué tickets de avería le son visibles y asignables. MECHANICAL: camiones, grúas y maquinaria pesada. ELEVATION: carretillas y plataformas elevadoras.",
                max_length=20,
                null=True,
                verbose_name="Familia de taller",
            ),
        ),
        migrations.CreateModel(
            name="WorkshopFamilyMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalogue_family",
                    models.CharField(
                        help_text="Valor exacto del campo MachineAsset.family tal como figura en el catálogo importado (p.ej. PLATAFOR, CARR, MOVILES, AUTOCARG). La comparación es sensible a mayúsculas/minúsculas.",
                        max_length=100,
                        verbose_name="Familia de catálogo",
                    ),
                ),
                (
                    "workshop_family",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "Taller Mecánico"),
                            ("ELEVATION", "Taller Elevación"),
                        ],
                        help_text="Grupo de taller al que se enruta el ticket de avería cuando la máquina afectada pertenece a esta familia de catálogo. MECHANICAL: Taller Mecánico. ELEVATION: Taller Elevación.",
                        max_length=20,
                        verbose_name="Familia de taller destino",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción opcional del tipo de maquinaria incluida en esta familia (p.ej. 'Plataformas tijera eléctricas y articuladas').",
                        max_length=200,
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este mapeo de familia de taller.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_family_mappings",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeo de familia de taller",
                "verbose_name_plural": "Mapeos de familia de taller",
                "ordering": ["company__name", "catalogue_family"],
                "unique_together": {("company", "catalogue_family")},
            },
        ),
    ]
