# Generated by Django 5.2.12 on 2026-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0027_companyuser_workshop_family_workshopfamilymapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="routing_state",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin flujo activo"),
                    ("AWAITING_BREAKDOWN_CONFIRM", "Esperando confirmacion de averia"),
                    ("BREAKDOWN_IN_PROGRESS", "Recogida de averia en curso"),
                ],
                default="NONE",
                help_text="Estado del flujo de averia del contacto. NONE: sin flujo activo. AWAITING_BREAKDOWN_CONFIRM: se ha enviado el Quick Reply Si/No. BREAKDOWN_IN_PROGRESS: el agente Gemini esta recogiendo los datos.",
                max_length=30,
                verbose_name="Estado de enrutamiento",
            ),
        ),
    ]
