# Generated by Django 5.2.12 on 2026-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0028_routing_state_breakdown_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("OPERATOR", "Operador"),
                    ("WORKSHOP", "Operario de taller"),
                    ("WORKSHOPBOSS", "Jefe de taller"),
                    ("SUPERVISOR", "Supervisor"),
                    ("DRIVER", "Chófer"),
                    ("ASSISTANCE", "Operario de Asistencia"),
                ],
                default="OPERATOR",
                help_text="ADMIN: acceso completo a la configuración. OPERATOR: gestión de presencia. WORKSHOP: partes de taller. WORKSHOPBOSS: jefe de taller — tickets de avería, sala BREAKDOWNS y sección propia, más acceso equivalente a SUPERVISOR en Taller, Administración y jornada. SUPERVISOR: revisión y exportación de partes PDF. DRIVER: reservado. ASSISTANCE: operario de Asistencia — solo modulo de presupuestos.",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
