# Generated by Django 5.2.12 on 2026-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0029_alter_companyuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="labor_calendar",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Festivos locales, nacionales y horario nocturno de referencia. Alimenta el motor de cálculo de presupuestos para aplicar correctamente los recargos nocturnos y festivos según el calendario real.",
                verbose_name="Calendario laboral",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="operation_bases",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Localidades o zonas desde donde opera la empresa. Alimenta el motor de cálculo de presupuestos para determinar el punto de origen del servicio.",
                verbose_name="Bases de operación",
            ),
        ),
    ]
