# Generated by Django 5.2.12 on 2026-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0030_company_labor_calendar_company_operation_bases"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="night_end",
            field=models.TimeField(
                default="06:00",
                help_text="Hora de fin de la franja nocturna para el módulo de presupuestos ASISTENCIA. Los servicios antes de esta hora se marcan automáticamente como nocturnos/festivos. Por defecto: 06:00.",
                verbose_name="Fin franja nocturna",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="night_start",
            field=models.TimeField(
                default="22:00",
                help_text="Hora de inicio de la franja nocturna para el módulo de presupuestos ASISTENCIA. Los servicios a esta hora o después se marcan automáticamente como nocturnos/festivos. Por defecto: 22:00.",
                verbose_name="Inicio franja nocturna",
            ),
        ),
    ]
