# Generated by Django 5.2.12 on 2026-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0031_add_night_start_end_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_broadcast_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indica si esta sección puede recibir circulares masivas de WhatsApp. Solo las secciones habilitadas aparecen en el selector del bot.",
                verbose_name="Habilitada para circulares WhatsApp",
            ),
        ),
    ]
