# Generated by Django 5.2.12 on 2026-06-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0032_add_section_is_broadcast_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="is_intensive_override",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este operario está en jornada intensiva (verano). El operario puede activarlo o desactivarlo desde el formulario de parte. El supervisor o administrador puede cambiarlo desde el panel de gestión de usuarios. Cuando está activo, Gate 4 resuelve el WorkdaySchedule con is_intensive=True de la empresa en lugar del horario partido (invierno). El estado persiste entre sesiones hasta que se modifique explícitamente.",
                verbose_name="Jornada intensiva activa",
            ),
        ),
    ]
