# Generated by Django 5.2.12 on 2026-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0033_companyuser_is_intensive_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="ivr_breakdown_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, cuando Gemini detecta que el llamante reporta una avería interna de flota, la conversación sigue el flujo de captura de datos para crear un BreakdownTicket vinculado a esta sección. No implica transferencia de llamada — el ticket se crea en BD y se notifica al taller por WhatsApp. Activar solo en secciones de taller.",
                verbose_name="Avería interna IVR habilitada",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="ivr_transfer_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo, esta sección aparece en el section_callflow_map y María puede transferir llamadas a sus contactos. Desactivar para secciones que gestionan averías internas o que no deben recibir transferencias de voz (p. ej. Taller Mecánico).",
                verbose_name="Transferencia IVR habilitada",
            ),
        ),
    ]
