# Generated by Django 5.2.12 on 2026-06-19 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_breakdownticket_is_repair_order_and_more"),
        ("ivr_config", "0034_section_ivr_breakdown_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador único de llamada Twilio (CA...).",
                        max_length=50,
                        verbose_name="Call SID",
                    ),
                ),
                (
                    "twilio_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número E.164 de Twilio que recibió la llamada.",
                        max_length=20,
                        verbose_name="Número Twilio",
                    ),
                ),
                (
                    "caller_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número E.164 del llamante capturado por Twilio (CLI). Puede no coincidir con el número real del chófer si llamó desde un teléfono ajeno.",
                        max_length=20,
                        verbose_name="Número llamante (CLI)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="Momento en que Twilio conectó la llamada al bridge.",
                        verbose_name="Inicio de llamada",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que la sesión Gemini Live finalizó.",
                        null=True,
                        verbose_name="Fin de llamada",
                    ),
                ),
                (
                    "caller_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre y apellidos inferidos por Gemini durante la conversación.",
                        max_length=200,
                        verbose_name="Nombre del llamante",
                    ),
                ),
                (
                    "caller_phone_reported",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de teléfono que el llamante indicó verbalmente, si difiere del CLI o si llamó desde un teléfono ajeno.",
                        max_length=20,
                        verbose_name="Teléfono facilitado por el llamante",
                    ),
                ),
                (
                    "call_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resumen breve del motivo inferido por Gemini.",
                        max_length=500,
                        verbose_name="Motivo de la llamada",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("BREAKDOWN", "Avería interna"),
                            ("TRANSFER", "Transferencia"),
                            ("INFO", "Información"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        help_text="Clasificación del tipo de llamada inferida por Gemini.",
                        max_length=20,
                        verbose_name="Tipo de llamada",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("TICKET_CREATED", "Ticket creado"),
                            ("TRANSFERRED", "Transferido"),
                            ("INFO_GIVEN", "Información facilitada"),
                            ("ABANDONED", "Llamada abandonada"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        help_text="Resultado final de la llamada.",
                        max_length=20,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "raw_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Resumen libre generado por Gemini al final de la conversación. Incluye todos los datos capturados y el resultado de la llamada.",
                        verbose_name="Resumen de la conversación",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "breakdown_ticket",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ticket de avería creado durante esta llamada, si aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_call_logs",
                        to="chat.breakdownticket",
                        verbose_name="Ticket de avería",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa que recibió la llamada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_call_logs",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sección identificada por Gemini como destino de la llamada.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_call_logs",
                        to="ivr_config.section",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de llamada entrante",
                "verbose_name_plural": "Registros de llamadas entrantes",
                "ordering": ["-started_at"],
            },
        ),
    ]
