# Generated by Django 5.2.12 on 2026-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0035_inboundcalllog"),
    ]

    operations = [
        migrations.AddField(
            model_name="workperiod",
            name="is_closed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indica que el periodo ha sido liquidado administrativamente. Cuando está activo, ningún parte dentro del rango puede editarse. Se activa manualmente por el ADMIN o SUPERVISOR al cerrar el periodo.",
                verbose_name="Liquidado",
            ),
        ),
        migrations.AlterField(
            model_name="workperiod",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Último día del periodo de trabajo (inclusive). Puede establecerse al crear el periodo sin que implique cierre.",
                null=True,
                verbose_name="Fecha de fin",
            ),
        ),
    ]
