# Generated by Django 5.2.12 on 2026-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0036_workperiod_is_closed_alter_workperiod_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre de pila del contacto. Si está relleno, se usa en saludos de voz (Alia IVR) en lugar del nombre completo.",
                max_length=100,
                verbose_name="Nombre de pila",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Apellidos del contacto.",
                max_length=200,
                verbose_name="Apellidos",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(
                help_text="Nombre completo del contacto (legacy — usar first_name/last_name).",
                max_length=200,
                verbose_name="Nombre",
            ),
        ),
    ]
