# Generated by Django 5.2.12 on 2026-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0037_contact_first_name_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="toll_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de recargo aplicado sobre el coste de peaje calculado. Se aplica a todos los presupuestos hasta que se cambie manualmente desde el panel de peajes. Ej: 10 = 10% de recargo.",
                max_digits=5,
                verbose_name="Recargo de peaje al cliente (%)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="toll_vehicle_type",
            field=models.CharField(
                choices=[
                    ("LIGHT", "Ligero"),
                    ("HEAVY_1", "Pesado 1"),
                    ("HEAVY_2", "Pesado 2"),
                ],
                default="HEAVY_1",
                help_text="Categoría de vehículo usada para calcular el coste de peaje en el motor de presupuestos ASISTENCIA. Se aplica a todos los presupuestos hasta que se cambie manualmente desde el panel de peajes.",
                max_length=10,
                verbose_name="Tipo de vehículo de peaje",
            ),
        ),
    ]
