# Generated by Django 5.2.12 on 2026-06-29 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0038_company_toll_markup_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPeriodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nombre descriptivo del periodo (p. ej. 'Junio-Julio 2026'). Se muestra como cabecera en la lista de periodos y en el historial de partes del operario.",
                        max_length=100,
                        verbose_name="Etiqueta",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Primer día del periodo de trabajo (inclusive).",
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Último día del periodo de trabajo (inclusive). Puede establecerse al crear el grupo sin que implique cierre.",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica que el periodo ha sido liquidado administrativamente. Cuando está activo, ningún parte dentro del rango puede editarse. Se activa manualmente por el ADMIN o SUPERVISOR al cerrar el periodo. Cierra también todos los WorkPeriod subordinados.",
                        verbose_name="Liquidado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este grupo de periodos de trabajo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_period_groups",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor o ADMIN que creó este grupo de periodos. Se establece automáticamente desde el usuario autenticado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_period_groups",
                        to="ivr_config.companyuser",
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de periodos de trabajo",
                "verbose_name_plural": "Grupos de periodos de trabajo",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="workperiod",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo de periodo al que pertenece este registro individual. Nulo para registros legacy creados antes de la introducción de WorkPeriodGroup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_periods",
                to="ivr_config.workperiodgroup",
                verbose_name="Grupo de periodo",
            ),
        ),
    ]
