# Generated by Django 5.2.12 on 2026-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0039_workperiodgroup_workperiod_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="can_view_budget_breakdown",
            field=models.BooleanField(
                default=False,
                help_text="Solo aplica a usuarios con rol Operario de Asistencia. Cuando está activo, además de crear presupuestos, el usuario puede ver el historial completo y el desglose detallado de cualquier presupuesto — funcionalidad normalmente exclusiva de Administrador. No concede ningún otro permiso de ADMIN.",
                verbose_name="Puede ver desglose de presupuestos",
            ),
        ),
    ]
