# Generated by Django 5.2.12 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0040_companyuser_can_view_budget_breakdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("OPERATOR", "Operador"),
                    ("WORKSHOP", "Operario de taller"),
                    ("WORKSHOPBOSS", "Jefe de taller"),
                    ("SUPERVISOR", "Supervisor"),
                    ("DRIVER", "Chófer"),
                    ("ASSISTANCE", "Operario de Asistencia"),
                    ("DOCS_SUPERVISOR", "Supervisor de Documentación"),
                ],
                default="OPERATOR",
                help_text="ADMIN: acceso completo a la configuración. OPERATOR: gestión de presencia. WORKSHOP: partes de taller. WORKSHOPBOSS: jefe de taller — tickets de avería, sala BREAKDOWNS y sección propia, más acceso equivalente a SUPERVISOR en Taller, Administración y jornada. SUPERVISOR: revisión y exportación de partes PDF. DRIVER: reservado. ASSISTANCE: operario de Asistencia — solo modulo de presupuestos. DOCS_SUPERVISOR: puede subir documentación de centros de gasto (el listado es de solo lectura para cualquier usuario).",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
