# Generated by Django 5.2.12 on 2026-07-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0041_alter_companyuser_role"),
        ("budgets", "0030_budget_manual_toll_segments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_users",
                to="budgets.base",
                verbose_name="Base",
                help_text="Base física de referencia de este usuario. Determina qué calendario laboral/festivos (Base.labor_calendar, ya sincronizado vía sync_base_calendars) aplica a sus vacaciones en el calendario de RRHH (H24). Nulo para roles que no lo necesitan (p. ej. ADMIN).",
            ),
        ),
    ]
