# Generated by Django 5.2.12 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0042_companyuser_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="pending_onboarding",
            field=models.BooleanField(
                default=False,
                help_text="2026-07-23 (H25) -- True cuando este CompanyUser se creó automáticamente al subir documentación de un trabajador que todavía no tenía cuenta (\"pre-registro\": Miguel Ángel, \"leemos el nombre de la carpeta... iniciamos ya el proceso de registro... lo único que nos va a faltar es el teléfono, que lo obtendremos cuando el trabajador inicie la conversación con el chatbot\"). Mientras esté activo: is_active=False (no puede entrar al panel), sin contraseña utilizable, sin Contact/teléfono, rol y sección todavía sin confirmar. Se pone a False cuando el propio trabajador completa el alta real por WhatsApp (WhatsAppOnboardingService._create_user, DNI coincidente -- ese momento activa la cuenta y rellena lo que faltaba, en vez de crear un CompanyUser duplicado).",
                verbose_name="Pre-registro pendiente de onboarding",
            ),
        ),
    ]
