# Generated by Django 5.2.12 on 2026-07-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0041_alter_companyuser_role"),
        ("work_order_processor", "0030_taskphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_periods",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_periods",
                        to="ivr_config.companyuser",
                        verbose_name="Operario/chófer",
                    ),
                ),
                (
                    "generated_entry_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacation_period",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Tarea automática generada",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacation_periods_created",
                        to="ivr_config.companyuser",
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de vacaciones",
                "verbose_name_plural": "Periodos de vacaciones",
                "ordering": ["-date_start"],
            },
        ),
        migrations.AddConstraint(
            model_name="vacationperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("date_end__gte", models.F("date_start"))),
                name="vacationperiod_date_end_gte_date_start",
            ),
        ),
    ]
