# Generated by Django 5.2.12 on 2026-05-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0018_workdayschedule_season_split_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakdownTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("IN_PROGRESS", "En curso"),
                            ("RESOLVED", "Resuelto"),
                        ],
                        default="OPEN",
                        help_text="Estado actual del ticket. Ciclo: OPEN → IN_PROGRESS → RESOLVED.",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "machine_raw",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificación de la máquina o vehículo afectado tal como la describe el contacto.",
                        max_length=200,
                        verbose_name="Máquina / Vehículo",
                    ),
                ),
                (
                    "fault_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción de la avería recogida por el agente Gemini mediante diálogo natural.",
                        verbose_name="Resumen de la avería",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ubicación actual del vehículo o lugar donde ocurrió la avería.",
                        max_length=200,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="",
                        help_text="Nivel de urgencia. El agente Gemini sugiere y el contacto confirma.",
                        max_length=10,
                        verbose_name="Urgencia",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones adicionales del operario recogidas durante el diálogo.",
                        verbose_name="Notas adicionales",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp en que el SUPERVISOR marcó el ticket como RESOLVED.",
                        null=True,
                        verbose_name="Fecha de resolución",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="Contacto de WhatsApp que inició el reporte de avería.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakdown_tickets",
                        to="ivr_config.contact",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario del panel (SUPERVISOR) que cerró el ticket.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_breakdown_tickets",
                        to="ivr_config.companyuser",
                        verbose_name="Resuelto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de avería",
                "verbose_name_plural": "Tickets de avería",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BreakdownConversationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "Usuario"), ("MODEL", "Modelo")],
                        help_text="USER: turno del contacto. MODEL: turno del agente Gemini.",
                        max_length=5,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texto completo del turno de diálogo.",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket de avería al que pertenece este turno de diálogo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="chat.breakdownticket",
                        verbose_name="Ticket de avería",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de conversación de avería",
                "verbose_name_plural": "Turnos de conversación de avería",
                "ordering": ["ticket", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[("SECTION", "Sección"), ("BREAKDOWNS", "Averías")],
                        help_text="SECTION: sala de difusión de mensajes WhatsApp de una sección. BREAKDOWNS: sala especial de recogida de averías con agente Gemini.",
                        max_length=20,
                        verbose_name="Tipo de sala",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre legible de la sala mostrado en el panel.",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la sala está operativa y visible en el panel.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece esta sala de chat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sección asociada a esta sala. Nulo únicamente para salas de tipo BREAKDOWNS.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_rooms",
                        to="ivr_config.section",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala de chat",
                "verbose_name_plural": "Salas de chat",
                "ordering": ["company__name", "room_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Entrante"), ("OUTBOUND", "Saliente")],
                        help_text="INBOUND: mensaje entrante de WhatsApp. OUTBOUND: mensaje saliente desde el panel.",
                        max_length=10,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Texto completo del mensaje.",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "whatsapp_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SID del mensaje asignado por Twilio. Vacío para mensajes del agente Gemini.",
                        max_length=64,
                        verbose_name="SID de WhatsApp",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Indexado para consultas de polling por rango de fechas.",
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "sender_contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contacto de WhatsApp origen del mensaje. Informado únicamente para mensajes INBOUND.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages_sent",
                        to="ivr_config.contact",
                        verbose_name="Contacto remitente",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario del panel que envió el mensaje. Informado únicamente para mensajes OUTBOUND.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages_sent",
                        to="ivr_config.companyuser",
                        verbose_name="Usuario remitente",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Sala de chat a la que pertenece este mensaje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de chat",
                "verbose_name_plural": "Mensajes de chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="breakdownticket",
            name="room",
            field=models.ForeignKey(
                help_text="Sala BREAKDOWNS de la empresa a la que pertenece este ticket.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakdown_tickets",
                to="chat.chatroom",
                verbose_name="Sala",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_type", "BREAKDOWNS")),
                fields=("company",),
                name="unique_breakdowns_room_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_type", "SECTION")),
                fields=("company", "section"),
                name="unique_section_room_per_company_section",
            ),
        ),
    ]
