# Generated by Django 5.2.12 on 2026-05-21 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_breakdownticket_is_repair_order_and_more"),
        ("ivr_config", "0025_workshopboss_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="WORKSHOPBOSS al que se ha asignado este ticket para su atención. Null cuando el ticket está disponible para cualquier jefe de taller.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_breakdown_tickets",
                to="ivr_config.companyuser",
                verbose_name="Asignado a",
            ),
        ),
    ]
