# Generated by Django 5.2.12 on 2026-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_breakdownticket_is_repair_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakdownticket",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CHATBOT", "Chatbot"),
                    ("IVR", "IVR (llamada de voz)"),
                ],
                default="MANUAL",
                help_text="Indica si el ticket fue creado manualmente o por el chatbot.",
                max_length=8,
                verbose_name="Origen",
            ),
        ),
    ]
