# Generated by Django 5.2.12 on 2026-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_breakdownticket_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownticket",
            name="fault_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ubicación exacta de la avería en la máquina (ej. 'rueda delantera lado conductor'). Recogida por el agente IVR o WhatsApp.",
                max_length=255,
                verbose_name="Ubicación en máquina",
            ),
        ),
        migrations.AddField(
            model_name="breakdownticket",
            name="geo_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud GPS real de la avería. Recibida vía WhatsApp location o resuelta desde la base más próxima.",
                max_digits=9,
                null=True,
                verbose_name="Latitud GPS",
            ),
        ),
        migrations.AddField(
            model_name="breakdownticket",
            name="geo_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud GPS real de la avería. Recibida vía WhatsApp location o resuelta desde la base más próxima.",
                max_digits=9,
                null=True,
                verbose_name="Longitud GPS",
            ),
        ),
        migrations.AddField(
            model_name="breakdownticket",
            name="location_warning",
            field=models.BooleanField(
                default=False,
                help_text="True si no se pudo obtener geolocalización: el contacto no envió ubicación o se superó el timeout de 3 minutos.",
                verbose_name="Sin geolocalización",
            ),
        ),
    ]
