# Generated by Django 5.2.12 on 2026-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_h17_remove_chatroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownticket",
            name="conversation_log",
            field=models.JSONField(
                default=list,
                help_text="Historial unificado de la conversación asociada a este ticket. Lista de entradas con formato: {timestamp, source ('IVR'|'WHATSAPP'|'SYSTEM'), role ('USER'|'MODEL'), content}. Poblado por el agente IVR (Alia) y el agente WhatsApp.",
                verbose_name="Log de conversación",
            ),
        ),
        migrations.AlterField(
            model_name="breakdownticket",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CHATBOT", "Chatbot"),
                    ("IVR", "IVR (llamada de voz)"),
                ],
                default="MANUAL",
                help_text="Indica si el ticket fue creado manualmente, por el chatbot o por IVR.",
                max_length=8,
                verbose_name="Origen",
            ),
        ),
    ]
