# Generated by Django 5.2.12 on 2026-07-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_breakdownticket_conversation_log_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakdownticket",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("CHATBOT", "Chatbot"),
                    ("IVR", "IVR (llamada de voz)"),
                    ("AUTO", "Auto-generado"),
                ],
                default="MANUAL",
                help_text="Indica si el ticket fue creado manualmente, por el chatbot o por IVR.",
                max_length=8,
                verbose_name="Origen",
            ),
        ),
    ]
