# Generated by Django 5.2.12 on 2026-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_breakdownticket_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakdownticket",
            name="task_category_free",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Categorización libre generada por Gemini para tareas con tipo_tarea distinto de AVERIA (mejora, mantenimiento, fabricación...), sin taxonomía rígida. Vacío cuando tipo_tarea=AVERIA (se usa fault_category/fault_subcategory en su lugar) o cuando el ticket todavía no se ha clasificado.",
                max_length=200,
                verbose_name="Categoría de tarea (libre)",
            ),
        ),
        migrations.AddField(
            model_name="breakdownticket",
            name="tipo_tarea",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVERIA", "Avería"),
                    ("MEJORA", "Mejora"),
                    ("MANTENIMIENTO", "Mantenimiento"),
                    ("FABRICACION", "Fabricación"),
                ],
                default="",
                help_text="Naturaleza de la tarea anclada a este ticket. Vacío hasta que la tarea Celery classify_fault_line lo clasifica al grabar la primera tarea del ticket. AVERIA usa fault_category/fault_subcategory (en WorkOrderEntryLine); el resto usa task_category_free.",
                max_length=15,
                verbose_name="Tipo de tarea",
            ),
        ),
    ]
