# Generated by Django 5.2.12 on 2026-04-22 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0010_alter_datacaptureset_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa_codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código corto de la empresa en el catálogo (ej: GRA, TRA, GRH). Se usa para agrupación y filtrado por empresa origen.",
                        max_length=20,
                        verbose_name="Código de Empresa",
                    ),
                ),
                (
                    "empresa_nombre",
                    models.CharField(
                        help_text="Nombre completo de la empresa tal como aparece en el catálogo.",
                        max_length=200,
                        verbose_name="Nombre de Empresa",
                    ),
                ),
                (
                    "familia",
                    models.CharField(
                        blank=True,
                        help_text="Familia de maquinaria del catálogo (ej: MOVILES, PLATAFOR, CARR, AUTOCARG, REMOLQUE, TTE.).",
                        max_length=100,
                        verbose_name="Familia",
                    ),
                ),
                (
                    "tipo_codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código del tipo de maquinaria en el catálogo (ej: MV035, PLTJ-E08, CG050).",
                        max_length=50,
                        verbose_name="Código de Tipo",
                    ),
                ),
                (
                    "tipo_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Descripción legible del tipo de maquinaria (ej: GRUA MOVIL DE 35 TM, TIJERA ELECTRICA DE 8 MTS.).",
                        max_length=200,
                        verbose_name="Nombre de Tipo",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la máquina en el catálogo (ej: A54, Z45, B27). Es la clave de búsqueda principal para resolver referencias de partes de trabajo. Se almacena en mayúsculas.",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True,
                        help_text="Matrícula o número de bastidor abreviado del vehículo o maquinaria. Puede coincidir con el código en equipos sin matrícula oficial.",
                        max_length=50,
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "num_bastidor",
                    models.CharField(
                        blank=True,
                        help_text="Número de bastidor completo tal como figura en el catálogo.",
                        max_length=100,
                        verbose_name="Nº Bastidor",
                    ),
                ),
                (
                    "marca_modelo",
                    models.CharField(
                        blank=True,
                        help_text="Marca y modelo del vehículo o maquinaria (ej: LIEBHERR LTM 1055, LUNA GT-60/42, STILL RX20-20).",
                        max_length=200,
                        verbose_name="Marca / Modelo",
                    ),
                ),
                (
                    "fecha_compra",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de adquisición del vehículo o maquinaria.",
                        null=True,
                        verbose_name="Fecha de Compra",
                    ),
                ),
                (
                    "kms",
                    models.IntegerField(
                        default=0,
                        help_text="Kilómetros registrados en el catálogo en el momento de la importación.",
                        verbose_name="Kilómetros",
                    ),
                ),
                (
                    "horas",
                    models.IntegerField(
                        default=0,
                        help_text="Horas de trabajo registradas en el catálogo en el momento de la importación.",
                        verbose_name="Horas de Trabajo",
                    ),
                ),
                (
                    "es_activo",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indica si la unidad está activa en la flota. Las unidades dadas de baja se marcan como inactivas.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "importado_en",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se importó este registro desde el catálogo.",
                        verbose_name="Importado en",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación del registro.",
                        verbose_name="Actualizado en",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa propietaria de esta unidad de maquinaria. Corresponde al campo EMPRESA del catálogo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_assets",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo de Flota",
                "verbose_name_plural": "Activos de Flota",
                "ordering": ["empresa_codigo", "familia", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha en que se realizó la intervención de mantenimiento.",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de los trabajos realizados durante la intervención.",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "operario",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del mecánico o técnico que realizó la intervención. Se propaga desde el parte de trabajo cuando procede.",
                        max_length=200,
                        verbose_name="Operario",
                    ),
                ),
                (
                    "horas_imputadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Horas de mano de obra propia imputadas a esta intervención. Se calcula a partir del delta de horas del parte de trabajo.",
                        max_digits=6,
                        verbose_name="Horas Imputadas",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales del supervisor o del operario.",
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "machine_asset",
                    models.ForeignKey(
                        help_text="Máquina o vehículo sobre el que se realiza la intervención.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="fleet.machineasset",
                        verbose_name="Activo de Flota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Mantenimiento",
                "verbose_name_plural": "Registros de Mantenimiento",
                "ordering": ["-fecha", "machine_asset"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REPUESTO_ALMACEN", "Repuesto — Almacén propio"),
                            ("REPUESTO_TERCERO", "Repuesto — Tercero"),
                            ("MANO_OBRA_TERCERO", "Mano de obra — Tercero"),
                        ],
                        db_index=True,
                        help_text="Tipo de concepto: repuesto de almacén propio, repuesto de tercero o mano de obra de tercero.",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Nombre o descripción del repuesto, pieza o concepto de mano de obra.",
                        max_length=300,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Referencia del repuesto o pieza (código de almacén, referencia del fabricante, etc.). Vacío para mano de obra de tercero.",
                        max_length=100,
                        verbose_name="Referencia",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Cantidad consumida del repuesto o pieza.",
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "coste_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coste unitario del repuesto o concepto en euros. Puede quedar vacío si no se conoce en el momento del registro.",
                        max_digits=10,
                        null=True,
                        verbose_name="Coste Unitario (€)",
                    ),
                ),
                (
                    "albaran_ref",
                    models.CharField(
                        blank=True,
                        help_text="Referencia del albarán o factura del proveedor externo. Vacío para repuestos de almacén propio. Permite trazar el coste al documento de tercero cuando el módulo de albaranes esté disponible.",
                        max_length=100,
                        verbose_name="Referencia de Albarán",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "maintenance_log",
                    models.ForeignKey(
                        help_text="Intervención de mantenimiento a la que pertenece esta línea.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fleet.maintenancelog",
                        verbose_name="Registro de Mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Mantenimiento",
                "verbose_name_plural": "Líneas de Mantenimiento",
                "ordering": ["maintenance_log", "tipo", "descripcion"],
            },
        ),
        migrations.AddIndex(
            model_name="machineasset",
            index=models.Index(
                fields=["empresa_codigo", "familia"],
                name="fleet_machi_empresa_df0f3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machineasset",
            index=models.Index(fields=["codigo"], name="fleet_machi_codigo_c94f12_idx"),
        ),
    ]
