# Generated by Django 5.2.12 on 2026-04-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("work_order_processor", "0002_remove_workorderentry_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="work_entry_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea del parte de trabajo que originó esta intervención. Nulo si la intervención se introdujo manualmente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_logs",
                to="work_order_processor.workorderentryline",
                verbose_name="Línea de Parte de Trabajo",
            ),
        ),
    ]
