# Generated by Django 5.2.12 on 2026-05-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_rename_fields_english"),
        ("ivr_config", "0013_alter_companyuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machineasset",
            options={
                "ordering": ["company_code", "family", "code"],
                "verbose_name": "Centro de gasto",
                "verbose_name_plural": "Centros de gasto",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenanceitem",
            options={
                "ordering": ["maintenance_log", "item_type", "description"],
                "verbose_name": "Línea de Mantenimiento",
                "verbose_name_plural": "Líneas de Mantenimiento",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancelog",
            options={
                "ordering": ["-date", "machine_asset"],
                "verbose_name": "Registro de Mantenimiento",
                "verbose_name_plural": "Registros de Mantenimiento",
            },
        ),
        migrations.RemoveIndex(
            model_name="machineasset",
            name="fleet_machi_empresa_df0f3e_idx",
        ),
        migrations.RemoveIndex(
            model_name="machineasset",
            name="fleet_machi_codigo_c94f12_idx",
        ),
        migrations.AddField(
            model_name="machineasset",
            name="has_crane_hours",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el operario debe registrar la lectura del horómetro de grúa al enviar un parte para este activo.",
                verbose_name="Tiene horómetro de grúa",
            ),
        ),
        migrations.AddField(
            model_name="machineasset",
            name="has_engine_hours",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el operario debe registrar la lectura del horómetro de motor al enviar un parte para este activo.",
                verbose_name="Tiene horómetro de motor",
            ),
        ),
        migrations.AddField(
            model_name="machineasset",
            name="has_odometer",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el operario debe registrar la lectura de kilómetros (odómetro) al enviar un parte para este activo.",
                verbose_name="Tiene odómetro",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("WAREHOUSE_PART", "Repuesto — Almacén propio"),
                    ("THIRD_PARTY_PART", "Repuesto — Tercero"),
                    ("THIRD_PARTY_LABOUR", "Mano de obra — Tercero"),
                ],
                db_index=True,
                help_text="Tipo de concepto: repuesto de almacén propio, repuesto de tercero o mano de obra de tercero.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="machine_asset",
            field=models.ForeignKey(
                help_text="Máquina o vehículo sobre el que se realiza la intervención.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_logs",
                to="fleet.machineasset",
                verbose_name="Centro de gasto",
            ),
        ),
        migrations.AddIndex(
            model_name="machineasset",
            index=models.Index(
                fields=["company_code", "family"], name="fleet_machi_company_e255a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machineasset",
            index=models.Index(fields=["code"], name="fleet_machi_code_f6895c_idx"),
        ),
    ]
