# Generated by Django 5.2.12 on 2026-04-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0012_callflow_backup_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("config", models.JSONField(verbose_name="configuración")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_profiles",
                        to="ivr_config.companyuser",
                        verbose_name="usuario de empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de analítica",
                "verbose_name_plural": "Perfiles de analítica",
                "ordering": ["nombre"],
                "unique_together": {("company_user", "nombre")},
            },
        ),
    ]
