# Generated by Django 5.2.12 on 2026-07-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0042_companyuser_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_dni_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="DNI detectado (sin asignar)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CLASSIFIED", "Clasificado"),
                            ("UNASSIGNED", "Clasificado, sin asignar"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Mensaje de error",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre legible",
                    ),
                ),
                (
                    "source_master_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Origen (documento maestro)",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre de archivo original",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de caducidad",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de emisión",
                    ),
                ),
                (
                    "validity_rule",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Regla de vigencia (texto detectado)",
                    ),
                ),
                (
                    "computed_expiry_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de caducidad calculada",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Número/referencia de documento",
                    ),
                ),
                (
                    "issuing_entity",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Entidad emisora",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Inicio de periodo",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fin de periodo",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Importe",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Metadatos adicionales",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        verbose_name="Archivado",
                    ),
                ),
                (
                    "gcs_blob_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Ruta del objeto en Google Cloud Storage",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        upload_to="personal_documents/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_documents",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "company_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_documents",
                        to="ivr_config.companyuser",
                        verbose_name="Trabajador",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_documents_uploaded",
                        to="ivr_config.companyuser",
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de personal",
                "verbose_name_plural": "Documentos de personal",
                "ordering": ["-created_at"],
            },
        ),
    ]
