# Generated by Django 5.2.12 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldocument",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Hash de contenido (SHA-256)",
            ),
        ),
    ]
