# /home/MiguelAeTxio/PROJECTS/EnterpriseBot/vox_bridge/management/commands/launch_voice_system.py
import os
import time
import subprocess
import sys
from django.core.management.base import BaseCommand
from twilio.rest import Client

"""
EnterpriseBot Unified Launcher: Real-time logs and DNS Guard Period.
April 2026 Standard: Integration of --no-call flag for zero-cost architecture validation.
---
Lanzador Unificado de EnterpriseBot: Logs en tiempo real y Periodo de Guarda DNS.
Estándar de Abril de 2026: Integración del flag --no-call para validación de arquitectura sin coste.
"""

class Command(BaseCommand):
    """
    Management command to orchestrate the entire voice infrastructure.
    Supports dry-runs to save Twilio credits during networking audits.
    ---
    Comando de gestión para orquestar toda la infraestructura de voz.
    Soporta ejecuciones de prueba para ahorrar créditos de Twilio durante auditorías de red.
    """
    help = 'Lanza la infraestructura y dispara la llamada en consola única con opción de prueba sin coste.'

    def add_arguments(self, parser):
        """
        Defines command line arguments for the management command.
        ---
        Define los argumentos de línea de comandos para el comando de gestión.
        """
        # Flag to skip the Twilio outbound call / Flag para omitir la llamada saliente de Twilio.
        parser.add_argument(
            '--no-call',
            action='store_true',
            help='Inicia la infraestructura pero no dispara la llamada telefónica (Ahorro de costes).',
        )

    def handle(self, *args, **options):
        """
        Main execution logic for the infrastructure launcher.
        ---
        Lógica de ejecución principal para el lanzador de infraestructura.
        """
        project_root = "/home/MiguelAeTxio/PROJECTS/EnterpriseBot"
        orchestrator_path = os.path.join(project_root, "voice_orchestrator.py")
        shared_url_file = os.path.join(project_root, "DOCS/SESSION/NGROK_URL.txt")
        no_call_mode = options['no_call']
        
        self.stdout.write(self.style.MIGRATE_HEADING("\n# [SYSTEM] INICIANDO INFRAESTRUCTURA HÍBRIDA 2026..."))

        # 1. Port Cleanup / Limpieza de Puertos
        # Ensures no zombie processes are holding the bridge or ngrok ports.
        # Asegura que no haya procesos zombi ocupando los puertos del puente o ngrok.
        cleanup_script = "import psutil; [p.kill() for p in psutil.process_iter() if any(c.laddr.port in [8081, 4041, 4040] for c in psutil.net_connections(kind='inet') if c.pid == p.pid)]"
        subprocess.run(["python3", "-c", cleanup_script], capture_output=True)
        time.sleep(1)

        # 2. Launch Orchestrator / Lanzamiento del Orquestador
        # Spawns the main orchestrator that manages ngrok and the Sidecar bridge.
        # Lanza el orquestador principal que gestiona ngrok y el puente Sidecar.
        process = subprocess.Popen(
            ["python3", "-u", orchestrator_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            cwd=project_root,
            text=True,
            bufsize=1
        )

        # 3. URL Retrieval / Obtención de URL
        # Polls for the shared URL file generated by the orchestrator.
        # Sondea el archivo de URL compartido generado por el orquestador.
        public_url = None
        for _ in range(45): # Increased timeout for 2026 high-latency tunnel handshakes.
            if os.path.exists(shared_url_file):
                with open(shared_url_file, 'r') as f:
                    public_url = f.read().strip()
                    if public_url: break
            line = process.stdout.readline()
            if line: self.stdout.write(f"  > {line.strip()}")
            time.sleep(1)

        if not public_url:
            self.stdout.write(self.style.ERROR("# [ERROR] Fallo crítico al establecer el túnel ngrok."))
            process.terminate()
            return

        # 4. DNS Guard Period / Periodo de Guarda DNS
        # Crucial for .dev and dynamic domains in 2026 to ensure global propagation.
        # Crucial para .dev y dominios dinámicos en 2026 para asegurar propagación global.
        self.stdout.write(self.style.SUCCESS(f"# [INFO] Túnel activo: {public_url}"))
        self.stdout.write("# [AUDIT] Estabilizando señal DNS (15s)...")
        for i in range(15, 0, -1):
            self.stdout.write(f"  > Sincronizando: {i}s ", ending='\r')
            sys.stdout.flush()
            time.sleep(1)
        self.stdout.write("\n# [SUCCESS] Señal de red estabilizada.")

        # 5. Outbound Execution Logic / Lógica de Ejecución de Salida
        if no_call_mode:
            # DRY-RUN MODE: Networking audit only.
            # MODO DE PRUEBA: Solo auditoría de red.
            self.stdout.write(self.style.WARNING("# [MODE] Ejecución --no-call activa. Omitiendo disparo de Twilio."))
            self.stdout.write(f"# [INFO] Webhook de prueba listo en: {public_url}/api/vox/inbound/")
            self.stdout.write("# [MONITOR] Escuchando logs de la infraestructura (Pulsa Ctrl+C para finalizar)...\n")
        else:
            # LIVE MODE: Incurs Twilio costs.
            # MODO EN VIVO: Incurre en costes de Twilio.
            # ✅ FIX APRIL 2026: Directing webhook to the specific API path handled by the Hybrid Bridge.
            # CORRECCIÓN ABRIL 2026: Dirigiendo el webhook a la ruta API específica gestionada por el Bridge Híbrido.
            webhook_url = f"{public_url}/api/vox/inbound/" 
            
            try:
                # API Credentials from environment.
                # Credenciales de API desde el entorno.
                client = Client(
                    os.getenv('TWILIO_API_KEY_SID'), 
                    os.getenv('TWILIO_API_KEY_SECRET'), 
                    os.getenv('TWILIO_ACCOUNT_SID')
                )
                
                call = client.calls.create(
                    url=webhook_url, 
                    to="+34688360595", 
                    from_=os.getenv('TWILIO_PHONE_NUMBER'), 
                    method='POST'
                )
                
                self.stdout.write(self.style.SUCCESS(f"# [LIVE] Llamada disparada con éxito: {call.sid}"))
                self.stdout.write("# [MONITOR] Escuchando logs de la sesión en tiempo real...\n")
            except Exception as e:
                self.stdout.write(self.style.ERROR(f"# [TWILIO ERROR] Fallo en la llamada: {str(e)}"))

        # 6. Log Monitoring Loop / Bucle de Monitoreo de Logs
        try:
            while True:
                line = process.stdout.readline()
                if line:
                    self.stdout.write(f" [LOG] {line.strip()}")
                if process.poll() is not None:
                    break
        except KeyboardInterrupt:
            self.stdout.write(self.style.WARNING("\n# [SYSTEM] Finalizando sesión de orquestación..."))
        finally:
            # Clean process termination / Finalización limpia de procesos.
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()

