# /home/MiguelAeTxio/PROJECTS/EnterpriseBot/vox_bridge/management/commands/update_twilio_webhook.py
"""
Django management command to update the Twilio incoming phone number webhook
to point to the currently active ngrok tunnel URL.

Reads all required credentials from the Django settings environment and the
active ngrok URL from DOCS/SESSION/NGROK_URL.txt.

Usage (from project root, inside EnterpriseBot_venv):
    python -m dotenv run python manage.py update_twilio_webhook
---
Comando de gestión Django para actualizar el webhook del número de teléfono
entrante de Twilio para que apunte a la URL activa del túnel ngrok.

Lee todas las credenciales necesarias del entorno de settings de Django y la
URL activa de ngrok desde DOCS/SESSION/NGROK_URL.txt.

Uso (desde la raíz del proyecto, dentro de EnterpriseBot_venv):
    python -m dotenv run python manage.py update_twilio_webhook
"""

import os

from django.core.management.base import BaseCommand, CommandError
from twilio.rest import Client as TwilioClient


# ---------------------------------------------------------------------------
# CONSTANTS / CONSTANTES
# ---------------------------------------------------------------------------

# Path to the shared session file where voice_orchestrator.py writes the
# active ngrok HTTPS URL after successfully establishing the tunnel.
# Ruta al archivo de sesión compartido donde voice_orchestrator.py escribe
# la URL HTTPS activa de ngrok tras establecer el túnel correctamente.
NGROK_URL_FILE = (
    "/home/MiguelAeTxio/PROJECTS/EnterpriseBot/DOCS/SESSION/NGROK_URL.txt"
)


class Command(BaseCommand):
    """
    Updates the Twilio voice webhook for the configured phone number to point
    to the currently active ngrok tunnel URL read from NGROK_URL.txt.

    This command is intended for use during development and testing sessions
    to synchronise the Twilio webhook with the ephemeral ngrok tunnel URL
    generated by voice_orchestrator.py each time it is launched.

    It must be executed after voice_orchestrator.py has written the active
    tunnel URL to DOCS/SESSION/NGROK_URL.txt and before any inbound call test.
    ---
    Actualiza el webhook de voz de Twilio para el número configurado para que
    apunte a la URL activa del túnel ngrok leída desde NGROK_URL.txt.

    Este comando está pensado para su uso durante sesiones de desarrollo y
    pruebas para sincronizar el webhook de Twilio con la URL efímera del túnel
    ngrok generada por voice_orchestrator.py cada vez que se lanza.

    Debe ejecutarse después de que voice_orchestrator.py haya escrito la URL
    activa del túnel en DOCS/SESSION/NGROK_URL.txt y antes de cualquier prueba
    de llamada entrante.
    """

    help = (
        "Actualiza el webhook de voz de Twilio para que apunte al túnel ngrok activo. "
        "Requiere que voice_orchestrator.py esté en ejecución y haya escrito la URL "
        "en DOCS/SESSION/NGROK_URL.txt."
    )

    def handle(self, *args, **options):
        """
        Thin wrapper entry point for the management command. Delegates the
        full webhook update logic to VoiceOrchestrator.update_twilio_webhook()
        — the single source of truth for this operation — to avoid duplication
        between the orchestrator auto-update on startup and this manual command.

        Reads the active ngrok URL from NGROK_URL_FILE (written by the
        orchestrator on startup) and passes it to the orchestrator method.
        Raises CommandError on any unrecoverable failure.
        ---
        Punto de entrada thin wrapper del comando de gestión. Delega la lógica
        completa de actualización del webhook en
        VoiceOrchestrator.update_twilio_webhook() — única fuente de verdad para
        esta operación — para evitar duplicación entre el auto-update del
        orquestador en el arranque y este comando manual.

        Lee la URL activa de ngrok desde NGROK_URL_FILE (escrita por el
        orquestador en el arranque) y la pasa al método del orquestador.
        Lanza CommandError ante cualquier fallo irrecuperable.
        """

        # ------------------------------------------------------------------
        # STEP 1 — Read the active ngrok HTTPS URL from the shared session file.
        # PASO 1 — Leer la URL HTTPS activa de ngrok desde el archivo de sesión.
        # ------------------------------------------------------------------
        if not os.path.exists(NGROK_URL_FILE):
            raise CommandError(
                f"El archivo de sesión ngrok no existe: {NGROK_URL_FILE}. "
                "Asegúrese de que el orquestador de voz está activo y ha escrito "
                "la URL correctamente antes de ejecutar este comando."
            )

        with open(NGROK_URL_FILE, "r", encoding="utf-8") as fh:
            raw_ngrok_url = fh.read().strip().rstrip("/")

        if not raw_ngrok_url:
            raise CommandError(
                f"El archivo de sesión ngrok está vacío: {NGROK_URL_FILE}. "
                "Reinicie el orquestador de voz y vuelva a intentarlo."
            )

        self.stdout.write(f"# [INFO] URL activa de ngrok leída: {raw_ngrok_url}")

        # ------------------------------------------------------------------
        # STEP 2 — Import VoiceOrchestrator and delegate webhook update.
        # PASO 2 — Importar VoiceOrchestrator y delegar la actualización.
        # ------------------------------------------------------------------
        if PROJECT_ROOT not in sys.path:
            sys.path.insert(0, PROJECT_ROOT)

        try:
            from voice_orchestrator import VoiceOrchestrator
        except ImportError as exc:
            raise CommandError(
                f"No se pudo importar VoiceOrchestrator desde {PROJECT_ROOT}: "
                f"{exc}"
            )

        orchestrator = VoiceOrchestrator()
        success = orchestrator.update_twilio_webhook(raw_ngrok_url)

        if not success:
            raise CommandError(
                "La actualización de uno o más webhooks de Twilio falló. "
                "Revise los mensajes anteriores para más detalles."
            )

        self.stdout.write(
            self.style.SUCCESS(
                "# [SUCCESS] Todos los webhooks de Twilio actualizados correctamente "
                "desde el comando de gestión."
            )
        )
