# /home/MiguelAeTxio/PROJECTS/EnterpriseBot/vox_bridge/management/commands/update_twilio_webhook.py
"""
Django management command to update the Twilio incoming phone number webhook
to point to the currently active ngrok tunnel URL.

Reads all required credentials from the Django settings environment and the
active ngrok URL from DOCS/SESSION/NGROK_URL.txt.

Usage (from project root, inside EnterpriseBot_venv):
    python -m dotenv run python manage.py update_twilio_webhook
---
Comando de gestión Django para actualizar el webhook del número de teléfono
entrante de Twilio para que apunte a la URL activa del túnel ngrok.

Lee todas las credenciales necesarias del entorno de settings de Django y la
URL activa de ngrok desde DOCS/SESSION/NGROK_URL.txt.

Uso (desde la raíz del proyecto, dentro de EnterpriseBot_venv):
    python -m dotenv run python manage.py update_twilio_webhook
"""

import os

from django.core.management.base import BaseCommand, CommandError
from twilio.rest import Client as TwilioClient


# ---------------------------------------------------------------------------
# CONSTANTS / CONSTANTES
# ---------------------------------------------------------------------------

# Path to the shared session file where voice_orchestrator.py writes the
# active ngrok HTTPS URL after successfully establishing the tunnel.
# Ruta al archivo de sesión compartido donde voice_orchestrator.py escribe
# la URL HTTPS activa de ngrok tras establecer el túnel correctamente.
NGROK_URL_FILE = (
    "/home/MiguelAeTxio/PROJECTS/EnterpriseBot/DOCS/SESSION/NGROK_URL.txt"
)


class Command(BaseCommand):
    """
    Updates the Twilio voice webhook for the configured phone number to point
    to the currently active ngrok tunnel URL read from NGROK_URL.txt.

    This command is intended for use during development and testing sessions
    to synchronise the Twilio webhook with the ephemeral ngrok tunnel URL
    generated by voice_orchestrator.py each time it is launched.

    It must be executed after voice_orchestrator.py has written the active
    tunnel URL to DOCS/SESSION/NGROK_URL.txt and before any inbound call test.
    ---
    Actualiza el webhook de voz de Twilio para el número configurado para que
    apunte a la URL activa del túnel ngrok leída desde NGROK_URL.txt.

    Este comando está pensado para su uso durante sesiones de desarrollo y
    pruebas para sincronizar el webhook de Twilio con la URL efímera del túnel
    ngrok generada por voice_orchestrator.py cada vez que se lanza.

    Debe ejecutarse después de que voice_orchestrator.py haya escrito la URL
    activa del túnel en DOCS/SESSION/NGROK_URL.txt y antes de cualquier prueba
    de llamada entrante.
    """

    help = (
        "Actualiza el webhook de voz de Twilio para que apunte al túnel ngrok activo. "
        "Requiere que voice_orchestrator.py esté en ejecución y haya escrito la URL "
        "en DOCS/SESSION/NGROK_URL.txt."
    )

    def handle(self, *args, **options):
        """
        Entry point for the management command. Executes the full webhook
        update sequence: credential validation, ngrok URL resolution, Twilio
        client instantiation, phone number lookup, webhook update and verification.

        Raises CommandError on any unrecoverable failure so that Django's
        management framework can report the error cleanly and exit with a
        non-zero status code.
        ---
        Punto de entrada del comando de gestión. Ejecuta la secuencia completa
        de actualización del webhook: validación de credenciales, resolución de
        URL ngrok, instanciación del cliente Twilio, búsqueda del número de
        teléfono, actualización del webhook y verificación.

        Lanza CommandError ante cualquier fallo irrecuperable para que el
        framework de gestión de Django pueda reportar el error de forma limpia
        y salir con un código de estado no nulo.
        """

        # ------------------------------------------------------------------
        # STEP 1 — Validate required environment variables.
        # PASO 1 — Validar las variables de entorno requeridas.
        # ------------------------------------------------------------------
        required_env_vars = [
            "TWILIO_ACCOUNT_SID",
            "TWILIO_API_KEY_SID",
            "TWILIO_API_KEY_SECRET",
            "TWILIO_PHONE_NUMBER",
        ]
        missing_vars = [var for var in required_env_vars if not os.getenv(var)]
        if missing_vars:
            raise CommandError(
                f"Las siguientes variables de entorno son obligatorias y no están "
                f"definidas: {', '.join(missing_vars)}. "
                "Verifique el archivo .env del proyecto y ejecute con "
                "'python -m dotenv run python manage.py update_twilio_webhook'."
            )

        twilio_account_sid    = os.environ["TWILIO_ACCOUNT_SID"]
        twilio_api_key_sid    = os.environ["TWILIO_API_KEY_SID"]
        twilio_api_key_secret = os.environ["TWILIO_API_KEY_SECRET"]
        twilio_phone_number   = os.environ["TWILIO_PHONE_NUMBER"]

        # ------------------------------------------------------------------
        # STEP 2 — Read the active ngrok HTTPS URL from the shared session file.
        # PASO 2 — Leer la URL HTTPS activa de ngrok desde el archivo de sesión.
        # ------------------------------------------------------------------
        if not os.path.exists(NGROK_URL_FILE):
            raise CommandError(
                f"El archivo de sesión ngrok no existe: {NGROK_URL_FILE}. "
                "Asegúrese de que el orquestador de voz está activo y ha escrito "
                "la URL correctamente."
            )

        with open(NGROK_URL_FILE, "r", encoding="utf-8") as fh:
            raw_ngrok_url = fh.read().strip().rstrip("/")

        if not raw_ngrok_url:
            raise CommandError(
                f"El archivo de sesión ngrok está vacío: {NGROK_URL_FILE}. "
                "Reinicie el orquestador de voz y vuelva a intentarlo."
            )

        voice_webhook_url = f"{raw_ngrok_url}/api/vox/inbound/"

        self.stdout.write(f"# [INFO] URL activa de ngrok leída: {raw_ngrok_url}")
        self.stdout.write(f"# [INFO] Webhook de voz a configurar: {voice_webhook_url}")

        # ------------------------------------------------------------------
        # STEP 3 — Instantiate the Twilio REST client using API Key credentials.
        # The SDK 9.x supports ApiKeySid/ApiKeySecret authentication, which is
        # preferred for production use as it allows credential rotation without
        # modifying the account auth token.
        # PASO 3 — Instanciar el cliente REST de Twilio usando API Key.
        # El SDK 9.x soporta autenticación ApiKeySid/ApiKeySecret, preferida en
        # producción ya que permite rotación de credenciales sin modificar el
        # auth token de cuenta.
        # ------------------------------------------------------------------
        twilio_client = TwilioClient(
            twilio_api_key_sid,
            twilio_api_key_secret,
            twilio_account_sid,
        )
        self.stdout.write(
            f"# [INFO] Cliente Twilio instanciado correctamente para la cuenta: "
            f"{twilio_account_sid[:8]}...{twilio_account_sid[-4:]}"
        )

        # ------------------------------------------------------------------
        # STEP 4 — Locate the IncomingPhoneNumber SID matching TWILIO_PHONE_NUMBER.
        # PASO 4 — Localizar el SID de IncomingPhoneNumber que coincide con
        #          TWILIO_PHONE_NUMBER.
        # ------------------------------------------------------------------
        self.stdout.write(
            f"# [INFO] Buscando número {twilio_phone_number} en la cuenta Twilio..."
        )
        try:
            matching_numbers = twilio_client.incoming_phone_numbers.list(
                phone_number=twilio_phone_number
            )
        except Exception as exc:
            raise CommandError(
                f"Fallo al consultar la API de Twilio (incoming_phone_numbers.list): "
                f"{type(exc).__name__}: {exc}"
            )

        if not matching_numbers:
            raise CommandError(
                f"El número {twilio_phone_number} no se encontró en la cuenta "
                f"{twilio_account_sid}. "
                "Verifique que TWILIO_PHONE_NUMBER está en formato E.164 "
                "(p. ej. +12603466780) y que pertenece a esta cuenta."
            )

        if len(matching_numbers) > 1:
            self.stdout.write(
                self.style.WARNING(
                    f"# [WARNING] Se encontraron {len(matching_numbers)} números "
                    "coincidentes. Se actualizará únicamente el primero de la lista."
                )
            )

        target_number_resource = matching_numbers[0]
        phone_number_sid = target_number_resource.sid

        self.stdout.write(
            f"# [INFO] Número encontrado: {target_number_resource.phone_number} "
            f"| SID: {phone_number_sid}"
        )
        self.stdout.write(
            f"# [INFO] Webhook de voz actual registrado en Twilio: "
            f"{target_number_resource.voice_url or '(vacío)'}"
        )

        # ------------------------------------------------------------------
        # STEP 5 — Update voice_url and voice_method on the located phone number.
        # voice_method is explicitly set to POST to match the UniversalVoiceBridge
        # handle_twiml_post() handler in voice_sidecar_bridge.py.
        # PASO 5 — Actualizar voice_url y voice_method en el número localizado.
        # voice_method se establece explícitamente a POST para coincidir con el
        # handler handle_twiml_post() de UniversalVoiceBridge en
        # voice_sidecar_bridge.py.
        # ------------------------------------------------------------------
        self.stdout.write(
            f"# [INFO] Actualizando webhook de voz a: {voice_webhook_url} "
            "(método: POST)..."
        )
        try:
            updated_resource = twilio_client.incoming_phone_numbers(
                phone_number_sid
            ).update(
                voice_url=voice_webhook_url,
                voice_method="POST",
            )
        except Exception as exc:
            raise CommandError(
                f"Fallo al actualizar el webhook de voz en Twilio: "
                f"{type(exc).__name__}: {exc}"
            )

        # ------------------------------------------------------------------
        # STEP 6 — Confirm the update by comparing the returned voice_url.
        # PASO 6 — Confirmar la actualización comparando el voice_url devuelto.
        # ------------------------------------------------------------------
        if updated_resource.voice_url == voice_webhook_url:
            self.stdout.write(
                self.style.SUCCESS(
                    f"# [SUCCESS] Webhook de voz actualizado y verificado correctamente.\n"
                    f"#           Número  : {updated_resource.phone_number}\n"
                    f"#           SID     : {updated_resource.sid}\n"
                    f"#           URL     : {updated_resource.voice_url}\n"
                    f"#           Método  : {updated_resource.voice_method}"
                )
            )
        else:
            self.stdout.write(
                self.style.WARNING(
                    f"# [WARNING] La URL devuelta por Twilio no coincide con la "
                    f"URL solicitada.\n"
                    f"#           URL solicitada : {voice_webhook_url}\n"
                    f"#           URL devuelta   : {updated_resource.voice_url}\n"
                    "# Verifique manualmente en la consola de Twilio."
                )
            )
