# Generated by Django 5.2.12 on 2026-04-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0002_phonenumber_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono del usuario en formato E.164 (p. ej. +34XXXXXXXXX). Identifica de forma única al interlocutor externo dentro de la empresa.",
                        max_length=20,
                        verbose_name="Número de teléfono",
                    ),
                ),
                (
                    "session_start",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación de la sesión.",
                        verbose_name="Inicio de sesión",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora del último mensaje registrado en la sesión. Actualizado automáticamente en cada operación de guardado. La tarea expire_whatsapp_sessions usa este campo para determinar si la ventana de 24 horas de Meta ha expirado.",
                        verbose_name="Último mensaje",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True mientras la ventana de sesión Meta de 24 horas esté abierta. La tarea Celery expire_whatsapp_sessions lo establece a False cuando last_message_at supera las 24 horas.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa con la que se mantiene esta sesión de WhatsApp.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_sessions",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de WhatsApp",
                "verbose_name_plural": "Sesiones de WhatsApp",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Entrante"), ("OUT", "Saliente")],
                        help_text="IN: mensaje entrante del usuario. OUT: respuesta saliente del agente.",
                        max_length=3,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Contenido textual completo del mensaje.",
                        verbose_name="Cuerpo",
                    ),
                ),
                (
                    "message_sid",
                    models.CharField(
                        blank=True,
                        help_text="SID de mensaje Twilio (SMxxxxxxxx). Presente en mensajes salientes confirmados por la API de Twilio. Vacío en mensajes entrantes.",
                        max_length=50,
                        verbose_name="SID de mensaje",
                    ),
                ),
                (
                    "content_sid",
                    models.CharField(
                        blank=True,
                        help_text="SID del Content Template de Twilio (HXxxxxxxxx). Presente únicamente en mensajes salientes enviados mediante template. Vacío en mensajes de texto libre.",
                        max_length=50,
                        verbose_name="SID de contenido",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de registro del mensaje en la base de datos.",
                        verbose_name="Marca de tiempo",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Sesión de WhatsApp a la que pertenece este mensaje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp.whatsappsession",
                        verbose_name="Sesión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de WhatsApp",
                "verbose_name_plural": "Mensajes de WhatsApp",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificativo de la plantilla (p. ej. presence_reminder). Usado internamente para seleccionar la plantilla correcta en el código.",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "content_sid",
                    models.CharField(
                        help_text="SID del Content Template de Twilio en formato HXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. Obtenido del Content Template Builder del Console de Twilio tras la aprobación de Meta.",
                        max_length=50,
                        verbose_name="SID de contenido",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UTILITY", "Utilidad"),
                            ("MARKETING", "Marketing"),
                            ("AUTHENTICATION", "Autenticación"),
                        ],
                        help_text="Categoría Meta de la plantilla: UTILITY (notificaciones de servicio), MARKETING (promociones), AUTHENTICATION (OTP y verificación).",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Código de idioma BCP-47 de la plantilla (p. ej. 'es', 'en', 'ca'). Debe coincidir con el idioma registrado en el Console de Twilio.",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True si la plantilla está disponible para su uso. Establecer a False para retirar una plantilla sin eliminar su registro.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa propietaria de esta plantilla de mensaje.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_templates",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de WhatsApp",
                "verbose_name_plural": "Plantillas de WhatsApp",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["company", "phone_number", "is_active"],
                name="whatsapp_session_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["session", "timestamp"], name="whatsapp_message_history_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsapptemplate",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_whatsapp_template_per_company"
            ),
        ),
    ]
