# Generated by Django 5.2.12 on 2026-04-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0007_section_call_flow_callflow_fallback_section"),
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud geográfica contenida en el mensaje. Solo presente en mensajes de tipo 'location'. Twilio proporciona este valor en el campo Latitude del webhook POST.",
                max_digits=9,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud geográfica contenida en el mensaje. Solo presente en mensajes de tipo 'location'. Twilio proporciona este valor en el campo Longitude del webhook POST.",
                max_digits=9,
                null=True,
                verbose_name="Longitud",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("location", "Ubicación"),
                    ("media", "Media"),
                    ("template", "Template"),
                ],
                default="text",
                help_text="Tipo de contenido del mensaje: text (texto libre o respuesta del agente), location (mensaje de ubicación nativo de WhatsApp), media (imagen, documento u otro adjunto), template (mensaje enviado mediante Content Template de Twilio).",
                max_length=20,
                verbose_name="Tipo de mensaje",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud geográfica del cliente en grados decimales. Se rellena cuando el cliente comparte su ubicación por WhatsApp o cuando el IVR captura la posición vía DataCaptureSet.",
                max_digits=9,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="location_address",
            field=models.CharField(
                blank=True,
                help_text="Dirección postal legible asociada a las coordenadas de ubicación. Puede ser proporcionada por el propio mensaje de ubicación de WhatsApp o resolverse mediante Grounding with Google Maps (Paso 20).",
                max_length=500,
                verbose_name="Dirección formateada",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="location_captured_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se registró la ubicación geográfica del cliente. Permite auditar el momento exacto de la captura dentro de la sesión.",
                null=True,
                verbose_name="Ubicación capturada en",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud geográfica del cliente en grados decimales. Se rellena conjuntamente con latitude cuando la ubicación está disponible.",
                max_digits=9,
                null=True,
                verbose_name="Longitud",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="target_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Sección de la empresa a la que el cliente desea ser derivado. El agente chatbot detecta esta intención durante la conversación y actualiza este campo. Null si la intención aún no ha sido identificada o si el cliente no ha especificado sección.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_sessions",
                to="ivr_config.section",
                verbose_name="Sección destino",
            ),
        ),
    ]
