# Generated by Django 5.2.12 on 2026-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "whatsapp",
            "0002_whatsappsession_location_target_section_whatsappmessage_type_coords",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsession",
            name="pending_albaran_units",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de PKs de WorkOrderAssistanceUnit pendientes de notificar a este operario. Formato: [1, 2, 3]. Se vacía tras la entrega del enlace al albarán en el webhook opt_in.",
                verbose_name="Unidades de albarán pendientes",
            ),
        ),
    ]
