# Generated by Django 5.2.12 on 2026-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0003_whatsappsession_pending_albaran_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsession",
            name="pending_broadcast_messages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de mensajes de circular masiva pendientes de entregar a este operario. Formato: [{"body": "...", "created_at": "ISO"}]. Se popula cuando el operario está fuera de la ventana de 24h y se envía un chat_session_renewal. Se vacía tras la entrega en opt_in. Los mensajes con más de 48h se descartan automáticamente en la entrega.',
                verbose_name="Mensajes de circular pendientes",
            ),
        ),
    ]
