# Generated by Django 5.2.12 on 2026-07-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0005_add_first_repair_to_machineasset"),
        ("ivr_config", "0041_alter_companyuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre legible",
                    ),
                ),
                (
                    "source_master_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Origen (documento maestro)",
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="ID de archivo en Google Drive",
                    ),
                ),
                (
                    "drive_web_link",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Enlace de Google Drive",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_documents",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "machine_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.machineasset",
                        verbose_name="Máquina / Centro de gasto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="machine_documents_uploaded",
                        to="ivr_config.companyuser",
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de centro de gasto",
                "verbose_name_plural": "Documentos de centros de gasto",
                "ordering": ["-created_at"],
            },
        ),
    ]
