# Generated by Django 5.2.12 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="source_file",
            field=models.FileField(
                default="",
                upload_to="machine_documents/%Y/%m/",
                verbose_name="Archivo",
            ),
            preserve_default=False,
        ),
    ]
