# Generated by Django 5.2.12 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0002_machinedocument_source_file"),
    ]

    operations = [
        # Filas ya existentes (si las hay) fueron procesadas por el
        # pipeline síncrono anterior -- ya tienen document_type/
        # display_name rellenos, así que se consideran CLASSIFIED al
        # aplicar esta migración. El default=PENDING del modelo (para
        # objetos nuevos creados desde ahora) es un default de Python
        # a nivel de aplicación, independiente de este backfill de
        # ALTER TABLE.
        migrations.AddField(
            model_name="machinedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("CLASSIFIED", "Clasificado"),
                    ("ERROR", "Error"),
                ],
                default="CLASSIFIED",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="error_message",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Mensaje de error",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de caducidad",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="issue_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de emisión",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="document_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Número/referencia de documento",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="issuing_entity",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Entidad emisora",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="original_filename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nombre de archivo original",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nombre legible",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="source_file",
            field=models.FileField(
                blank=True,
                upload_to="machine_documents/%Y/%m/",
                verbose_name="Archivo",
            ),
        ),
    ]
