# Generated by Django 5.2.12 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0003_machinedocument_status_and_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="period_start",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Inicio de periodo",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="period_end",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fin de periodo",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Importe",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Metadatos adicionales",
            ),
        ),
    ]
