# Generated by Django 5.2.12 on 2026-07-16
# S022: persistencia en Google Cloud Storage para documentación de
# centros de gasto (H23 prioridad 0 -- migración fuera de Drive).
# Campo nuevo, blank=True, default="" -- coherente con
# drive_file_id/drive_web_link ya existentes en este mismo modelo, sin
# ambigüedad de las descritas en com-migrations sección 2.3.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0004_machinedocument_period_amount_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="gcs_blob_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Ruta del objeto en Google Cloud Storage",
            ),
        ),
    ]
