# Generated by Django 5.2.12 on 2026-07-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0005_machinedocument_gcs_blob_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="detected_reference_hint",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Código/matrícula detectado (sin asignar)",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="machine_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="fleet.machineasset",
                verbose_name="Máquina / Centro de gasto",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("CLASSIFIED", "Clasificado"),
                    ("UNASSIGNED", "Clasificado, sin asignar"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
