# Generated by Django 5.2.12 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0007_machinedocument_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="is_possible_master",
            field=models.BooleanField(
                default=False,
                verbose_name="Posible documento maestro (pendiente de resolver)",
            ),
        ),
    ]
