# Generated by Django 5.2.12 on 2026-07-20
# S025: campo nuevo para persistir la ruta GCS de la version Markdown
# de un documento (peticion explicita de Miguel Angel, manuales muy
# pesados). blank=True, default="" -- mismo criterio que gcs_blob_name
# (com-migrations seccion 2.3, sin ambiguedad: cadena vacia es el
# default natural de CharField con blank=True para las filas ya
# existentes).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0008_machinedocument_is_possible_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="markdown_blob_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Vacío hasta que se convierte a mano (botón "
                    "'Convertir a Markdown'). Una vez convertido, se "
                    "reutiliza sin volver a procesar el PDF."
                ),
                max_length=500,
                verbose_name="Ruta del Markdown en Google Cloud Storage",
            ),
        ),
    ]
