# Generated by Django 5.2.12 on 2026-07-21
# S026: campo nuevo para la salvaguarda de discrepancia nombre/
# contenido -- Miguel Angel, explicito: "no deberiamos de dejarlo
# unica y exclusivamente al nombre del archivo... si se sube y se
# asigna a esa maquina, marcarlo con incidencia". blank=True,
# default="" -- mismo criterio que gcs_blob_name/markdown_blob_name
# (com-migrations seccion 2.3).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0009_machinedocument_markdown_blob_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="content_mismatch_warning",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Se rellena cuando Gemini detecta, dentro del "
                    "propio contenido del documento, una referencia de "
                    "unidad (matrícula/número de serie) distinta de la "
                    "máquina a la que se asignó por nombre de archivo. "
                    "Nunca bloquea la subida -- solo avisa para "
                    "revisión manual."
                ),
                max_length=500,
                verbose_name="Aviso de discrepancia nombre/contenido",
            ),
        ),
    ]
