# Generated by Django 5.2.12 on 2026-07-21
# S026: campo FK nuevo para poder resolver la incidencia de
# discrepancia contra una fleet.MachineAsset concreta (en vez de solo
# un texto libre), y asi generar un boton de resolucion por cada
# maquina distinta implicada en la ficha de una maquina. related_name
# "+" (sin acceso inverso) -- mismo criterio que superseding_content_type
# de DocumentSubstitutionLog: es una referencia de trazabilidad, no
# una relacion de negocio que necesite consultarse en sentido inverso.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_add_first_repair_to_machineasset"),
        ("machine_documents", "0010_machinedocument_content_mismatch_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="content_mismatch_candidate_machine",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "La OTRA máquina real que la carpeta/nombre/"
                    "contenido sugieren para este documento, cuando se "
                    "pudo resolver a una fleet.MachineAsset concreta -- "
                    'Miguel Ángel, S026: "pulsando el botón, nos '
                    "dividirá la pantalla y nos muestra la máquina y la "
                    "máquina con la que hemos pulsado el botón que "
                    'tiene incidencia". Permite generar un botón de '
                    "resolución por cada máquina distinta implicada en "
                    "la ficha de máquina, en vez de un aviso de solo "
                    "texto. Vacío si el conflicto no se pudo resolver a "
                    "una máquina real conocida."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="fleet.machineasset",
                verbose_name="Máquina candidata en conflicto",
            ),
        ),
    ]
