# Generated by Django 5.2.12 on 2026-07-22
# S028: dos campos nuevos para que Gemini pueda marcar un documento
# como candidato a obsoleto durante su propia clasificacion (S028,
# Miguel Angel: "que sea Gemini quien decida... solo que la decision
# final de eliminar sea de un humano") -- default=False/"" para que
# las filas ya existentes queden sin marcar, sin necesitar ningun
# valor por defecto interactivo (tabla con datos reales).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0011_machinedocument_content_mismatch_candidate_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="obsolete_candidate",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Marcado por Gemini durante la clasificación cuando "
                    "el propio contenido del documento sugiere que ya no "
                    "tiene ningún valor operativo (p.ej. un recibo de "
                    "seguro caducado hace muchos años). Nunca se borra "
                    "solo -- aparece en la sección \"Candidatos a "
                    "documento obsoleto\" de la ficha de máquina para "
                    "revisión y confirmación humana."
                ),
                verbose_name="Candidato a documento obsoleto",
            ),
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="obsolete_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Justificación breve que dio Gemini al marcar el "
                    "documento como candidato a obsoleto. Vacío si "
                    "obsolete_candidate es False."
                ),
                max_length=500,
                verbose_name="Motivo de obsolescencia (Gemini)",
            ),
        ),
    ]
