# Generated by Django 5.2.12 on 2026-07-22
# S028: campo nuevo para anular manualmente el calculo automatico de
# vigencia (document_management.vigencia_service) sobre documentos que
# siguen siendo validos indefinidamente pese a ser antiguos --
# default=False para que las filas ya existentes sigan calculandose
# por fecha como hasta ahora, sin ningun cambio de comportamiento
# hasta que un supervisor marque explicitamente un documento.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine_documents", "0012_machinedocument_obsolete_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinedocument",
            name="force_current",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Si está marcado, el documento se trata SIEMPRE como "
                    "vigente, sin importar lo que calcule "
                    "vigencia_service por fechas -- para documentos que "
                    "siguen siendo válidos indefinidamente (p.ej. una "
                    "ficha técnica antigua) aunque el cálculo automático "
                    "los archivara por error."
                ),
                verbose_name="Vigencia forzada manualmente",
            ),
        ),
    ]
