# Generated by Django 5.2.12 on 2026-05-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0029_alter_companyuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "service_date",
                    models.DateField(
                        help_text="Fecha en la que se va a realizar el servicio.",
                        verbose_name="Fecha del servicio",
                    ),
                ),
                (
                    "is_overnight",
                    models.BooleanField(
                        default=False,
                        help_text="Activo cuando el servicio se realiza en dos fases: recogida del vehiculo el primer dia y traslado al destino al dia siguiente. Genera dos salidas y dos tramos de kilometraje independientes.",
                        verbose_name="Pernocta",
                    ),
                ),
                (
                    "km_phase1",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kilometros totales ida y vuelta de la primera fase del servicio. Si no es pernocta, estos son los unicos kilometros del servicio.",
                        max_digits=8,
                        verbose_name="Km fase 1 (ida+vuelta)",
                    ),
                ),
                (
                    "km_phase2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilometros totales ida y vuelta de la segunda fase del servicio. Solo aplica cuando is_overnight es True.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km fase 2 (ida+vuelta)",
                    ),
                ),
                (
                    "km_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Suma de km_phase1 + km_phase2. Calculado automaticamente al guardar.",
                        max_digits=8,
                        verbose_name="Km totales",
                    ),
                ),
                (
                    "has_unlock",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el servicio incluye desbloqueo o enganche con eslingas. No aplica a remolques (se desenganchan/enganchan directamente en la quinta rueda).",
                        verbose_name="Desbloqueo",
                    ),
                ),
                (
                    "is_night_or_holiday",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el servicio se realiza en horario nocturno o en festivo. Activa el recargo NYF de la tarifa de la aseguradora.",
                        verbose_name="Nocturno / Festivo",
                    ),
                ),
                (
                    "is_loaded",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el vehiculo asistido va cargado. Activa el recargo por vehiculo cargado si la tarifa lo contempla.",
                        verbose_name="Vehiculo cargado",
                    ),
                ),
                (
                    "wait_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numero de horas de espera facturables. Solo si la tarifa contempla este concepto.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas de espera",
                    ),
                ),
                (
                    "rescue_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numero de horas de rescate facturables. Solo si la tarifa contempla este concepto.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas de rescate",
                    ),
                ),
                (
                    "assistant_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numero de horas de ayudante facturables. Solo si la tarifa contempla este concepto.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas de ayudante",
                    ),
                ),
                (
                    "worker_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Numero de horas de mano de obra mecanica. Solo si la tarifa contempla este concepto.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas de mano de obra",
                    ),
                ),
                (
                    "custody_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Numero de dias de custodia del vehiculo. Solo si la tarifa contempla este concepto.",
                        null=True,
                        verbose_name="Dias de custodia",
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones libres del operario sobre este presupuesto. Uso interno.",
                        verbose_name="Notas adicionales",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe total calculado por el motor. Es la unica cifra visible para el operario.",
                        max_digits=10,
                        verbose_name="Total presupuesto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("ACCEPTED", "Aceptado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="DRAFT",
                        help_text="DRAFT: presupuesto calculado, pendiente de respuesta. ACCEPTED: la aseguradora o cliente ha aceptado el presupuesto. REJECTED: el presupuesto ha sido rechazado.",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa cliente que genera el presupuesto.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Operario que genero el presupuesto.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="ivr_config.companyuser",
                        verbose_name="Operario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept_code",
                    models.CharField(
                        help_text="Codigo interno del concepto aplicado (ej: DEPARTURE, KM_NORMAL, NYF_PERCENT).",
                        max_length=30,
                        verbose_name="Codigo de concepto",
                    ),
                ),
                (
                    "concept_label",
                    models.CharField(
                        help_text="Nombre legible en castellano del concepto aplicado.",
                        max_length=200,
                        verbose_name="Descripcion del concepto",
                    ),
                ),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad de unidades aplicadas (ej: 2 salidas, 115 km, 1.5 horas).",
                        max_digits=8,
                        verbose_name="Unidades",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio unitario de la linea de tarifa aplicada.",
                        max_digits=10,
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Resultado de units x unit_price para esta linea.",
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "is_surcharge",
                    models.BooleanField(
                        default=False,
                        help_text="Activo para lineas de recargo porcentual (nocturno/festivo, vehiculo cargado). Inactivo para conceptos base (salida, km, desbloqueo, etc.).",
                        verbose_name="Es recargo",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Orden de visualizacion en el desglose de auditoria ADMIN.",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Presupuesto al que pertenece esta linea de desglose.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgets.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea de presupuesto",
                "verbose_name_plural": "Lineas de presupuesto",
                "ordering": ["budget", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Insurer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre comercial de la aseguradora (ej: AXA Assistance, RACE, Mapfre).",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código identificador interno (ej: AXA, RACE, MAPFRE). Sin espacios.",
                        max_length=50,
                        verbose_name="Código interno",
                    ),
                ),
                (
                    "management_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de gastos de gestión aplicado sobre el total del presupuesto. 0 si la aseguradora no aplica este concepto. Ejemplo: COVEI aplica 5%.",
                        max_digits=5,
                        verbose_name="Gastos de gestión (%)",
                    ),
                ),
                (
                    "surcharges_are_cumulative",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el recargo nocturno/festivo y el recargo por vehículo cargado se suman. Si está inactivo (por defecto), se aplica únicamente el mayor de los dos, conforme a las condiciones generales de la mayoría de aseguradoras.",
                        verbose_name="Recargos acumulables",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta aseguradora está disponible para generar presupuestos.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones internas sobre esta aseguradora. No visible al operario.",
                        verbose_name="Notas internas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa cliente a la que pertenece esta aseguradora.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurers",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aseguradora",
                "verbose_name_plural": "Aseguradoras",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="insurer",
            field=models.ForeignKey(
                help_text="Aseguradora o cliente para el que se genera el presupuesto.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="budgets.insurer",
                verbose_name="Aseguradora",
            ),
        ),
        migrations.CreateModel(
            name="InsurerTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Año de vigencia de la tarifa (ej: 2026).",
                        verbose_name="Año",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Fecha a partir de la cual esta tarifa está en vigor.",
                        verbose_name="Válida desde",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la que esta tarifa estuvo en vigor. Null indica que es la tarifa actualmente activa.",
                        null=True,
                        verbose_name="Válida hasta",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones sobre esta versión de tarifa (ej: cambios respecto a la anterior).",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        help_text="Aseguradora a la que pertenece esta tarifa.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="budgets.insurer",
                        verbose_name="Aseguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de aseguradora",
                "verbose_name_plural": "Tarifas de aseguradora",
                "ordering": ["insurer__name", "-valid_from"],
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="tariff",
            field=models.ForeignKey(
                help_text="Version de tarifa que se uso para calcular este presupuesto.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="budgets.insurertariff",
                verbose_name="Tarifa aplicada",
            ),
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre exacto del tipo de vehículo según la tarifa de la aseguradora. Se muestra tal cual en el desplegable del formulario de presupuesto.",
                        max_length=300,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posición en el desplegable. Menor número = aparece antes.",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este tipo de vehículo está disponible en el formulario.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        help_text="Aseguradora a cuyo catálogo pertenece este tipo de vehículo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_types",
                        to="budgets.insurer",
                        verbose_name="Aseguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de vehículo",
                "verbose_name_plural": "Tipos de vehículo",
                "ordering": ["insurer__name", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TariffLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.CharField(
                        choices=[
                            ("DEPARTURE", "Salida / Enganche"),
                            ("SERVICE_LOCAL", "Servicio local / Urbano"),
                            ("KM_NORMAL", "Kilometro normal"),
                            ("KM_LONG", "Kilometro largo recorrido"),
                            ("UNLOCK", "Desbloqueo / Enganche eslingas"),
                            ("RESCUE_HOUR", "Hora de rescate"),
                            ("WAIT_HOUR", "Hora de espera"),
                            ("WORKER_HOUR", "Hora de mano de obra"),
                            ("ASSISTANT_HOUR", "Hora de ayudante"),
                            ("CUSTODY_DAY", "Custodia por dia"),
                            ("NYF_PERCENT", "Recargo nocturno/festivo (%)"),
                            ("LOADED_PERCENT", "Recargo vehiculo cargado (%)"),
                        ],
                        help_text="Tipo de concepto facturable que representa esta linea.",
                        max_length=30,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("FIXED", "Importe fijo"),
                            ("PER_KM", "Por kilometro"),
                            ("PER_HOUR", "Por hora"),
                            ("PER_DAY", "Por dia"),
                            ("PERCENT", "Porcentaje"),
                        ],
                        help_text="Unidad de medida del concepto (fijo, por km, por hora, por dia, porcentaje).",
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe unitario del concepto. Para PERCENT, es el porcentaje (ej: 50 para un recargo del 50%). Para FIXED, es el importe fijo en euros.",
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "km_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Solo para KM_LARGO. Kilometraje total (ida+vuelta) a partir del cual aplica esta tarifa reducida. Habitualmente 200. Dejar vacio para KM_NORMAL.",
                        null=True,
                        verbose_name="Umbral de km",
                    ),
                ),
                (
                    "min_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimo de unidades a facturar aunque el valor real sea inferior. Ejemplo: hora de rescate con minimo 2 horas. Dejar vacio si no aplica.",
                        max_digits=5,
                        null=True,
                        verbose_name="Minimo facturable",
                    ),
                ),
                (
                    "requires_authorization",
                    models.BooleanField(
                        default=False,
                        help_text="Si esta activo, este concepto debe haber sido autorizado previamente por la central de la aseguradora antes de poder incluirse en el presupuesto.",
                        verbose_name="Requiere autorizacion",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        help_text="Tarifa a la que pertenece esta linea de concepto.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgets.insurertariff",
                        verbose_name="Tarifa",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de vehiculo al que aplica esta linea. Dejar vacio para conceptos genericos de la tarifa (recargos NYF, vehículo cargado, desbloqueo cuando es precio unico).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_lines",
                        to="budgets.vehicletype",
                        verbose_name="Tipo de vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea de tarifa",
                "verbose_name_plural": "Lineas de tarifa",
                "ordering": ["tariff", "vehicle_type__sort_order", "concept"],
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="vehicle_type",
            field=models.ForeignKey(
                help_text="Tipo de vehiculo asistido segun la nomenclatura de la aseguradora.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="budgets.vehicletype",
                verbose_name="Tipo de vehiculo",
            ),
        ),
    ]
