# Generated by Django 5.2.12 on 2026-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_budget_apply_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="is_insurance_company",
            field=models.BooleanField(
                default=True,
                help_text="True: compañía aseguradora. False: cliente particular con tarifa propia. Controla el label mostrado en el desplegable del asistente de presupuestos.",
                verbose_name="Es compañía aseguradora",
            ),
        ),
    ]
