# Generated by Django 5.2.12 on 2026-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_insurer_is_insurance_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="insurer_company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre de la compañía aseguradora pura (ej: 'Europ Assistance', 'ARAG', 'Mapfre'). Permite agrupar y filtrar tarifas de la misma aseguradora atendidas por distintas empresas prestadoras.",
                max_length=150,
                verbose_name="Nombre aseguradora",
            ),
        ),
        migrations.AddField(
            model_name="insurer",
            name="service_company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empresa que presta el servicio en campo (ej: 'Transgrual', 'Grúas Alvarez', 'Asistencia y Grúas Granada'). Junto con insurer_company_name conforma el name combinado del wizard.",
                max_length=150,
                verbose_name="Empresa prestadora",
            ),
        ),
        migrations.AlterField(
            model_name="insurer",
            name="name",
            field=models.CharField(
                help_text="Nombre combinado visible en el wizard: '<Aseguradora> / <Empresa prestadora>' (ej: 'Europ Assistance / Transgrual').",
                max_length=200,
                verbose_name="Nombre",
            ),
        ),
    ]
