# Generated by Django 5.2.12 on 2026-05-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_insurer_company_and_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="total_amount_with_iva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe total del presupuesto con IVA incluido. Solo se rellena cuando apply_iva es True. El porcentaje de IVA aplicado se define en IVA_PERCENT en budgets/services.py.",
                max_digits=10,
                null=True,
                verbose_name="Total con IVA",
            ),
        ),
    ]
