# Generated by Django 5.2.12 on 2026-05-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0005_budget_total_amount_with_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="always_apply_iva",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el IVA se aplica obligatoriamente en todos los presupuestos de esta aseguradora. El operario no puede desmarcarlo.",
                verbose_name="Aplicar IVA siempre",
            ),
        ),
        migrations.AddField(
            model_name="insurer",
            name="special_night_holiday_tariff",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, el motor usa la tabla SpecialRateTariff vinculada a la tarifa activa en lugar del recargo porcentual estándar. Aplicable a aseguradoras como RACC/Zurich con precios diferenciados por franja horaria.",
                verbose_name="Tarifa especial nocturno/festivo",
            ),
        ),
        migrations.CreateModel(
            name="SpecialRateTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones internas sobre esta tabla de tarifas especiales.",
                        verbose_name="Notas internas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "insurer_tariff",
                    models.OneToOneField(
                        help_text="Tarifa activa de la aseguradora a la que está vinculada esta tabla de precios especiales nocturno/festivo.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="special_rate",
                        to="budgets.insurertariff",
                        verbose_name="Tarifa base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa especial nocturno/festivo",
                "verbose_name_plural": "Tarifas especiales nocturno/festivo",
            },
        ),
        migrations.CreateModel(
            name="SpecialRateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.CharField(
                        help_text="Código del concepto (DEPARTURE, KM_NORMAL, KM_LONG, SERVICE_LOCAL, etc.).",
                        max_length=30,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unidad de medida del concepto (FIXED, PER_KM, PERCENT).",
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio unitario para condiciones nocturnas/festivas.",
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "km_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Umbral de km a partir del cual se aplica la tarifa de largo recorrido. Solo relevante para conceptos KM_NORMAL que coexisten con KM_LONG.",
                        max_digits=8,
                        null=True,
                        verbose_name="Umbral km",
                    ),
                ),
                (
                    "min_units",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unidades mínimas facturables para este concepto. Ej: rescate mínimo 2 horas.",
                        max_digits=5,
                        null=True,
                        verbose_name="Unidades mínimas",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de vehículo al que aplica esta línea. Null indica que aplica a todos los tipos (concepto genérico).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="special_rate_lines",
                        to="budgets.vehicletype",
                        verbose_name="Tipo de vehículo",
                    ),
                ),
                (
                    "special_rate_tariff",
                    models.ForeignKey(
                        help_text="Tabla de tarifas especiales a la que pertenece esta línea.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="budgets.specialratetariff",
                        verbose_name="Tarifa especial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de tarifa especial",
                "verbose_name_plural": "Líneas de tarifa especial",
                "ordering": [
                    "special_rate_tariff",
                    "vehicle_type__sort_order",
                    "concept",
                ],
            },
        ),
    ]
