# Generated by Django 5.2.12 on 2026-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0006_insurer_iva_special_rate_tariff"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_night",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el servicio se realiza en horario nocturno. Marcado manualmente por el operario en el wizard. Independiente de is_holiday, que es calculado automaticamente por el motor segun la fecha del servicio y el calendario laboral.",
                verbose_name="Nocturno",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="is_night_or_holiday",
            field=models.BooleanField(
                default=False,
                help_text="Calculado automaticamente por el motor: True si is_night OR is_holiday. Activa el recargo NYF de la tarifa de la aseguradora. No editar directamente — se recalcula en cada llamada a calculate_budget().",
                verbose_name="Nocturno / Festivo",
            ),
        ),
    ]
