# Generated by Django 5.2.12 on 2026-05-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0007_budget_is_night"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificativo de la base (ej: 'Sevilla', 'Granada Norte').",
                        max_length=150,
                        verbose_name="Nombre de la base",
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        help_text="Municipio donde se ubica la base. Se usa para geocodificar las coordenadas y para consultar el calendario laboral local via API. Debe coincidir con el nombre oficial del municipio en espanol (ej: 'Sevilla', 'Granada', 'Jerez de la Frontera').",
                        max_length=150,
                        verbose_name="Municipio",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitud de la base en grados decimales. Si es nula, se geocodifica el municipio en la primera llamada y se persiste el resultado aqui automaticamente.",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitud de la base en grados decimales. Si es nula, se geocodifica el municipio en la primera llamada y se persiste el resultado aqui automaticamente.",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "labor_calendar",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Festivos locales de la base en formato JSON (lista de fechas ISO). Poblado automaticamente por el comando sync_base_calendars. Incluye festivos nacionales, autonomicos y locales del municipio.",
                        verbose_name="Calendario laboral",
                    ),
                ),
                (
                    "calendar_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la ultima sincronizacion del calendario laboral con la API de calendariosnacionales.com. Null si nunca se ha sincronizado.",
                        null=True,
                        verbose_name="Ultimo sync de calendario",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si esta base esta disponible para seleccion en el wizard.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificacion"
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        help_text="Par aseguradora/prestadora al que pertenece esta base. Una misma prestadora puede tener bases distintas por cada par.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bases",
                        to="budgets.insurer",
                        verbose_name="Aseguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base",
                "verbose_name_plural": "Bases",
                "ordering": ["insurer__name", "name"],
                "unique_together": {("insurer", "name")},
            },
        ),
    ]
