# Generated by Django 5.2.12 on 2026-05-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0008_base_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="base",
            field=models.ForeignKey(
                blank=True,
                help_text="Base de servicio desde la que se realiza el servicio. Determina el calendario laboral para la deteccion automatica de festivos. Nullable para compatibilidad con presupuestos anteriores a la implementacion del modelo Base.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="budgets.base",
                verbose_name="Base",
            ),
        ),
    ]
