# Generated by Django 5.2.12 on 2026-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0010_base_insurerbase_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="pk_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Punto kilometrico de la via donde se encuentra el vehiculo averiado.",
                max_digits=8,
                null=True,
                verbose_name="Punto kilometrico",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="road_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre de la via donde se encuentra el vehiculo (ej: A-45, N-331).",
                max_length=50,
                verbose_name="Carretera",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="route_calculation_mode",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("API", "API Routes")],
                default="MANUAL",
                help_text="MANUAL: el operario introduce los km directamente. API: distancia calculada automaticamente por la Routes API de Google.",
                max_length=10,
                verbose_name="Modo de calculo km",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="route_distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Distancia en km calculada por la Routes API desde la base hasta el punto kilometrico del vehiculo averiado.",
                max_digits=8,
                null=True,
                verbose_name="Distancia calculada (km)",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="route_toll_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coste estimado de peajes en EUR devuelto por la Routes API. Null cuando no hay peajes o el calculo es manual.",
                max_digits=8,
                null=True,
                verbose_name="Coste de peajes",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="service_time",
            field=models.TimeField(
                blank=True,
                help_text="Hora en la que se realiza el servicio. Se combina con service_date para construir el departureTime en la llamada a la Routes API, necesario para el calculo de peajes con dependencia horaria.",
                null=True,
                verbose_name="Hora del servicio",
            ),
        ),
    ]
