# Generated by Django 5.2.12 on 2026-06-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0011_budget_route_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="dest_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Municipio o provincia donde se encuentra el vehiculo averiado. Opcional. Se usa para refinar la geocodificacion del punto kilometrico en la llamada a la Routes API de Google.",
                max_length=150,
                verbose_name="Municipio / provincia destino",
            ),
        ),
    ]
