# Generated by Django 5.2.12 on 2026-06-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0012_add_dest_location_to_budget"),
        ("ivr_config", "0031_add_night_start_end_to_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderAssistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_order_number",
                    models.CharField(
                        help_text="Número de orden auto-generado en formato YYYYMMDDNNN. Ejemplo: 20260601001. Ordinal diario de 3 dígitos por empresa, reiniciado cada día natural.",
                        max_length=11,
                        unique=True,
                        verbose_name="Número de orden",
                    ),
                ),
                (
                    "service_date",
                    models.DateField(
                        help_text="Fecha en la que se realiza el servicio de asistencia.",
                        verbose_name="Fecha del servicio",
                    ),
                ),
                (
                    "expediente",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de expediente facilitado por la aseguradora.",
                        max_length=100,
                        verbose_name="Expediente",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En curso"),
                            ("COMPLETED", "Completada"),
                            ("INVOICED", "Facturada"),
                        ],
                        default="PENDING",
                        help_text="PENDING: orden creada, pendiente de enviar al operario. IN_PROGRESS: operario en camino o realizando el servicio. COMPLETED: servicio realizado y firmado por el cliente. INVOICED: albarán procesado y listo para facturación.",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_overnight",
                    models.BooleanField(
                        default=False,
                        help_text="Activo cuando el servicio se realiza en dos fases en días distintos. Cuando es True, phase2_data debe estar informado.",
                        verbose_name="Pernocta",
                    ),
                ),
                (
                    "machine_1",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador o matrícula de la primera máquina de servicio.",
                        max_length=100,
                        verbose_name="Máquina 1",
                    ),
                ),
                (
                    "machine_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador o matrícula de la segunda máquina. Vacío en servicios de una sola máquina.",
                        max_length=100,
                        verbose_name="Máquina 2",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre completo o razón social del cliente.",
                        max_length=200,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "client_nif",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de identificación fiscal del cliente.",
                        max_length=20,
                        verbose_name="N.I.F.",
                    ),
                ),
                (
                    "client_address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dirección postal del cliente.",
                        max_length=300,
                        verbose_name="Domicilio",
                    ),
                ),
                (
                    "client_cp",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código postal del domicilio del cliente.",
                        max_length=10,
                        verbose_name="C.P.",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Correo electrónico del cliente.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono de contacto del cliente.",
                        max_length=50,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Matrícula del vehículo asistido.",
                        max_length=20,
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "vehicle_brand",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Marca del vehículo asistido.",
                        max_length=100,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "vehicle_locality",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Localidad donde se encuentra el vehículo averiado.",
                        max_length=150,
                        verbose_name="Localidad",
                    ),
                ),
                (
                    "vehicle_province",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provincia donde se encuentra el vehículo averiado.",
                        max_length=100,
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "vehicle_pma",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso máximo autorizado del vehículo en kilogramos.",
                        max_digits=10,
                        null=True,
                        verbose_name="P.M.A. (kg)",
                    ),
                ),
                (
                    "vehicle_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Longitud del vehículo en metros.",
                        max_digits=6,
                        null=True,
                        verbose_name="Largo (m)",
                    ),
                ),
                (
                    "vehicle_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altura del vehículo en metros.",
                        max_digits=6,
                        null=True,
                        verbose_name="Alto (m)",
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Punto de recogida del vehículo averiado.",
                        max_length=300,
                        verbose_name="Recogida",
                    ),
                ),
                (
                    "base_pickup",
                    models.BooleanField(
                        default=False,
                        help_text="Activo cuando el vehículo se recoge directamente en la base.",
                        verbose_name="Recogida en base",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Punto de destino del servicio de asistencia.",
                        max_length=300,
                        verbose_name="Destino",
                    ),
                ),
                (
                    "phase1_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con todos los datos de servicio de la primera fase/máquina. Siempre informado. Consultar docstring del modelo para el esquema.",
                        verbose_name="Datos fase 1",
                    ),
                ),
                (
                    "phase2_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON con los datos de la segunda fase (pernocta) o segunda máquina. Null en servicios de fase única. Mismo esquema que phase1_data.",
                        null=True,
                        verbose_name="Datos fase 2",
                    ),
                ),
                (
                    "total_importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe total del servicio antes de aplicar el IVA.",
                        max_digits=10,
                        null=True,
                        verbose_name="Total importe",
                    ),
                ),
                (
                    "iva_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje de IVA aplicado al importe total.",
                        max_digits=5,
                        null=True,
                        verbose_name="IVA (%)",
                    ),
                ),
                (
                    "total_servicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe total del servicio con IVA incluido (TOTAL SERVICIO).",
                        max_digits=10,
                        null=True,
                        verbose_name="Total servicio",
                    ),
                ),
                (
                    "parte_operator_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de operario para el parte de producción interno.",
                        max_length=20,
                        verbose_name="Nº operario (parte)",
                    ),
                ),
                (
                    "parte_departure_base_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de salida desde la base de operaciones.",
                        null=True,
                        verbose_name="Hora salida base",
                    ),
                ),
                (
                    "parte_arrival_base_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de regreso a la base al finalizar el servicio.",
                        null=True,
                        verbose_name="Hora llegada base",
                    ),
                ),
                (
                    "parte_arrival_job_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de llegada al punto donde se encuentra el vehículo.",
                        null=True,
                        verbose_name="Hora llegada trabajo",
                    ),
                ),
                (
                    "parte_departure_job_time",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de salida del punto de trabajo.",
                        null=True,
                        verbose_name="Hora salida trabajo",
                    ),
                ),
                (
                    "parte_km_departure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Lectura del cuentakilómetros al salir de la base.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km salida",
                    ),
                ),
                (
                    "parte_km_arrival",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Lectura del cuentakilómetros al regresar a la base.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km llegada",
                    ),
                ),
                (
                    "parte_motor_a_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de funcionamiento del motor A durante el servicio.",
                        max_digits=6,
                        null=True,
                        verbose_name="Horas motor A",
                    ),
                ),
                (
                    "parte_motor_b_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de funcionamiento del motor B durante el servicio.",
                        max_digits=6,
                        null=True,
                        verbose_name="Horas motor B",
                    ),
                ),
                (
                    "parte_liters_motor_a",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Litros de combustible consumidos por el motor A.",
                        max_digits=6,
                        null=True,
                        verbose_name="Litros motor A",
                    ),
                ),
                (
                    "parte_liters_motor_b",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Litros de combustible consumidos por el motor B.",
                        max_digits=6,
                        null=True,
                        verbose_name="Litros motor B",
                    ),
                ),
                (
                    "parte_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones internas del parte de producción.",
                        verbose_name="Observaciones (parte)",
                    ),
                ),
                (
                    "whatsapp_notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se ha enviado la notificación WhatsApp al operario con el enlace al albarán digital.",
                        verbose_name="Notificación WhatsApp enviada",
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observaciones internas ADMIN. No visibles en el albarán exportado.",
                        verbose_name="Notas adicionales",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        blank=True,
                        help_text="Base de salida del servicio de asistencia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_assistance",
                        to="budgets.base",
                        verbose_name="Base de operación",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        help_text="Presupuesto aceptado del que se origina esta orden de trabajo. Null cuando la orden se crea directamente sin presupuesto previo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance",
                        to="budgets.budget",
                        verbose_name="Presupuesto de origen",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa cliente a la que pertenece esta orden de trabajo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders_assistance",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario del panel que genera la orden de trabajo.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance_created",
                        to="ivr_config.companyuser",
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        help_text="Aseguradora o cliente para el que se realiza el servicio. Heredado del Budget si existe, o seleccionado manualmente en entrada directa.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance",
                        to="budgets.insurer",
                        verbose_name="Aseguradora",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Conductor principal asignado al servicio (Máquina 1).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance_primary",
                        to="ivr_config.companyuser",
                        verbose_name="Conductor principal",
                    ),
                ),
                (
                    "operator_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segundo conductor. Solo en servicios que requieren dos máquinas simultáneas.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance_secondary",
                        to="ivr_config.companyuser",
                        verbose_name="Conductor secundario",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        help_text="Tipo de vehículo asistido según la nomenclatura de la aseguradora. Heredado del Budget si existe.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders_assistance",
                        to="budgets.vehicletype",
                        verbose_name="Tipo de vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de trabajo (asistencia)",
                "verbose_name_plural": "Órdenes de trabajo (asistencia)",
                "ordering": ["-created_at"],
            },
        ),
    ]
