# Generated by Django 5.2.12 on 2026-06-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0013_workorderassistance"),
        ("ivr_config", "0031_add_night_start_end_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderassistance",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el operario localizó el vehículo.",
                null=True,
                verbose_name="F. localizado",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="breakdown_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de avería asignado por la aseguradora.",
                max_length=50,
                verbose_name="Cód. avería",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="breakdown_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descripción de la avería facilitada por el asegurado.",
                max_length=300,
                verbose_name="Avería",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="company_observations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Observaciones internas de la empresa prestadora del servicio.",
                verbose_name="Observaciones compañía",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="completion_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de finalización completa del servicio.",
                null=True,
                verbose_name="F. finalizado",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="delivery_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dirección completa del punto de entrega del vehículo.",
                max_length=300,
                verbose_name="Dirección entrega",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="delivery_country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="País del punto de entrega del vehículo.",
                max_length=100,
                verbose_name="País entrega",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="delivery_locality",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Localidad del punto de entrega del vehículo.",
                max_length=150,
                verbose_name="Localidad entrega",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="delivery_province",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provincia del punto de entrega del vehículo.",
                max_length=100,
                verbose_name="Provincia entrega",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de punto de entrega (ej: In situ, Taller, Depósito).",
                max_length=50,
                verbose_name="Tipo entrega",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="driver_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kilómetros recorridos por el chófer según TIREA.",
                max_digits=8,
                null=True,
                verbose_name="Km chófer",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="insured_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre completo del asegurado o conductor del vehículo.",
                max_length=200,
                verbose_name="Nombre asegurado",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="insurer_comments",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comentarios de la aseguradora sobre cobertura, destino, autopista, etc.",
                verbose_name="Comentarios aseguradora",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="is_accident",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el servicio está relacionado con un accidente de tráfico.",
                verbose_name="Accidente",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="is_billable",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el servicio es facturable. Por defecto True.",
                verbose_name="Facturable",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="is_failed",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el servicio resultó fallido (vehículo no localizado, sin acceso, etc.).",
                verbose_name="Fallido",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="load_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el vehículo fue cargado.",
                null=True,
                verbose_name="F. cargado",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="location_elapsed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tiempo transcurrido hasta localizar el vehículo (ej: 01h53m).",
                max_length=20,
                verbose_name="Tiempo localizado",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="num_passengers",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Número de ocupantes del vehículo en el momento del siniestro.",
                null=True,
                verbose_name="Ocupantes",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="own_crane_management",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la gestión de la grúa es propia, sin intermediario.",
                verbose_name="Gestión propia grúa",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="pickup_country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="País del punto de recogida del vehículo.",
                max_length=100,
                verbose_name="País recogida",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="pickup_cp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código postal del punto de recogida del vehículo.",
                max_length=10,
                verbose_name="C.P. recogida",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="pickup_province",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Provincia del punto de recogida del vehículo.",
                max_length=100,
                verbose_name="Provincia recogida",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="pickup_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de punto de recogida (ej: Población, Carretera).",
                max_length=30,
                verbose_name="Tipo recogida",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="policy_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de póliza del asegurado facilitado por la aseguradora.",
                max_length=100,
                verbose_name="Nº póliza",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="provider_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de proveedor asignado por la aseguradora (ej: GP700101).",
                max_length=50,
                verbose_name="Cód. proveedor",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="repair_on_site",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el vehículo fue reparado in situ sin remolque.",
                verbose_name="Reparación in situ",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="request_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de recepción de la solicitud de la aseguradora.",
                null=True,
                verbose_name="F. solicitud",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="ris_motive",
            field=models.CharField(
                blank=True,
                choices=[],
                help_text="Motivo de la intervención RIS según el desplegable de TIREA.",
                max_length=50,
                null=True,
                verbose_name="Motivo RIS",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="second_service",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este servicio es un segundo servicio del mismo siniestro.",
                verbose_name="Segundo servicio",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="service_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de inicio del desplazamiento del operario.",
                null=True,
                verbose_name="F. inicio",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="total_km_tirea",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kilómetros totales del servicio registrados en TIREA.",
                max_digits=8,
                null=True,
                verbose_name="Km totales TIREA",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_axes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Número de ejes del vehículo asistido.",
                null=True,
                verbose_name="Ejes",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color del vehículo asistido.",
                max_length=50,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Modelo del vehículo asistido (ej: ACTROS, Sprinter).",
                max_length=100,
                verbose_name="Modelo",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_subtype_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subtipo de vehículo según TIREA.",
                max_length=100,
                verbose_name="Subtipo vehículo",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_tare",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tara del vehículo en kilogramos.",
                max_digits=10,
                null=True,
                verbose_name="Tara (kg)",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_type_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo de vehículo según TIREA (ej: Cabeza Tractora, Turismo).",
                max_length=100,
                verbose_name="Tipo vehículo",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistance",
            name="vehicle_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Peso del vehículo en kilogramos.",
                max_digits=10,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderAssistanceUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_number",
                    models.PositiveSmallIntegerField(
                        help_text="Ordinal de esta unidad dentro de la orden de trabajo (1, 2, 3...). El albarán impreso se identifica como work_order_number-unit_number.",
                        verbose_name="Nº unidad",
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Matrícula o identificador de la máquina asignada al primer tramo.",
                        max_length=100,
                        verbose_name="Máquina",
                    ),
                ),
                (
                    "machine_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Matrícula o identificador de la máquina del segundo tramo. Solo en servicios diferidos. Puede coincidir con la máquina del primer tramo.",
                        max_length=100,
                        verbose_name="Máquina (fase 2)",
                    ),
                ),
                (
                    "is_overnight",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si esta unidad realiza un servicio diferido: recoge el vehículo un día y lo traslada a destino en otro momento. Cuando es True, operator_2, machine_2 y phase2_km deben estar informados.",
                        verbose_name="Pernocta",
                    ),
                ),
                (
                    "phase1_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilómetros del primer tramo del servicio.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km fase 1",
                    ),
                ),
                (
                    "phase2_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilómetros del segundo tramo del servicio. Solo en servicios diferidos (is_overnight=True).",
                        max_digits=8,
                        null=True,
                        verbose_name="Km fase 2",
                    ),
                ),
                (
                    "departure_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe fijo de salida/enganche del servicio.",
                        max_digits=8,
                        null=True,
                        verbose_name="Salida",
                    ),
                ),
                (
                    "rescue_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de rescate/extracción facturables para esta unidad.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas rescate",
                    ),
                ),
                (
                    "wait_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de espera facturables para esta unidad.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas espera",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de la última sincronización exitosa desde la app Android. Null indica que la unidad aún no ha sido sincronizada.",
                        null=True,
                        verbose_name="Sincronizado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En curso"),
                            ("COMPLETED", "Completada"),
                        ],
                        default="PENDING",
                        help_text="PENDING: unidad creada, pendiente de enviar al operario. IN_PROGRESS: operario en camino o realizando el servicio. COMPLETED: servicio realizado y firmado por el cliente.",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Chófer asignado al primer tramo del servicio.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistance_units_primary",
                        to="ivr_config.companyuser",
                        verbose_name="Chófer",
                    ),
                ),
                (
                    "operator_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chófer del segundo tramo (base a destino). Solo en servicios diferidos (is_overnight=True). Puede coincidir con el chófer del primer tramo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistance_units_secondary",
                        to="ivr_config.companyuser",
                        verbose_name="Chófer (fase 2)",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Orden de trabajo (expediente) a la que pertenece esta unidad.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="budgets.workorderassistance",
                        verbose_name="Orden de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de orden de trabajo (asistencia)",
                "verbose_name_plural": "Unidades de orden de trabajo (asistencia)",
                "ordering": ["work_order", "unit_number"],
                "unique_together": {("work_order", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAssistanceSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_data",
                    models.TextField(
                        help_text="Imagen PNG de la firma del cliente codificada en base64.",
                        verbose_name="Firma (base64)",
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la persona que firma el albarán (opcional).",
                        max_length=200,
                        verbose_name="Firmante",
                    ),
                ),
                (
                    "signed_offline",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la firma fue capturada sin cobertura de red y sincronizada posteriormente al recuperar conexión.",
                        verbose_name="Firmado offline",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se registró la firma en el sistema.",
                        verbose_name="Fecha de firma",
                    ),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        help_text="Unidad de albarán a la que pertenece esta firma.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="budgets.workorderassistanceunit",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma digital (asistencia)",
                "verbose_name_plural": "Firmas digitales (asistencia)",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAssistanceIncidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memo",
                    models.TextField(
                        help_text="Justificación obligatoria de la incidencia. Debe describir el motivo del cambio respecto al albarán original.",
                        verbose_name="Memorándum",
                    ),
                ),
                (
                    "machine",
                    models.CharField(
                        blank=True,
                        help_text="Máquina modificada. Null si no cambia.",
                        max_length=100,
                        null=True,
                        verbose_name="Máquina",
                    ),
                ),
                (
                    "machine_2",
                    models.CharField(
                        blank=True,
                        help_text="Máquina de fase 2 modificada. Null si no cambia.",
                        max_length=100,
                        null=True,
                        verbose_name="Máquina (fase 2)",
                    ),
                ),
                (
                    "phase1_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilómetros fase 1 modificados. Null si no cambian.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km fase 1",
                    ),
                ),
                (
                    "phase2_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Kilómetros fase 2 modificados. Null si no cambian.",
                        max_digits=8,
                        null=True,
                        verbose_name="Km fase 2",
                    ),
                ),
                (
                    "departure_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe de salida modificado. Null si no cambia.",
                        max_digits=8,
                        null=True,
                        verbose_name="Salida",
                    ),
                ),
                (
                    "rescue_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de rescate modificadas. Null si no cambian.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas rescate",
                    ),
                ),
                (
                    "wait_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horas de espera modificadas. Null si no cambian.",
                        max_digits=5,
                        null=True,
                        verbose_name="Horas espera",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se registró la incidencia.",
                        verbose_name="Fecha de registro",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chófer modificado. Null si no cambia.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistance_incidences_operator",
                        to="ivr_config.companyuser",
                        verbose_name="Chófer",
                    ),
                ),
                (
                    "operator_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chófer de fase 2 modificado. Null si no cambia.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistance_incidences_operator_2",
                        to="ivr_config.companyuser",
                        verbose_name="Chófer (fase 2)",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Usuario que registró la incidencia.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistance_incidences",
                        to="ivr_config.companyuser",
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "unit",
                    models.OneToOneField(
                        help_text="Unidad de albarán a la que pertenece esta incidencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidence",
                        to="budgets.workorderassistanceunit",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidencia de unidad (asistencia)",
                "verbose_name_plural": "Incidencias de unidad (asistencia)",
            },
        ),
    ]
