# Generated by Django 5.2.12 on 2026-06-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0014_workorderassistance_arrival_time_and_more"),
        ("ivr_config", "0031_add_night_start_end_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el operario cerró el albarán sin firma del cliente.",
                null=True,
                verbose_name="Cerrado en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que la plataforma recibió el albarán firmado desde la app Android.",
                null=True,
                verbose_name="Completado en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="downloaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el operario descargó o abrió el albarán. Registrado por la app Android al cargar el albarán por primera vez.",
                null=True,
                verbose_name="Descargado en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se envió el template WhatsApp al operario. Null hasta que se ejecuta send_operator_albaran_notification().",
                null=True,
                verbose_name="Notificado en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="signed_received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el supervisor confirmó la recepción de la firma del cliente. Solo aplica a albaranes cerrados sin firma (CLOSED_UNSIGNED → SIGNED_RECEIVED).",
                null=True,
                verbose_name="Firma recibida en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="signed_received_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor que marcó la recepción de la firma del cliente. Null en todos los estados salvo SIGNED_RECEIVED.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistance_units_signed_received",
                to="ivr_config.companyuser",
                verbose_name="Firma confirmada por",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el operario marcó inicio del servicio en la app Android.",
                null=True,
                verbose_name="Iniciado en",
            ),
        ),
        migrations.AddField(
            model_name="workorderassistanceunit",
            name="unsigned_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Justificación obligatoria cuando el albarán se cierra sin firma del cliente. Vacío en albaranes cerrados con firma.",
                verbose_name="Motivo cierre sin firma",
            ),
        ),
        migrations.AlterField(
            model_name="workorderassistanceunit",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("NOTIFIED", "Notificado"),
                    ("DOWNLOADED", "Descargado"),
                    ("IN_PROGRESS", "En curso"),
                    ("COMPLETED", "Completado"),
                    ("CLOSED_UNSIGNED", "Cerrado sin firma"),
                    ("SIGNED_RECEIVED", "Firma recibida"),
                ],
                default="PENDING",
                help_text="PENDING: unidad creada, pendiente de notificar al operario. NOTIFIED: template WhatsApp enviado al operario. DOWNLOADED: operario ha abierto el albarán en la app. IN_PROGRESS: operario en servicio activo. COMPLETED: albarán recibido en plataforma con firma. CLOSED_UNSIGNED: albarán recibido sin firma — pendiente de gestión. SIGNED_RECEIVED: supervisor confirma firma recibida del cliente.",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
