# Generated by Django 5.2.12 on 2026-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0015_workorderassistanceunit_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="local_service_km_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=20,
                help_text="Kilometraje total máximo (fase 1 + fase 2) para considerar el servicio como local y aplicar el forfait SERVICE_LOCAL de la tarifa. Valor por defecto: 20 km. Dejar vacío (null) si esta aseguradora no contempla servicio local.",
                null=True,
                verbose_name="Umbral servicio local (km)",
            ),
        ),
    ]
