# Generated by Django 5.2.12 on 2026-06-11 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0016_insurer_local_service_km_threshold"),
        ("ivr_config", "0033_companyuser_is_intensive_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="NightSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Nombre descriptivo del horario nocturno (ej: "Nocturno estándar 18h–06h", "Nocturno amplio 20h–08h").',
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "night_start",
                    models.TimeField(
                        help_text="Hora de inicio de la franja nocturna. Los servicios a esta hora o después se marcan como nocturnos.",
                        verbose_name="Inicio franja nocturna",
                    ),
                ),
                (
                    "night_end",
                    models.TimeField(
                        help_text="Hora de fin de la franja nocturna. Los servicios antes de esta hora se marcan como nocturnos.",
                        verbose_name="Fin franja nocturna",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, este horario se aplica a las aseguradoras de la empresa que no tengan horario nocturno explícitamente asignado. Solo puede haber un horario por defecto activo por empresa.",
                        verbose_name="Horario por defecto",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactivar para retirar el horario del motor sin eliminarlo. Un horario inactivo no se usa aunque sea el asignado de una aseguradora.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa a la que pertenece este horario nocturno.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="night_schedules",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario nocturno",
                "verbose_name_plural": "Horarios nocturnos",
                "ordering": ["company__name", "-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="insurer",
            name="night_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Franja horaria nocturna asignada a esta aseguradora. Si no se asigna, el motor usa el horario nocturno por defecto de la empresa. Si tampoco existe, usa Company.night_start/night_end.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insurers",
                to="budgets.nightschedule",
                verbose_name="Horario nocturno",
            ),
        ),
    ]
