# Generated by Django 5.2.12 on 2026-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0017_add_night_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TollSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road_code",
                    models.CharField(
                        db_index=True,
                        help_text="Identificador oficial de la autopista. Ej: AP-7, AP-68.",
                        max_length=20,
                        verbose_name="Código de vía",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="Nombre del tramo tal como aparece en el PDF del MITMA. Ej: Málaga - Estepona.",
                        max_length=150,
                        verbose_name="Nombre del tramo",
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del peaje o salida de origen del recorrido.",
                        max_length=150,
                        verbose_name="Origen",
                    ),
                ),
                (
                    "dest_name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del peaje o salida de destino del recorrido.",
                        max_length=150,
                        verbose_name="Destino",
                    ),
                ),
                (
                    "price_light",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarifa para turismos, motos y furgonetas ligeras.",
                        max_digits=8,
                        verbose_name="Precio ligeros (€)",
                    ),
                ),
                (
                    "price_heavy_1",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarifa para camiones/autocares de 2-3 ejes (categorías 2.1 y 2.2).",
                        max_digits=8,
                        verbose_name="Precio pesados 1 (€)",
                    ),
                ),
                (
                    "price_heavy_2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarifa para camiones/autocares de 4 o más ejes totales (categorías 3.1 y 3.2).",
                        max_digits=8,
                        verbose_name="Precio pesados 2 (€)",
                    ),
                ),
                (
                    "tariff_level",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("SPECIAL", "Especial (temporada alta)"),
                        ],
                        default="NORMAL",
                        help_text="Normal: todo el año para habituales y temporada baja para todos. Especial: temporada alta para usuarios no habituales.",
                        max_length=10,
                        verbose_name="Nivel tarifario",
                    ),
                ),
                (
                    "has_free_night",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, el peaje es gratuito durante la franja nocturna definida en free_night_start / free_night_end.",
                        verbose_name="Gratuito nocturno",
                    ),
                ),
                (
                    "free_night_start",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de inicio de la franja gratuita nocturna (inclusive). Típicamente 00:00 en vías SEITT.",
                        null=True,
                        verbose_name="Inicio gratuito nocturno",
                    ),
                ),
                (
                    "free_night_end",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de fin de la franja gratuita nocturna (exclusive). Típicamente 06:00 en vías SEITT.",
                        null=True,
                        verbose_name="Fin gratuito nocturno",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Fecha de inicio de vigencia de la tarifa. Ej: 2026-01-01 para tarifas aprobadas para 2026.",
                        verbose_name="Vigente desde",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desactivar cuando la concesión expire y la vía quede libre de peaje, sin eliminar el histórico tarifario.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tramo de peaje",
                "verbose_name_plural": "Tramos de peaje",
                "ordering": ["road_code", "section_name", "origin_name", "dest_name"],
                "indexes": [
                    models.Index(
                        fields=["road_code", "tariff_level", "is_active"],
                        name="toll_road_tariff_active_idx",
                    ),
                    models.Index(
                        fields=["origin_name", "dest_name"], name="toll_od_pair_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "road_code",
                            "origin_name",
                            "dest_name",
                            "tariff_level",
                            "valid_from",
                        ),
                        name="toll_segment_unique_od_tariff_date",
                    )
                ],
            },
        ),
    ]
