# Generated by Django 5.2.12 on 2026-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0018_add_toll_segment"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="route_toll_budget_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coste de peajes que se añade al presupuesto. Aplica la tarifa completa del tramo sin tener en cuenta la gratuidad nocturna. Null cuando no hay peajes o el cálculo es manual.",
                max_digits=8,
                null=True,
                verbose_name="Coste peajes presupuestado",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="route_toll_real_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coste real de peajes aplicando gratuidad nocturna por tramo. Solo informativo: no se suma al total del presupuesto. Visible únicamente en el desglose ADMIN.",
                max_digits=8,
                null=True,
                verbose_name="Coste peajes real",
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="is_informational",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, esta línea aparece en el desglose ADMIN pero no se suma al total del presupuesto. Reservado para la línea de coste real de peajes con gratuidad nocturna aplicada.",
                verbose_name="Solo informativo",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="dest_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud del punto de peaje destino. Poblada automáticamente por geocode_toll_segments.",
                max_digits=10,
                null=True,
                verbose_name="Latitud destino",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="dest_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud del punto de peaje destino. Poblada automáticamente por geocode_toll_segments.",
                max_digits=10,
                null=True,
                verbose_name="Longitud destino",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="origin_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitud del punto de peaje origen. Poblada automáticamente por geocode_toll_segments.",
                max_digits=10,
                null=True,
                verbose_name="Latitud origen",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="origin_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitud del punto de peaje origen. Poblada automáticamente por geocode_toll_segments.",
                max_digits=10,
                null=True,
                verbose_name="Longitud origen",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="route_toll_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coste estimado de peajes en EUR. Alias de route_toll_budget_cost mantenido por compatibilidad con presupuestos anteriores.",
                max_digits=8,
                null=True,
                verbose_name="Coste de peajes",
            ),
        ),
    ]
