# Generated by Django 5.2.12 on 2026-06-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0019_budget_route_toll_budget_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="waypoints_json",
            field=models.JSONField(
                blank=True,
                help_text="Lista ordenada de paradas del planificador multi-parada. Cada elemento: {label, address, lat, lng, is_base_return}. is_base_return=True indica retorno intermedio a base (pernocta): el motor divide los tramos en ese punto para calcular km_phase1 y km_phase2 de forma independiente y activa is_overnight=True. Null en presupuestos con modo MANUAL o ruta punto a punto legacy.",
                null=True,
                verbose_name="Paradas de ruta",
            ),
        ),
    ]
