# Generated by Django 5.2.12 on 2026-06-19 04:45

import django.db.models.deletion
from django.db import migrations, models


# ---------------------------------------------------------------------------
# System concept seed data
# Datos de siembra de conceptos de sistema
# ---------------------------------------------------------------------------

SYSTEM_CONCEPTS = [
    # (code, label, default_unit, sort_order)
    ("DEPARTURE",       "Salida / Enganche",                  "FIXED",    1),
    ("SERVICE_LOCAL",   "Servicio local / Urbano",            "FIXED",    2),
    ("KM_NORMAL",       "Kilometros (normal)",                "PER_KM",   3),
    ("KM_LONG",         "Kilometros (largo recorrido)",       "PER_KM",   4),
    ("UNLOCK",          "Desbloqueo / Enganche eslingas",     "FIXED",    5),
    ("RESCUE_HOUR",     "Hora de rescate",                    "PER_HOUR", 6),
    ("WAIT_HOUR",       "Hora de espera",                     "PER_HOUR", 7),
    ("WORKER_HOUR",     "Hora de mano de obra",               "PER_HOUR", 8),
    ("ASSISTANT_HOUR",  "Hora de ayudante",                   "PER_HOUR", 9),
    ("CUSTODY_DAY",     "Custodia por dia",                   "PER_DAY",  10),
    ("NYF_PERCENT",     "Recargo nocturno/festivo (%)",       "PERCENT",  11),
    ("LOADED_PERCENT",  "Recargo vehiculo cargado (%)",       "PERCENT",  12),
]


def seed_tariff_concepts(apps, schema_editor):
    """
    Create the 12 built-in TariffConcept records (is_system=True, company=None).
    Idempotent: skips codes that already exist.
    ---
    Crea los 12 registros TariffConcept incorporados (is_system=True, company=None).
    Idempotente: omite los códigos que ya existen.
    """
    TariffConcept = apps.get_model("budgets", "TariffConcept")
    for code, label, default_unit, sort_order in SYSTEM_CONCEPTS:
        TariffConcept.objects.get_or_create(
            code=code,
            defaults={
                "label": label,
                "default_unit": default_unit,
                "is_system": True,
                "company": None,
                "sort_order": sort_order,
            },
        )


def migrate_concept_strings_to_fk(apps, schema_editor):
    """
    For every existing TariffLine and SpecialRateLine, resolve the legacy
    string concept code to the corresponding TariffConcept FK.
    Rows whose concept code is not found in TariffConcept are skipped with
    a warning printed to stdout — they will cause an IntegrityError on the
    subsequent AlterField if not resolved.
    ---
    Para cada TariffLine y SpecialRateLine existente, resuelve el código
    de concepto string legacy al FK TariffConcept correspondiente.
    Las filas cuyo código no se encuentre en TariffConcept se omiten con
    un aviso en stdout — causarán IntegrityError en el AlterField siguiente
    si no se resuelven.
    """
    TariffConcept = apps.get_model("budgets", "TariffConcept")
    TariffLine = apps.get_model("budgets", "TariffLine")
    SpecialRateLine = apps.get_model("budgets", "SpecialRateLine")

    # Build code->pk lookup to avoid per-row queries.
    # Construir lookup code->pk para evitar queries por fila.
    concept_map = {
        tc.code: tc
        for tc in TariffConcept.objects.all()
    }

    # Migrate TariffLine rows.
    # Migrar filas de TariffLine.
    tariff_lines = TariffLine.objects.all()
    for line in tariff_lines:
        # concept is still the old CharField value at this point.
        # concept es todavía el valor CharField antiguo en este punto.
        old_code = line.concept_id  # raw FK column still holds the string
        tc = concept_map.get(old_code)
        if tc is None:
            print(
                f"WARNING: TariffLine pk={line.pk} has unknown concept "
                f"code '{old_code}' — skipping."
            )
            continue
        line.concept_id = tc.pk
        line.save(update_fields=["concept_id"])

    # Migrate SpecialRateLine rows.
    # Migrar filas de SpecialRateLine.
    special_lines = SpecialRateLine.objects.all()
    for line in special_lines:
        old_code = line.concept_id
        tc = concept_map.get(old_code)
        if tc is None:
            print(
                f"WARNING: SpecialRateLine pk={line.pk} has unknown concept "
                f"code '{old_code}' — skipping."
            )
            continue
        line.concept_id = tc.pk
        line.save(update_fields=["concept_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0020_budget_waypoints_json"),
        ("ivr_config", "0033_companyuser_is_intensive_override"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tariffline",
            options={
                "ordering": [
                    "tariff",
                    "vehicle_type__sort_order",
                    "concept__sort_order",
                ],
                "verbose_name": "Linea de tarifa",
                "verbose_name_plural": "Lineas de tarifa",
            },
        ),
        migrations.CreateModel(
            name="TariffConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador interno del concepto. Único en todo el sistema. Los conceptos de sistema usan mayúsculas (ej: DEPARTURE). Los conceptos personalizados se generan automáticamente.",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Texto mostrado en el desplegable al añadir una línea de tarifa y en los documentos exportados.",
                        max_length=200,
                        verbose_name="Nombre visible",
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        help_text="Tipo de unidad preseleccionado al crear una línea con este concepto. El usuario puede cambiarlo.",
                        max_length=10,
                        verbose_name="Unidad por defecto",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, este concepto forma parte del catálogo base del motor de cálculo y no puede editarse ni eliminarse desde el panel.",
                        verbose_name="Concepto de sistema",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posición en el desplegable. Menor número = aparece antes.",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa propietaria de este concepto. Nulo para conceptos de sistema accesibles a todas las empresas.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_tariff_concepts",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de tarifa",
                "verbose_name_plural": "Conceptos de tarifa",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.RunPython(
            seed_tariff_concepts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            migrate_concept_strings_to_fk,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="specialrateline",
            name="concept",
            field=models.ForeignKey(
                help_text="Tipo de concepto facturable que representa esta línea especial nocturno/festivo. Referencia el mismo catálogo TariffConcept que TariffLine.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="special_rate_lines",
                to="budgets.tariffconcept",
                verbose_name="Concepto",
            ),
        ),
        migrations.AlterField(
            model_name="tariffline",
            name="concept",
            field=models.ForeignKey(
                help_text="Tipo de concepto facturable que representa esta línea. Selecciona un concepto del catálogo — sistema o personalizado de tu empresa.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tariff_lines",
                to="budgets.tariffconcept",
                verbose_name="Concepto",
            ),
        ),
    ]
