# Generated by Django 5.2.12 on 2026-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0021_tariff_concept_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="concept_code",
            field=models.CharField(
                help_text="Codigo interno del concepto aplicado (ej: DEPARTURE, KM_NORMAL, NYF_PERCENT). max_length=50 alineado con TariffConcept.code.",
                max_length=50,
                verbose_name="Codigo de concepto",
            ),
        ),
    ]
