# Generated by Django 5.2.12 on 2026-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0022_alter_budgetline_concept_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tollsegment",
            name="markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de recargo sobre el precio base (price_heavy_1) aplicado al cliente. Ej: 10 → se factura el 110% del coste real del peaje. 0 sin recargo.",
                max_digits=5,
                verbose_name="Recargo (%)",
            ),
        ),
    ]
