# Generated by Django 5.2.12 on 2026-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0023_tollsegment_markup_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tollsegment",
            name="season_high_end",
            field=models.DateField(
                blank=True,
                help_text="Fecha de fin de la temporada alta (día/mes, inclusive). Solo se usan el mes y el día — el año se ignora. Si no se configura, se aplica price_heavy_1 todo el año. Ej: 2026-09-30 → temporada alta hasta el 30 de septiembre.",
                null=True,
                verbose_name="Fin temporada alta",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="season_high_start",
            field=models.DateField(
                blank=True,
                help_text="Fecha de inicio de la temporada alta (día/mes). Solo se usan el mes y el día — el año se ignora. Si no se configura, se aplica price_heavy_1 todo el año. Ej: 2026-06-15 → temporada alta desde el 15 de junio.",
                null=True,
                verbose_name="Inicio temporada alta",
            ),
        ),
    ]
