# Generated by Django 5.2.12 on 2026-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0024_tollsegment_season_high_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tollsegment",
            name="price_heavy_1_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarifa para camiones/autocares de 2-3 ejes en temporada alta. Dejar vacío si no hay distinción estacional.",
                max_digits=8,
                null=True,
                verbose_name="Precio pesados 1 temporada alta (€)",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="price_heavy_2_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarifa para camiones/autocares de 4+ ejes en temporada alta. Dejar vacío si no hay distinción estacional.",
                max_digits=8,
                null=True,
                verbose_name="Precio pesados 2 temporada alta (€)",
            ),
        ),
        migrations.AddField(
            model_name="tollsegment",
            name="price_light_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarifa para turismos, motos y furgonetas ligeras en temporada alta. Dejar vacío si no hay distinción estacional.",
                max_digits=8,
                null=True,
                verbose_name="Precio ligeros temporada alta (€)",
            ),
        ),
    ]
