# Generated by Django 5.2.12 on 2026-06-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0025_tollsegment_price_heavy_1_high_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tollsegment",
            name="markup_percent",
        ),
    ]
