# Generated by Django 5.2.12 on 2026-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0026_remove_tollsegment_markup_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="encoded_polyline",
            field=models.TextField(
                blank=True,
                help_text="Polyline Google Encoded de la ruta confirmada. En servicios con pernocta, dos polylines separadas por \\x01. Usada por calculate_budget() para el cruce con TollSegment.",
                null=True,
                verbose_name="Polyline codificada",
            ),
        ),
    ]
