# Generated by Django 5.2.12 on 2026-07-01 06:21

import budgets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0027_budget_encoded_polyline"),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPdfImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to=budgets.models._tariff_pdf_upload_to,
                        verbose_name="PDF de tarifa",
                    ),
                ),
                (
                    "extraction_raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Extracción bruta (JSON)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pendiente de revisión"),
                            ("APPLIED", "Aplicado"),
                            ("DISCARDED", "Descartado"),
                            ("ERROR", "Error de extracción"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="Mensaje de error"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_pdf_imports",
                        to="budgets.insurer",
                        verbose_name="Aseguradora origen",
                    ),
                ),
                (
                    "insurer_copy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariff_pdf_import_copy",
                        to="budgets.insurer",
                        verbose_name="Aseguradora copia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importación de tarifa por PDF",
                "verbose_name_plural": "Importaciones de tarifa por PDF",
                "ordering": ["-created_at"],
            },
        ),
    ]
