# Generated by Django 5.2.12 on 2026-07-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0028_tariffpdfimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="is_night_or_holiday_manual_override",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Cuando no es null, sustituye por completo el cálculo automático de is_night_or_holiday. Se establece desde el checkbox del modo Manual del wizard de presupuestos. Null en presupuestos con planificación de ruta o anteriores a esta funcionalidad.",
                null=True,
                verbose_name="Nocturno / Festivo (override manual)",
            ),
        ),
    ]
