# Generated by Django 5.2.12 on 2026-07-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0029_budget_is_night_or_holiday_manual_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="manual_toll_segments",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Selección itemizada de tramos TollSegment con número de pases, del modo Manual del wizard. Formato: {id_tramo: nº_pases}. Se suma a route_toll_budget_cost (Otros peajes), no lo sustituye.",
                null=True,
                verbose_name="Peajes por tramo (modo manual)",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="is_night_or_holiday_manual_override",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Cuando es True, fuerza is_night_or_holiday a True aunque el calendario/horario no lo indiquen. El cálculo automático por calendario se ejecuta siempre — este campo no lo sustituye, solo puede forzarlo a True. Se establece desde el checkbox del modo Manual del wizard de presupuestos.",
                null=True,
                verbose_name="Nocturno / Festivo (forzar)",
            ),
        ),
    ]
