import json
import os
from datetime import date

from django.core.management.base import BaseCommand, CommandError

from budgets.models import TollSegment


class Command(BaseCommand):
    """
    Management command to import toll segment data from a JSON file
    generated by web_scrapping/scrape_toll_pdfs.py into the TollSegment
    table. Supports dry-run mode and selective road filtering.
    Idempotent: uses update_or_create on the unique constraint fields.
    ---
    Comando de gestion para importar datos de tramos de peaje desde un
    archivo JSON generado por web_scrapping/scrape_toll_pdfs.py a la
    tabla TollSegment. Soporta modo dry-run y filtrado por via.
    Idempotente: usa update_or_create sobre los campos de la restriccion
    unica.
    """

    help = (
        "Importa tramos de peaje desde un archivo JSON "
        "(generado por scrape_toll_pdfs.py) a la tabla TollSegment."
    )

    def add_arguments(self, parser):
        """
        Define command-line arguments.
        ---
        Define los argumentos de linea de comandos.
        """
        parser.add_argument(
            "json_path",
            nargs="?",
            default=os.path.join(
                os.path.dirname(
                    os.path.dirname(
                        os.path.dirname(
                            os.path.dirname(
                                os.path.abspath(__file__)
                            )
                        )
                    )
                ),
                "toll_segments.json",
            ),
            help=(
                "Ruta al archivo JSON de tramos de peaje. "
                "Por defecto: toll_segments.json en la raiz del proyecto."
            ),
        )
        parser.add_argument(
            "--road",
            dest="road_filter",
            default=None,
            help=(
                "Filtrar importacion por codigo de via. "
                "Ej: --road AP-7"
            ),
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            dest="dry_run",
            default=False,
            help=(
                "Simula la importacion sin escribir en la base de datos."
            ),
        )
        parser.add_argument(
            "--deactivate-old",
            action="store_true",
            dest="deactivate_old",
            default=False,
            help=(
                "Desactiva los tramos existentes de las vias incluidas "
                "en el JSON antes de importar las nuevas tarifas. "
                "Util para actualizaciones anuales de tarifas."
            ),
        )

    def handle(self, *args, **options):
        """
        Execute the import: read JSON, validate, upsert TollSegment rows.
        ---
        Ejecuta la importacion: leer JSON, validar, upsert filas
        TollSegment.
        """
        json_path = options["json_path"]
        road_filter = options["road_filter"]
        dry_run = options["dry_run"]
        deactivate_old = options["deactivate_old"]

        # Validate input file existence.
        # Validar existencia del archivo de entrada.
        if not os.path.isfile(json_path):
            raise CommandError(
                f"Archivo JSON no encontrado: {json_path}"
            )

        self.stdout.write(
            f"# [INFO] Leyendo: {json_path}"
        )

        with open(json_path, "r", encoding="utf-8") as fh:
            try:
                data = json.load(fh)
            except json.JSONDecodeError as exc:
                raise CommandError(
                    f"JSON invalido: {exc}"
                ) from exc

        segments = data.get("segments", [])
        generated_at = data.get("generated_at", "desconocida")
        total_in_file = data.get("total_segments", len(segments))

        self.stdout.write(
            f"# [INFO] Fecha de generacion del JSON: {generated_at}"
        )
        self.stdout.write(
            f"# [INFO] Tramos en archivo: {total_in_file}"
        )

        if road_filter:
            segments = [
                s for s in segments
                if s.get("road_code") == road_filter
            ]
            self.stdout.write(
                f"# [INFO] Filtro aplicado: {road_filter} "
                f"-> {len(segments)} tramos"
            )

        if not segments:
            self.stdout.write("# [WARN] No hay tramos para importar.")
            return

        # Optionally deactivate existing segments for roads in the JSON.
        # Opcionalmente desactivar tramos existentes de las vias del JSON.
        if deactivate_old and not dry_run:
            roads_in_file = {s["road_code"] for s in segments}
            deactivated = TollSegment.objects.filter(
                road_code__in=roads_in_file,
                is_active=True,
            ).update(is_active=False)
            self.stdout.write(
                f"# [INFO] Tramos desactivados: {deactivated}"
            )

        created_count = 0
        updated_count = 0
        error_count = 0

        for idx, seg in enumerate(segments, start=1):
            # Validate required fields.
            # Validar campos obligatorios.
            required = [
                "road_code", "section_name", "origin_name",
                "dest_name", "price_light", "price_heavy_1",
                "price_heavy_2", "tariff_level", "valid_from",
            ]
            missing = [f for f in required if f not in seg]
            if missing:
                self.stderr.write(
                    f"# [ERROR] Tramo {idx}: campos faltantes "
                    f"{missing} — omitido."
                )
                error_count += 1
                continue

            # Parse valid_from date.
            # Parsear fecha valid_from.
            try:
                valid_from = date.fromisoformat(seg["valid_from"])
            except (ValueError, TypeError):
                self.stderr.write(
                    f"# [ERROR] Tramo {idx}: valid_from invalido "
                    f"'{seg['valid_from']}' — omitido."
                )
                error_count += 1
                continue

            # Parse time fields.
            # Parsear campos de hora.
            free_night_start = seg.get("free_night_start") or None
            free_night_end = seg.get("free_night_end") or None

            # Parse optional high-season date fields.
            # Parsear campos opcionales de temporada alta.
            season_high_start = None
            season_high_end   = None
            if seg.get("season_high_start"):
                try:
                    season_high_start = date.fromisoformat(
                        seg["season_high_start"]
                    )
                except (ValueError, TypeError):
                    pass
            if seg.get("season_high_end"):
                try:
                    season_high_end = date.fromisoformat(
                        seg["season_high_end"]
                    )
                except (ValueError, TypeError):
                    pass

            defaults = {
                "section_name":      seg["section_name"],
                "price_light":       seg["price_light"],
                "price_heavy_1":     seg["price_heavy_1"],
                "price_heavy_2":     seg["price_heavy_2"],
                "price_light_high":  seg.get("price_light_high"),
                "price_heavy_1_high": seg.get("price_heavy_1_high"),
                "price_heavy_2_high": seg.get("price_heavy_2_high"),
                "markup_percent":    seg.get("markup_percent", 0),
                "season_high_start": season_high_start,
                "season_high_end":   season_high_end,
                "has_free_night":    seg.get("has_free_night", False),
                "free_night_start":  free_night_start,
                "free_night_end":    free_night_end,
                "is_active":         seg.get("is_active", True),
            }

            lookup = {
                "road_code": seg["road_code"],
                "origin_name": seg["origin_name"],
                "dest_name": seg["dest_name"],
                "tariff_level": seg["tariff_level"],
                "valid_from": valid_from,
            }

            if dry_run:
                self.stdout.write(
                    f"# [DRY-RUN] {seg['road_code']} | "
                    f"{seg['origin_name']} -> {seg['dest_name']} "
                    f"[{seg['tariff_level']}] "
                    f"L={seg['price_light']}/{seg.get('price_light_high','—')} "
                    f"P1={seg['price_heavy_1']}/{seg.get('price_heavy_1_high','—')} "
                    f"P2={seg['price_heavy_2']}/{seg.get('price_heavy_2_high','—')}"
                )
                created_count += 1
                continue

            try:
                _, created = TollSegment.objects.update_or_create(
                    **lookup,
                    defaults=defaults,
                )
                if created:
                    created_count += 1
                else:
                    updated_count += 1
            except Exception as exc:
                self.stderr.write(
                    f"# [ERROR] Tramo {idx} "
                    f"{seg.get('road_code')} "
                    f"{seg.get('origin_name')}->"
                    f"{seg.get('dest_name')}: {exc}"
                )
                error_count += 1

        mode = "[DRY-RUN] " if dry_run else ""
        self.stdout.write(
            f"# [{mode}DONE] Creados: {created_count} | "
            f"Actualizados: {updated_count} | "
            f"Errores: {error_count}"
        )
        self.stdout.write(
            f"# [TOTAL] TollSegment en BD: "
            f"{TollSegment.objects.count()}"
        )

