# Generated by Django 5.2.12 on 2026-06-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0008_breakdownticket_conversation_log_and_more"),
        ("fleet", "0005_add_first_repair_to_machineasset"),
        ("ivr_config", "0039_workperiodgroup_workperiod_group"),
        ("work_order_processor", "0026_workorderentry_has_diet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("PHOTO", "Foto"), ("PDF", "PDF")],
                        max_length=10,
                        verbose_name="Tipo de origen",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="delivery_notes/photos/",
                        verbose_name="Foto del albarán",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="delivery_notes/pdfs/",
                        verbose_name="PDF del albarán",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Proveedor"
                    ),
                ),
                (
                    "supplier_tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="NIF/CIF proveedor"
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de albarán"
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de albarán"
                    ),
                ),
                (
                    "extraction_raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Respuesta bruta de extracción",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSED", "Procesado"),
                            ("ASSIGNED", "Asignado"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_notes",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_delivery_notes",
                        to="ivr_config.companyuser",
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Albarán de proveedor",
                "verbose_name_plural": "Albaranes de proveedor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.PositiveIntegerField(verbose_name="Número de línea"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio total línea",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("MACHINE", "Máquina"),
                            ("WAREHOUSE", "Almacén"),
                            ("UNASSIGNED", "Sin asignar"),
                        ],
                        default="UNASSIGNED",
                        max_length=15,
                        verbose_name="Tipo de asignación",
                    ),
                ),
                (
                    "delivery_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="spare_parts.deliverynote",
                        verbose_name="Albarán",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_note_lines",
                        to="fleet.machineasset",
                        verbose_name="Máquina asignada",
                    ),
                ),
                (
                    "work_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_note_lines",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Línea de parte vinculada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de albarán",
                "verbose_name_plural": "Líneas de albarán",
                "ordering": ["delivery_note", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="SparePartEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "is_uncountable",
                    models.BooleanField(default=False, verbose_name="Es incontable"),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cantidad en stock",
                    ),
                ),
                (
                    "stock_level",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Nivel de stock"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAREHOUSE", "Almacén"),
                            ("PRE_ASSIGNED", "Pre-asignado (limbo)"),
                            ("CONSUMED", "Consumido"),
                        ],
                        default="WAREHOUSE",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "pre_assigned_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de entrada en el limbo",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de consumo real"
                    ),
                ),
                (
                    "origin_type",
                    models.CharField(
                        choices=[
                            ("SUPPLIER", "Proveedor"),
                            ("SALVAGED", "Reciclado interno"),
                        ],
                        default="SUPPLIER",
                        max_length=10,
                        verbose_name="Tipo de origen",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Proveedor"
                    ),
                ),
                (
                    "supplier_tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="NIF/CIF proveedor"
                    ),
                ),
                (
                    "supplier_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección proveedor"
                    ),
                ),
                (
                    "purchase_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio unitario de compra",
                    ),
                ),
                (
                    "purchase_discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Descuento de compra (%)",
                    ),
                ),
                (
                    "purchase_total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio total de compra",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breakdown_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_part_entries",
                        to="chat.breakdownticket",
                        verbose_name="Ticket de avería destino",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_part_entries",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spare_part_entries",
                        to="fleet.machineasset",
                        verbose_name="Máquina destino",
                    ),
                ),
                (
                    "origin_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvaged_spare_part_entries",
                        to="fleet.machineasset",
                        verbose_name="Máquina donante",
                    ),
                ),
                (
                    "origin_work_order_entry_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salvaged_spare_part_entries",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Línea de parte donde se documentó la retirada",
                    ),
                ),
                (
                    "source_delivery_note_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_spare_part_entries",
                        to="spare_parts.deliverynoteline",
                        verbose_name="Línea de albarán de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repuesto",
                "verbose_name_plural": "Repuestos",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="deliverynoteline",
            name="spare_part_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_delivery_note_lines",
                to="spare_parts.sparepartentry",
                verbose_name="Entrada en stock resultante",
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Salida"),
                            ("ADJUST", "Ajuste"),
                            ("RETURN_TO_WAREHOUSE", "Devolución a almacén"),
                            ("SALVAGE", "Entrada por reciclado interno"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Cantidad movida",
                    ),
                ),
                (
                    "level_before",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Nivel antes"
                    ),
                ),
                (
                    "level_after",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Nivel después"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "breakdown_ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="chat.breakdownticket",
                        verbose_name="Ticket de avería vinculado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="ivr_config.companyuser",
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "delivery_note_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="spare_parts.deliverynoteline",
                        verbose_name="Línea de albarán origen",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="fleet.machineasset",
                        verbose_name="Máquina destino",
                    ),
                ),
                (
                    "spare_part_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="spare_parts.sparepartentry",
                        verbose_name="Repuesto",
                    ),
                ),
                (
                    "spare_part_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="work_order_processor.sparepartline",
                        verbose_name="Línea de repuesto del parte (consumo materializado)",
                    ),
                ),
                (
                    "work_order_entry_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="work_order_processor.workorderentryline",
                        verbose_name="Línea de parte vinculada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-created_at"],
            },
        ),
    ]
