# Generated by Django 5.2.12 on 2026-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynoteline",
            name="machine_code_raw",
            field=models.CharField(
                blank=True,
                help_text="Código de máquina o almacén anotado a mano en el albarán, tal como lo transcribió Gemini Vision (sin normalizar). Editable en la revisión antes de confirmar la asignación. Añadido en S002-H10 para soportar el Paso 3 del anexo (revisión de DeliveryNoteDetailView).",
                max_length=100,
                verbose_name="Código máquina/almacén (bruto)",
            ),
        ),
    ]
