# Generated by Django 5.2.12 on 2026-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0002_deliverynoteline_machine_code_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="recipient_company_code",
            field=models.CharField(
                blank=True,
                help_text="Código corto de la empresa del grupo, resuelto desde recipient_tax_id (ej: GRA, TRA, GRG). Vacío si el CIF no se ha podido leer o no está todavía en el catálogo -- requiere revisión manual en ese caso.",
                max_length=20,
                verbose_name="Código de empresa destinataria",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre legal de la empresa del grupo a la que va dirigido el albarán, tal como figura impreso en el documento.",
                max_length=255,
                verbose_name="Razón social destinataria",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="recipient_tax_id",
            field=models.CharField(
                blank=True,
                help_text="CIF de la empresa destinataria tal como figura en el albarán. Es la clave usada para resolver recipient_company_code de forma fiable, ya que la razón social aparece con variantes de texto en el catálogo.",
                max_length=50,
                verbose_name="NIF/CIF destinatario",
            ),
        ),
    ]
