# Generated by Django 5.2.12 on 2026-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_breakdownticket_conversation_log_and_more"),
        ("fleet", "0005_add_first_repair_to_machineasset"),
        ("ivr_config", "0040_companyuser_can_view_budget_breakdown"),
        ("spare_parts", "0003_deliverynote_recipient_company_code_and_more"),
        ("work_order_processor", "0027_sparepartline_spare_part_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepartentry",
            name="internal_reference",
            field=models.CharField(
                blank=True,
                help_text="Referencia propia de la empresa, estable frente a cambios de proveedor. Generada automáticamente, nunca importada de un albarán externo. Ver anexo H10, confirmado por Miguel Ángel el 2026-07-06: la referencia del proveedor puede cambiar si se cambia de proveedor para la misma pieza física, así que el catálogo y el consumo se identifican por esta referencia interna, no por la del proveedor.",
                max_length=20,
                verbose_name="Referencia interna",
            ),
        ),
        migrations.AlterField(
            model_name="sparepartentry",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Referencia proveedor"
            ),
        ),
        migrations.AddConstraint(
            model_name="sparepartentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("internal_reference", ""), _negated=True),
                fields=("company", "internal_reference"),
                name="unique_internal_reference_per_company",
            ),
        ),
    ]
