# Generated by Django 5.2.12 on 2026-07-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0040_companyuser_can_view_budget_breakdown"),
        ("spare_parts", "0004_sparepartentry_internal_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepartentry",
            name="supplier_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Proveedor (texto libre, histórico)",
            ),
        ),
        migrations.AlterField(
            model_name="sparepartentry",
            name="supplier_tax_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="NIF/CIF proveedor (texto libre, histórico)",
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("EXTERNAL", "Proveedor externo"),
                            ("SALVAGE", "Reciclado interno"),
                        ],
                        default="EXTERNAL",
                        max_length=10,
                        verbose_name="Tipo de proveedor",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Vacío para el proveedor de tipo Reciclado interno.",
                        max_length=50,
                        verbose_name="NIF/CIF",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="sparepartentry",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia real al modelo Supplier (2026-07-06, aditivo). Los campos supplier_name/supplier_tax_id/supplier_address de abajo son el texto libre extraído por Gemini Vision del albarán -- todavía no se resuelven automáticamente contra este FK. Ver docstring de Supplier.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_part_entries",
                to="spare_parts.supplier",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tax_id", ""), _negated=True),
                fields=("company", "tax_id"),
                name="unique_supplier_tax_id_per_company",
            ),
        ),
    ]
