# Generated by Django 5.2.12 on 2026-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0005_alter_sparepartentry_supplier_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="general_machine_code_raw",
            field=models.CharField(
                blank=True,
                help_text="Anotación #CODIGO# general del albarán completo (fuera de cualquier línea concreta), tal como se extrajo o se corrigió a mano. Se usa solo como respaldo para las líneas sin anotación propia. Vacío si el albarán no lleva una anotación general.",
                max_length=100,
                verbose_name="Código general del albarán",
            ),
        ),
    ]
