# Generated by Django 5.2.12 on 2026-07-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0006_deliverynote_general_machine_code_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text='Referencia real al Supplier resuelto por CIF en confirm_delivery_note() (2026-07-08, gap señalado por Miguel Ángel: dos albaranes del mismo proveedor pueden traer el nombre impreso ligeramente distinto -- "ERC CASADO" vs "ELECTRORECAMBIOS CASADO SL" -- y sin este FK el listado mostraba cada uno con su propio texto en vez del nombre canónico ya deduplicado por CIF). Null hasta la confirmación (status=ASSIGNED) o si no hay CIF extraído -- supplier_name/supplier_tax_id de abajo siguen siendo el único rastro en ese caso, igual que antes.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes",
                to="spare_parts.supplier",
                verbose_name="Proveedor (resuelto)",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="supplier_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Proveedor (texto libre de este albarán)",
            ),
        ),
    ]
