# Generated by Django 5.2.12 on 2026-07-13
# S014-H10, Bloque B: escrita directamente (nuevo flujo de migraciones
# automatizado, ver com-migrations) replicando el diff real ya
# calculado por `manage.py makemigrations` contra la BD de producción
# en la consola de Miguel Angel (salida confirmada: "~ Alter field
# status on deliverynote" + "+ Create constraint
# unique_delivery_number_per_company on model deliverynote", sin
# ninguna otra operacion ni pregunta interactiva de Django).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0007_deliverynote_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de procesar"),
                    ("PROCESSED", "Procesado"),
                    ("ASSIGNED", "Asignado"),
                    ("ERROR", "Error de extracción"),
                ],
                default="PENDING",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverynote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("delivery_number", ""), _negated=True),
                fields=("company", "delivery_number"),
                name="unique_delivery_number_per_company",
            ),
        ),
    ]
