# Generated by Django 5.2.12 on 2026-07-13
# S014-H10: persistencia en Google Drive de las fotos/PDF de albarán,
# sustituye al envío por correo. Campos nuevos, ambos blank=True -- sin
# valor por defecto necesario para las filas existentes (cadena vacía
# es el default natural de CharField/URLField con blank=True), sin
# ambigüedad de las descritas en com-migrations sección 2.3.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0008_alter_deliverynote_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="drive_file_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="ID de archivo en Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="drive_web_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                verbose_name="Enlace de Google Drive",
            ),
        ),
    ]
