# Generated by Django 5.2.12 on 2026-07-16
# S022: persistencia en Google Cloud Storage, sustituye a Google Drive
# para toda subida nueva de albaranes (H23 prioridad 0 -- migración
# fuera de Drive). Campo nuevo, blank=True -- sin valor por defecto
# necesario para las filas existentes (cadena vacía es el default
# natural de CharField con blank=True), sin ambigüedad de las
# descritas en com-migrations sección 2.3. drive_file_id/drive_web_link
# no se tocan (quedan como legado, ver spare_parts/models.py).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spare_parts", "0009_deliverynote_drive_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="gcs_blob_name",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Ruta del objeto en Google Cloud Storage",
            ),
        ),
    ]
