# Generated by Django 5.2.12 on 2026-07-20
# S025: asignacion MANUAL de maquina/centro de gasto cuando la
# extraccion automatica no encuentra codigo valido -- reversion
# parcial de la norma S015 ("no se admite correccion manual"),
# decision explicita de Miguel Angel. manually_assigned/
# manually_assigned_by/manually_assigned_at dejan constancia
# obligatoria de que la asignacion no vino de la extraccion
# automatica. Campos nuevos con default/null=True -- sin ambiguedad
# para las filas existentes (com-migrations seccion 2.3): todas las
# filas ya confirmadas se consideran automaticas por defecto
# (manually_assigned=False).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr_config", "0042_companyuser_base"),
        ("spare_parts", "0010_deliverynote_gcs_blob_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="manually_assigned",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True si la máquina/centro de gasto de este "
                    "albarán se asignó a mano (la extracción "
                    "automática no encontró ningún código válido) -- "
                    "nunca confundir con una asignación automática "
                    "real."
                ),
                verbose_name="Asignación manual",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="manually_assigned_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha de asignación manual",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="manually_assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes_manually_assigned",
                to="ivr_config.companyuser",
                verbose_name="Asignado manualmente por",
            ),
        ),
    ]
