# Generated by Django 5.2.12 on 2026-07-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ivr_config", "0042_companyuser_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre de archivo original",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        upload_to="document_ingestion/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_ROUTING", "Pendiente de enrutar"),
                            ("ROUTED", "Enrutado"),
                            (
                                "NEEDS_REVIEW",
                                "Dominio no identificado -- revisar a mano",
                            ),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING_ROUTING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Mensaje de error",
                    ),
                ),
                (
                    "routed_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Dominio resuelto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de subida",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingested_files",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingested_files_uploaded",
                        to="ivr_config.companyuser",
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo en ingesta (sin enrutar)",
                "verbose_name_plural": "Archivos en ingesta (sin enrutar)",
                "ordering": ["-created_at"],
            },
        ),
    ]
