# Generated by Django 5.2.12 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ingestion", "0002_ingestedfile_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestedfile",
            name="source_folder_path",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Carpeta de origen",
            ),
        ),
        migrations.AddField(
            model_name="ingestedfile",
            name="upload_batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=40,
                verbose_name="Lote de subida",
            ),
        ),
        migrations.AddField(
            model_name="ingestedfile",
            name="routed_document_pk",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="PK del documento resultante",
            ),
        ),
    ]
