# Generated by Django 5.2.12 on 2026-07-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ingestion", "0003_ingestedfile_live_upload_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnedDocumentTypeKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Candidata extraída del nombre de archivo tras quitar código de máquina/matrícula, fecha y extensión -- ver preflight_discard_service._extract_candidate_keyword().",
                        max_length=100,
                        verbose_name="Palabra clave aprendida",
                    ),
                ),
                (
                    "canonical_group",
                    models.CharField(
                        help_text="Grupo al que se asocia esta keyword -- si el document_type de Gemini coincidió con un grupo ya existente (ver _OBSOLESCENCE_GROUP_KEYWORDS) se usa ese; si no, se crea un grupo nuevo a partir del propio document_type de Gemini, normalizado (Miguel Ángel, S016: Gemini puede proponer categorías libres, sin lista cerrada -- este campo hereda esa libertad).",
                        max_length=100,
                        verbose_name="Grupo canónico",
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Trazabilidad -- el nombre de archivo real que disparó este aprendizaje la primera vez.",
                        max_length=255,
                        verbose_name="Nombre de archivo de origen",
                    ),
                ),
                (
                    "source_document_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Texto tal cual lo devolvió Gemini la primera vez -- trazabilidad, no se usa para matching (para eso está canonical_group).",
                        max_length=100,
                        verbose_name="document_type de Gemini (origen)",
                    ),
                ),
                (
                    "occurrences",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Se incrementa cada vez que esta misma keyword vuelve a aprenderse a partir de otro documento -- señal de confianza para la revisión manual posterior, nunca desactiva/activa nada por sí sola.",
                        verbose_name="Repeticiones",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False si se desactivó a mano desde el listado -- una entrada inactiva nunca participa en la determinación de tipo, pero se conserva para histórico/auditoría en vez de borrarse.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Primera vez vista",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última vez vista",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learned_document_type_keywords",
                        to="ivr_config.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palabra clave de tipo de documento (aprendida)",
                "verbose_name_plural": "Palabras clave de tipo de documento (aprendidas)",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddConstraint(
            model_name="learneddocumenttypekeyword",
            constraint=models.UniqueConstraint(
                fields=("company", "keyword"),
                name="unique_learned_keyword_per_company",
            ),
        ),
    ]
