# Generated by Django 5.2.12 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ingestion", "0004_learneddocumenttypekeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestedfile",
            name="forced_domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACHINE", "Maquinaria"),
                    ("PERSONAL", "Personal"),
                ],
                default="",
                max_length=20,
                verbose_name="Dominio elegido al subir",
            ),
        ),
    ]
